Repository az-digital/az_quickstart, pull requests merged in 2020-02, with the labels that each got.

#25 Closes #24 Update Drupal core-recommended version to 8.8.2 in composer.json
  composer.json
Labels: enhancement, good first issue

#21 Add User Story, Task & Spike templates to github issues #20
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/spike.md
  .github/ISSUE_TEMPLATE/task.md
  .github/ISSUE_TEMPLATE/user_story.md
Labels: enhancement

#23 Fixes #22. Replaced uadigital.arizona.edu with digital.arizona.edu in composer.json.
  composer.json
Labels: documentation

#32 Drupal 8 Coding Standards on CONTRIBUTING.md and COPYRIGHT.txt
  CONTRIBUTING.md
  COPYRIGHT.txt
Labels: bug

#30 Add "Proposed Resolution" to issue bug and feature templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#37 Fixes #36: Added .gitattributes to help GitHub classify various files correctly.
  .gitattributes
Labels: documentation
