Repository az-digital/az_quickstart, pull requests merged in 2020-11, with the labels that each got.

#352 Add full html paragraph
  .github/workflows/security.yml
  composer.json
  config/install/editor.editor.full_html.yml
  config/install/filter.format.full_html.yml
  modules/custom/az_paragraphs/az_paragraphs_html/README.md
  modules/custom/az_paragraphs/az_paragraphs_html/az_paragraphs_html.info.yml
  modules/custom/az_paragraphs/az_paragraphs_html/config/install/core.entity_form_display.paragraph.az_html.default.yml
  modules/custom/az_paragraphs/az_paragraphs_html/config/install/core.entity_view_display.paragraph.az_html.default.yml
  modules/custom/az_paragraphs/az_paragraphs_html/config/install/field.field.paragraph.az_html.field_az_full_html.yml
  modules/custom/az_paragraphs/az_paragraphs_html/config/install/field.storage.paragraph.field_az_full_html.yml
  modules/custom/az_paragraphs/az_paragraphs_html/config/install/paragraphs.paragraphs_type.az_html.yml
  modules/custom/az_paragraphs/tests/src/Functional/AZParagraphsTest.php
Labels: enhancement, hacktoberfest-accepted

#362 Add local-settings and Vim settings to .gitignore
  .gitignore
Labels: enhancement

#382 #381: Updated Drupal core to version 9.0.8 for SA-CORE-2020-012 (critical security vulnerability).
  composer.json
Labels: bug

#373 Add Cards Paragraph
  az_quickstart.info.yml
  modules/custom/az_card/az_card.info.yml
  modules/custom/az_card/config/install/image.style.az_card_image.yml
  modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php
  modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php
  modules/custom/az_card/templates/az-card.html.twig
  modules/custom/az_paragraphs/az_paragraphs.libraries.yml
  modules/custom/az_paragraphs/az_paragraphs_cards/az_paragraphs_cards.info.yml
  modules/custom/az_paragraphs/az_paragraphs_cards/config/install/core.entity_form_display.paragraph.az_cards.default.yml
  modules/custom/az_paragraphs/az_paragraphs_cards/config/install/core.entity_view_display.paragraph.az_cards.default.yml
  modules/custom/az_paragraphs/az_paragraphs_cards/config/install/field.field.paragraph.az_cards.field_az_cards.yml
  modules/custom/az_paragraphs/az_paragraphs_cards/config/install/field.storage.paragraph.field_az_cards.yml
  modules/custom/az_paragraphs/az_paragraphs_cards/config/install/paragraphs.paragraphs_type.az_cards.yml
  modules/custom/az_paragraphs/css/az_paragraphs_az_cards.css
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZCardsParagraphBehavior.php
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZDefaultParagraphsBehavior.php
Labels: enhancement

#392 #391: Updated Drupal core to version 9.0.9 (critical security update for SA-CORE-2020-013).
  composer.json
Labels: backport, bug
