Repository az-digital/az_quickstart, pull requests merged in 2020-12, with the labels that each got.

#394 Fixes #393: Replaced hard-coded references to main branch in GitHub actions config.
  .github/workflows/security.yml
Labels: 2.0.x, bug

#400 Update arizona-bootstrap v2.0.5
  composer.json
  themes/custom/az_barrio/includes/common.inc
Labels: task

#388 Fixes #386: Update Paragraph Preview Styles
  modules/custom/az_paragraphs/az_paragraphs.libraries.yml
  modules/custom/az_paragraphs/css/az_paragraphs_preview.css
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZDefaultParagraphsBehavior.php
Labels: backport, enhancement

#358 CKeditor changes for Standard Text Format
  az_quickstart.info.yml
  composer.json
  modules/custom/az_paragraphs/config/optional/editor.editor.az_standard.yml
  modules/custom/az_paragraphs/config/optional/filter.format.az_standard.yml
Labels: backport, blocker

#406 remove hirak/prestissimo
  .lando.yml
Labels: backport, bug

#410 Configuration Management/Config Distro Integration
  composer.json
  modules/custom/az_cas/az_cas.az_config_overrides.yml
  modules/custom/az_cas/config/quickstart/cas.settings.yml
  modules/custom/az_core/az_core.info.yml
  modules/custom/az_core/az_core.module
  modules/custom/az_core/az_core.services.yml
  modules/custom/az_core/src/AZConfigOverride.php
  modules/custom/az_core/src/Plugin/ConfigProvider/QuickstartConfigProvider.php
  modules/custom/az_core/src/QuickstartConfigInstaller.php
  modules/custom/az_core/tests/src/Functional/ConfigOverrideTest.php
  phpstan-contrib.neon
Labels: backport, enhancement

#395 #348: Update to Drupal 9.1.0.
  .probo.yaml
  composer.json
  modules/custom/az_cas/src/Form/AzCasSettingsForm.php
  modules/custom/az_cas/tests/src/Functional/AzCasAdminSettingsTest.php
  modules/custom/az_core/src/Controller/MonitoringPageController.php
  modules/custom/az_core/src/Form/QuickstartCoreSettingsForm.php
  modules/custom/az_core/tests/src/Functional/MonitoringPageTest.php
  themes/custom/az_barrio/tests/src/Functional/AzBarrioTest.php
  themes/custom/az_barrio/theme-settings.php
Labels: backport

#415 Closes #414 - Adds Coffee module
  az_quickstart.info.yml
  composer.json
  config/install/user.role.az_content_editor.yml
Labels: backport, enhancement
