Repository az-digital/az_quickstart, pull requests merged in 2020-10, with the labels that each got.

#334 Default Paragraph Behavior
  CONTRIBUTING.md
  config/install/user.role.az_content_editor.yml
  modules/custom/az_paragraphs/az_paragraphs.module
  modules/custom/az_paragraphs/az_paragraphs.services.yml
  modules/custom/az_paragraphs/az_paragraphs_text/config/install/paragraphs.paragraphs_type.az_text.yml
  modules/custom/az_paragraphs/src/AZParagraphCustomizations.php
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZDefaultParagraphsBehavior.php
  modules/custom/az_paragraphs/tests/src/Functional/AZParagraphsTest.php
Labels: documentation, enhancement

#347 Fixes #346: Changed visibility of $modules property on test classes to protected.
  modules/custom/az_demo/tests/src/Functional/AZDemoContentTest.php
  modules/custom/az_paragraphs/tests/src/Functional/AZParagraphsTest.php
Labels: task

#345 Closes #344: Update Drupal core to version 9.0.7 (bugfix release) and add akslay's core patch.
  composer.json
Labels: task

#354 Use env file instead of set-env
  .github/workflows/create-upload-release.yml
  .github/workflows/security.yml
Labels: hacktoberfest-accepted

#356 Update composer.json with minimum version numbers that are compatible with composer 2.0
  .probo.yaml
  composer.json
Labels: blocker, enhancement, hacktoberfest-accepted
