Repository az-digital/az_quickstart, pull requests merged in 2020-04, with the labels that each got.

#64 Add info on how to edit quickstart files within lando containers with…
  CONTRIBUTING.md
Labels: documentation

#71 introduce simpletest environment vars
  .ddev/docker-compose.override.yaml
  .lando.yml
Labels: enhancement

#148 Fixes #147: Updated Drupal core to version 8.8.5.
  composer.json
Labels: bug, task

#155 #154: Add Initial Permission Changes from Workshop
  config/install/user.role.az_content_admin.yml
  config/install/user.role.az_content_editor.yml
Labels: question

#53 Add az_cas module to install and override cas defaults specific to the University of Arizona.
  .lando.yml
  README.md
  az_quickstart.info.yml
  composer.json
  modules/custom/az_cas/README.md
  modules/custom/az_cas/az_cas.az_config_overrides.yml
  modules/custom/az_cas/az_cas.info.yml
  modules/custom/az_cas/az_cas.module
  modules/custom/az_cas/config/install/cas.settings.yml
  modules/custom/az_cas/tests/src/Functional/AzCasTest.php
Labels: enhancement

#78 #77: Added az_content_editor & az_content_admin roles.
  config/install/user.role.administrator.yml
  config/install/user.role.az_content_admin.yml
  config/install/user.role.az_content_editor.yml
Labels: enhancement

#149 Adding some basic instructions for phpunit testing.
  CONTRIBUTING.md
Labels: documentation

#69 Closes #68 by adding bullets below Readme's How to contribute section
  README.md
Labels: documentation

#76 Add default PR reviewers, remind to add project -- closes #75
  .github/CODEOWNERS
  .github/pull_request_template.md
Labels: task

#74 Change description of task issue type -- Closes #73
  .github/ISSUE_TEMPLATE/task.md
Labels: task

#168 Fixes #167 Add default configuration for main menu block
  config/install/block.block.az_barrio_main_menu.yml
Labels: bug

#173 Fixes #170 Provide appropriate value for Navbar width container configuration.
  themes/custom/az_barrio/config/install/az_barrio.settings.yml
Labels: bug

#180 Fixes #179 Update DS commit hash
  composer.json
Labels: bug

#80 Fix Missing Layout Builder Revision Elements
  composer.json
Labels: bug

#182 Fixes #171 Resolve Duplicate Drupal Messages
  themes/custom/az_barrio/config/install/az_barrio.settings.yml
  themes/custom/az_barrio/templates/page.html.twig
Labels: bug

#189 Fixes #183 Update CDN Link to Github-based CDN
  themes/custom/az_barrio/az_barrio.theme
Labels: enhancement
