Repository az-digital/az_quickstart, pull requests merged in 2021-03, with the labels that each got.

#561 Fixes #409, #439 Third Party Libraries and Add Chosen
  az_quickstart.info.yml
  composer.json
  config/install/chosen.settings.yml
Labels: backport, blocker, enhancement

#562 Closes #393: Use quickstart_branch script to require correct branch/version of Quickstart in GitHub actions security workflow.
  .github/workflows/security.yml
Labels: backport, bug

#543 #516 Removed all sanitized text from renderable arrays in favor of built in sanitization, and remove unused code, and mark inlined svg as experimental.
  themes/custom/az_barrio/az_barrio.info.yml
  themes/custom/az_barrio/az_barrio.theme
  themes/custom/az_barrio/config/install/az_barrio.settings.yml
  themes/custom/az_barrio/config/schema/az_barrio.schema.yml
  themes/custom/az_barrio/theme-settings.php
Labels: backport

#566 az-digital/arizona-bootsrap#223: Removing unnecessary .nav class from main menu template.
  themes/custom/az_barrio/templates/navigation/menu--main.html.twig
Labels: backport, bug

#602 Closes #601 - Add patch 2552541-43 to core/views
  composer.json
Labels: backport, bug

#600 Fixes #599: Fix broken Quickstart version indicator render array.
  modules/custom/az_core/az_core.module
Labels: backport, bug

#598 Closes #401: Fix blockquote styling
  az_quickstart.info.yml
  composer.json
  config/install/filter.format.basic_html.yml
  config/install/filter.format.full_html.yml
  config/install/filter.format.restricted_html.yml
  modules/custom/az_media/az_media.info.yml
  modules/custom/az_media/config/install/filter.format.az_standard.yml
  modules/custom/az_paragraphs/config/optional/editor.editor.az_standard.yml
Labels: backport, bug

#597 Closes #590: Add exclude node title to page content type
  az_quickstart.info.yml
  composer.json
  config/install/exclude_node_title.settings.yml
  config/install/user.role.anonymous.yml
  config/install/user.role.authenticated.yml
  config/install/user.role.az_content_editor.yml
Labels: backport, enhancement

#612 Kitten for Arizona Quickstart
  .github/workflows/review-site.yml
Labels: ci

#591 Closes #556 Creating custom flexible block (new and improved: fixing branching problems)
  az_quickstart.info.yml
  modules/custom/az_flexible_block/az_flexible_block.info.yml
  modules/custom/az_flexible_block/config/install/block_content.type.az_flexible_block.yml
  modules/custom/az_flexible_block/config/install/core.entity_form_display.block_content.az_flexible_block.default.yml
  modules/custom/az_flexible_block/config/install/core.entity_view_display.block_content.az_flexible_block.default.yml
  modules/custom/az_flexible_block/config/install/field.field.block_content.az_flexible_block.field_az_main_content.yml
  modules/custom/az_flexible_block/config/install/field.storage.block_content.field_az_main_content.yml
Labels: backport, task

#609 Fixes #541: Update config settings for embed content
  modules/custom/az_paragraphs/config/optional/embed.button.az_embed_content.yml
Labels: backport, contractor, enhancement

#621 Fixes #619: Update Page permissions
  config/install/user.role.az_content_admin.yml
  config/install/user.role.az_content_editor.yml
Labels: backport, task

#610 Adding views and displays for news teaser page (closes #553 #554 #555)
  modules/custom/az_core/config/install/core.entity_view_mode.node.az_marquee.yml
  modules/custom/az_core/config/install/core.entity_view_mode.node.az_medium_media_list.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_marquee.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_medium_media_list.yml
  modules/custom/az_news/config/install/views.view.az_news.yml
  themes/custom/az_barrio/config/optional/block.block.views_block__az_news_marquee.yml
  themes/custom/az_barrio/templates/views/views-view--az-news--marquee.html.twig
Labels: backport, task

#623 Fixes #407: AZ Person view contextual filter updates
  modules/custom/az_paragraphs/az_paragraphs_view/config/install/core.entity_form_display.paragraph.az_view_reference.default.yml
  modules/custom/az_paragraphs/az_paragraphs_view/config/install/core.entity_view_display.paragraph.az_view_reference.default.yml
  modules/custom/az_paragraphs/az_paragraphs_view/config/install/field.field.paragraph.az_view_reference.field_az_title.yml
  modules/custom/az_paragraphs/az_paragraphs_view/config/install/field.field.paragraph.az_view_reference.field_az_view_reference.yml
  modules/custom/az_person/config/install/views.view.az_person.yml
Labels: backport, task

#620 Fixes #520: Update Drupal core to 9.1.5
  composer.json
Labels: backport, bug

#605 Add Carousel Item content type
  az_quickstart.info.yml
  composer.json
  config/install/user.role.az_content_admin.yml
  config/install/user.role.az_content_editor.yml
  modules/custom/az_carousel/az_carousel.info.yml
  modules/custom/az_carousel/az_carousel.libraries.yml
  modules/custom/az_carousel/az_carousel.module
  modules/custom/az_carousel/config/install/block.block.views_block__az_carousel_front_carousel_block.yml
  modules/custom/az_carousel/config/install/core.base_field_override.node.az_carousel_item.promote.yml
  modules/custom/az_carousel/config/install/core.entity_form_display.node.az_carousel_item.default.yml
  modules/custom/az_carousel/config/install/core.entity_view_display.node.az_carousel_item.default.yml
  modules/custom/az_carousel/config/install/field.field.node.az_carousel_item.field_az_carousel_short_summary.yml
  modules/custom/az_carousel/config/install/field.field.node.az_carousel_item.field_az_link.yml
  modules/custom/az_carousel/config/install/field.field.node.az_carousel_item.field_az_media_image.yml
  modules/custom/az_carousel/config/install/field.storage.node.field_az_carousel_short_summary.yml
  modules/custom/az_carousel/config/install/node.type.az_carousel_item.yml
  modules/custom/az_carousel/config/install/slick.optionset.center_mode.yml
  modules/custom/az_carousel/config/install/views.view.az_carousel.yml
  modules/custom/az_carousel/config/optional/block.block.az_carousel_notification.yml
  modules/custom/az_carousel/config/quickstart/slick.settings.yml
  modules/custom/az_carousel/css/az_carousel.css
  modules/custom/az_carousel/src/Plugin/Block/AZCarouselNotice.php
  modules/custom/az_core/az_core.info.yml
  modules/custom/az_core/config/install/search.page.content_exclude_az_content.yml
  modules/custom/az_core/config/install/smart_title.settings.yml
  modules/custom/az_core/config/quickstart/search.page.node_search.yml
  modules/custom/az_core/config/quickstart/search.settings.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_carousel_item.yml
  modules/custom/az_media/config/install/core.entity_view_mode.media.az_carousel_item.yml
  modules/custom/az_media/config/install/image.style.az_carousel_item.yml
Labels: enhancement
