Repository az-digital/az_quickstart, pull requests merged in 2021-04, with the labels that each got.

#611 Fixes #139 Create Sidebar Menu Block
  az_quickstart.info.yml
  composer.json
  themes/custom/az_barrio/config/optional/block.block.az_barrio_sidebar_menu.yml
  themes/custom/az_barrio/templates/navigation/menu--main.html.twig
  themes/custom/az_barrio/templates/navigation/menu--sidebar.html.twig
Labels: backport, contractor, enhancement

#634 Fixes #390, Fixes #427, Fixes #538, Fixes #613 Card Widget Updates
  modules/custom/az_card/az_card.services.yml
  modules/custom/az_card/css/az-card-widget.css
  modules/custom/az_card/src/AZCardImageHelper.php
  modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php
  modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php
Labels: backport, bug, enhancement

#633 Setting permissions for flexible block
  az_quickstart.info.yml
  composer.json
  config/install/user.role.az_content_admin.yml
  config/install/user.role.az_content_editor.yml
Labels: backport, task

#637 Added bootstrap responsive embed classes to default remote video display
  modules/custom/az_media/az_media.info.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_remote_video.default.yml
Labels: backport, bug

#643 #632: Change composition of child classes needing additional dependencies for better maintainability.
  modules/custom/az_accordion/src/Plugin/Field/FieldFormatter/AZAccordionDefaultFormatter.php
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZDefaultParagraphsBehavior.php
Labels: backport, enhancement

#636 Fixes #537 Relative paths in Cards link field
  modules/custom/az_card/config/schema/az_card.schema.yml
  modules/custom/az_card/css/az-card-widget.css
  modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php
  modules/custom/az_card/src/Plugin/Field/FieldType/AZCardItem.php
  modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php
Labels: backport, bug, contractor, enhancement

#653 Fixes #428 Config Distro Import Ignore Bug
  composer.json
Labels: bug

#655 Closes #615 - Fix offcanvas menu scroll
  themes/custom/az_barrio/css/style.css
Labels: backport, bug

#650 Fixes #545 Create Photo Gallery Paragraph Type
  az_quickstart.info.yml
  modules/custom/az_media/config/install/core.entity_form_display.media.az_image.default.yml
  modules/custom/az_media/config/install/core.entity_form_display.media.az_image.media_library.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_background.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_card_image.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_carousel_item.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_large.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_medium.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_natural_size.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_thumbnail.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_image.default.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_image.media_library.yml
  modules/custom/az_media/config/install/field.field.media.az_image.field_az_caption.yml
  modules/custom/az_media/config/install/field.storage.media.field_az_caption.yml
  modules/custom/az_paragraphs/az_paragraphs.libraries.yml
  modules/custom/az_paragraphs/az_paragraphs_photo_gallery/az_paragraphs_photo_gallery.info.yml
  modules/custom/az_paragraphs/az_paragraphs_photo_gallery/config/install/core.entity_form_display.paragraph.az_photo_gallery.default.yml
  modules/custom/az_paragraphs/az_paragraphs_photo_gallery/config/install/core.entity_view_display.paragraph.az_photo_gallery.default.yml
  modules/custom/az_paragraphs/az_paragraphs_photo_gallery/config/install/field.field.paragraph.az_photo_gallery.field_az_photos.yml
  modules/custom/az_paragraphs/az_paragraphs_photo_gallery/config/install/field.storage.paragraph.field_az_photos.yml
  modules/custom/az_paragraphs/az_paragraphs_photo_gallery/config/install/paragraphs.paragraphs_type.az_photo_gallery.yml
  modules/custom/az_paragraphs/az_paragraphs_photo_gallery/templates/paragraph--az-photo-gallery.html.twig
  modules/custom/az_paragraphs/css/az_paragraphs_az_photo_gallery.css
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZPhotoGalleryParagraphBehavior.php
Labels: backport, contractor, enhancement

#645 #589: Include a blocks tab within content admin page options
  config/install/user.role.az_content_editor.yml
  config/install/views.view.block_content.yml
  modules/custom/az_flexible_block/az_flexible_block.links.action.yml
  modules/custom/az_flexible_block/src/Plugin/Menu/LocalAction/AzFlexibleBlockAddLocalAction.php
Labels: backport, enhancement

#641 Issue/544 add video support to text with media
  modules/custom/az_paragraphs/az_paragraphs.services.yml
  modules/custom/az_paragraphs/az_paragraphs_text_media/az_paragraphs_text_media.libraries.yml
  modules/custom/az_paragraphs/az_paragraphs_text_media/config/install/field.field.paragraph.az_text_media.field_az_media.yml
  modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_youtube.es6.js
  modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_youtube.js
  modules/custom/az_paragraphs/az_paragraphs_text_media/templates/media--az-remote-video--az-background.html.twig
  modules/custom/az_paragraphs/az_paragraphs_text_media/templates/paragraph--az-text-media--default.html.twig
  modules/custom/az_paragraphs/css/az_paragraphs_az_text_media.css
  modules/custom/az_paragraphs/src/AZVideoEmbedHelper.php
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithMediaParagraphBehavior.php
  modules/custom/az_paragraphs/tests/src/Unit/AZVideoEmbedHelperTest.php
Labels: backport

#668 Closes #665, Closes #667: Update Drupal core to 9.1.7 for SA-CORE-2021-002 (critical security update).
  composer.json
Labels: backport, bug

#635 Run tests faster! (#507)
  .ddev/commands/web/phpunit-fastest
  .lando.yml
  .probo.yaml
Labels: backport, ci, enhancement

#672 Closes #671: Add pheremone/phpcs-security-audit fork as composer repository.
  composer.json
Labels: backport, bug, ci

#694 Resolve ServiceNotFoundException when logging out
  composer.json
Labels: backport, bug

#673 Closes #670: April 2021 Drupal contrib maintenance updates.
  composer.json
Labels: backport, bug, task
