Repository az-digital/az_quickstart, pull requests merged in 2021-06, with the labels that each got.

#752 Closes #135: Migration for D7 event content type.
  modules/custom/az_migration/migrations/migrate_plus.migration.az_event_categories.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_node_event.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_contact.yml
Labels: backport, migration

#815 Closes #813: Set 'When' field to not show extra empty widget on Event form display
  modules/custom/az_event/config/install/core.entity_form_display.node.az_event.default.yml
Labels: backport, enhancement

#816 Closes #745: Polish display for News content type nodes
  modules/custom/az_news/config/install/core.entity_form_display.node.az_news.default.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.default.yml
Labels: backport, enhancement

#769 Closes #772: Migration for D7 plain text paragraph type.
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_plain_text.yml
  modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsBehavior.php
  modules/custom/az_migration/src/Plugin/migrate/source/AZParagraphsItem.php
Labels: backport, migration

#812 Closes #119: Add person demo content.
  modules/custom/az_demo/az_demo.info.yml
  modules/custom/az_demo/data/az_demo_image_file.json
  modules/custom/az_demo/data/az_demo_menu_links.json
  modules/custom/az_demo/data/az_demo_person_categories.json
  modules/custom/az_demo/data/az_demo_person_categories_secondary.json
  modules/custom/az_demo/data/az_demo_person_node.json
  modules/custom/az_demo/images/placeduck01.jpg
  modules/custom/az_demo/images/placeduck02.jpg
  modules/custom/az_demo/images/placeduck03.jpg
  modules/custom/az_demo/images/placeduck04.jpg
  modules/custom/az_demo/images/placeduck05.jpg
  modules/custom/az_demo/images/placeduck06.jpg
  modules/custom/az_demo/images/placeduck07.jpg
  modules/custom/az_demo/images/placeduck08.jpg
  modules/custom/az_demo/images/placeduck09.jpg
  modules/custom/az_demo/images/placeduck10.jpg
  modules/custom/az_demo/images/placeduck11.jpg
  modules/custom/az_demo/images/wilbur-wildcat.jpg
  modules/custom/az_demo/images/wilma-wildcat.jpg
  modules/custom/az_demo/migrations/az_demo_image_file.yml
  modules/custom/az_demo/migrations/az_demo_person_categories.yml
  modules/custom/az_demo/migrations/az_demo_person_categories_secondary.yml
  modules/custom/az_demo/migrations/az_demo_person_node.yml
Labels: backport, enhancement

#715 Fixes #72 Add Chromedriver to Tooling Stack
  .ddev/docker-compose.override.yaml
  .lando.yml
  .probo.yaml
  modules/custom/az_paragraphs/tests/src/FunctionalJavascript/AZParagraphsJavascriptTest.php
Labels: 2.0.x, backport, ci, enhancement

#759 Closes #773: Migration for D7 headed text paragraph type.
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_headed_text.yml
Labels: backport, migration

#825 Send notification to upstream on release
  .github/workflows/create-release.yml
Labels: backport, ci

#802 Closes #774: Migration for D7 photo gallery paragraph type.
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_gallery.yml
  modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsBehavior.php
Labels: backport, migration

#835 Closes #787: Migration Paragraph Single Card to AZ Cards
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_single_card.yml
  modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsBehavior.php
Labels: backport, migration

#838 Closes #788: Migration for D7 well paragraph type (to cards).
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_well.yml
Labels: backport, migration

#848 Closes #847: Updated ctools module to 8.x-3.7 for SA-CONTRIB-2021-015.
  composer.json
Labels: backport, bug

#833 Closes #780: Migration for D7 callout paragraph type (to text).
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_callout.yml
  modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsBehavior.php
  modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsCalloutFieldMerge.php
Labels: backport, migration

#828 Closes #782: Migrate D7 full width background wrapper paragraph type (to text with background).
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_full_width_bg_wrapper.yml
  modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsBehavior.php
Labels: backport, migration

#855 Closes #779: Migration for D7 column image paragraph type (to AZ Text).
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_column_image.yml
  modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsColumnImageFieldMerge.php
Labels: backport, migration

#856 Closes #689: Fixing most theme problems with the grid.
  composer.json
  themes/custom/az_barrio/az_barrio.info.yml
  themes/custom/az_barrio/config/install/az_barrio.settings.yml
  themes/custom/az_barrio/config/schema/az_barrio.schema.yml
  themes/custom/az_barrio/templates/layout/html.html.twig
  themes/custom/az_barrio/templates/layout/maintenance-page.html.twig
  themes/custom/az_barrio/templates/layout/page.html.twig
Labels: bug

#841 Closes #736: Adding patch to fix claro dialog with ckeditor_bs_grid plugin
  composer.json
Labels: backport, bug, high priority

#861 Fixes #806, Fixes #723 Update Events Views to use Delta Splitting, Change 'Now' to 'Today'
  modules/custom/az_event/az_event.module
  modules/custom/az_event/config/install/views.view.az_events.yml
Labels: bug, enhancement, high priority

#872 Closes #871: Adding navbar-offcanvas class to array, not resetting the array.
  themes/custom/az_barrio/az_barrio.theme
  themes/custom/az_barrio/templates/layout/page.html.twig
Labels: backport, bug

#869 Closes #864, Relates az-digital/arizona-bootstrap#318: Active state of sidebar nav.
  themes/custom/az_barrio/css/style.css
  themes/custom/az_barrio/templates/navigation/menu--sidebar.html.twig
Labels: backport, bug

#865 Closes #852, Closes #854, Closes #863: Misc Arizona Barrio improvements/fixes.
  themes/custom/az_barrio/az_barrio.theme
  themes/custom/az_barrio/config/optional/block.block.az_barrio_messages.yml
  themes/custom/az_barrio/config/schema/az_barrio.schema.yml
  themes/custom/az_barrio/theme-settings.php
Labels: backport, bug, enhancement

#857 Closes #679: Update Drupal core to 9.2.0.
  .eslintrc.json
  az_quickstart.install
  composer.json
  package.json
Labels: backport, dependencies

#860 Closes #785: Migration or D7 full-width media row paragraph type (to text on media).
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_full_width_media_row.yml
  modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsBehavior.php
  modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsFWMediaRowFieldMerge.php
  modules/custom/az_migration/src/Plugin/migrate/source/AZParagraphsItem.php
Labels: backport, migration

#851 Closes #783: Migration for D7 views paragraph type.
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_chucks_view.yml
  modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsChunksViewDisplayMapping.php
Labels: backport, migration

#887 Closes #886: Force install of field_az_metatag field storage to resolve config dependencies preventing config distro import.
  modules/custom/az_seo/az_seo.install
Labels: backport, bug, high priority

#891 Fixes #873 Add default timezone settings.
  config/install/system.date.yml
Labels: backport, enhancement

#884 Closes #881: Disable az_demo by default. Enable in Probo & Kitten.
  .github/workflows/review-site.yml
  .probo.yaml
  az_quickstart.info.yml
Labels: backport, enhancement
