Repository az-digital/az_quickstart, pull requests merged in 2021-05, with the labels that each got.

#681 Add view and displays for page by category (closes #573)
  modules/custom/az_core/config/quickstart/chosen.settings.yml
  modules/custom/az_flexible_page/az_flexible_page.info.yml
  modules/custom/az_flexible_page/az_flexible_page.install
  modules/custom/az_flexible_page/config/install/core.entity_form_display.node.az_flexible_page.default.yml
  modules/custom/az_flexible_page/config/install/core.entity_view_display.node.az_flexible_page.az_card.yml
  modules/custom/az_flexible_page/config/install/core.entity_view_display.node.az_flexible_page.az_row.yml
  modules/custom/az_flexible_page/config/install/core.entity_view_display.node.az_flexible_page.teaser.yml
  modules/custom/az_flexible_page/config/install/field.field.node.az_flexible_page.field_az_media_image.yml
  modules/custom/az_flexible_page/config/install/field.field.node.az_flexible_page.field_az_page_category.yml
  modules/custom/az_flexible_page/config/install/field.field.node.az_flexible_page.field_az_summary.yml
  modules/custom/az_flexible_page/config/install/field.storage.node.field_az_page_category.yml
  modules/custom/az_flexible_page/config/install/taxonomy.vocabulary.az_page_categories.yml
  modules/custom/az_flexible_page/config/install/views.view.az_page_by_category.yml
Labels: backport, enhancement

#708 Closes #705, Closes #700: Added static favicon files as scaffold assets.
  assets/android-chrome-192x192.png
  assets/android-chrome-512x512.png
  assets/apple-touch-icon.png
  assets/browserconfig.xml
  assets/favicon-16x16.png
  assets/favicon-32x32.png
  assets/favicon.ico
  assets/mstile-144x144.png
  assets/mstile-150x150.png
  assets/mstile-310x150.png
  assets/mstile-310x310.png
  assets/mstile-70x70.png
  assets/safari-pinned-tab.svg
  assets/site.webmanifest
  composer.json
Labels: backport, bug, enhancement

#713 Fixes #712: Update Drupal core to 9.1.8 (bugfix release).
  composer.json
Labels: backport, bug, task

#728 Closes #716 — enabling the az_mail module breaking drush
  modules/custom/az_mail/src/Commands/AZMailCommands.php
Labels: backport, bug

#720 Fixes #719: Don't use magic credentials.sh filename in ProboCI config.
  .probo.yaml
Labels: backport, bug, ci

#732 Fixes #731: Update ctools to 8.x-3.6 for SA-CONTRIB-2021-009 (moderately critical security update).
  composer.json
Labels: backport, bug

#669 Fixes #127, Fixes #662, Fixes #663, Fixes #701: Added migration testing ProboCI workflow and D7 migrations for Users, Person nodes, Files, and Media.
  .probo.yaml
  composer.json
  modules/custom/az_migration/README.md
  modules/custom/az_migration/az_migration.info.yml
  modules/custom/az_migration/config/install/az_migration.settings.yml
  modules/custom/az_migration/config/install/migrate_plus.migration_group.az_migration.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_cas_user.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_event_categories.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_files.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_media.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_node_person.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_person_categories.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_person_categories_secondary.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_user.yml
  modules/custom/az_migration/src/Plugin/migrate/source/AZFileHandle.php
Labels: backport, enhancement

#717 Increase dependabot frequency and add reviewers to dependabot PRs.
  .github/dependabot.yml
Labels: enhancement

#763 Kitten D9 github action fixes
  .github/workflows/review-site.yml
Labels: backport, bug, ci

#606 Configure Content Moderation
  config/install/user.role.az_content_admin.yml
  config/install/user.role.az_content_editor.yml
  config/optional/workflows.workflow.editorial.yml
Labels: backport, contractor, enhancement

#768 Paragraph Admin module to see paragraph content
  composer.json
Labels: backport, enhancement, migration

#792 Fixes #638: Added patch for Image Widget Crop module bug affecting media library UX.
  composer.json
Labels: backport, bug

#664 Closes #572 - Add reorder carousel items view display
  az_quickstart.info.yml
  config/install/user.role.az_content_admin.yml
  config/install/user.role.az_content_editor.yml
  modules/custom/az_carousel/config/install/views.view.az_carousel.yml
  modules/custom/az_carousel/src/Plugin/Block/AZCarouselNotice.php
Labels: contractor, enhancement

#804 Fixes #803: Updated Drupal core to 9.1.9 for SA-CORE-2021-003 / PSA-2021-05-25 (moderately critical security update).
  composer.json
Labels: backport, bug

#755 Feature/734 - Carousel Migration
  modules/custom/az_migration/README.md
  modules/custom/az_migration/az_migration.info.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_node_carousel.yml
Labels: backport, migration

#796 Fixes #738: Add #maxlength to title field form element in Accordion and Card FieldWidgets.
  modules/custom/az_accordion/src/Plugin/Field/FieldWidget/AZAccordionWidget.php
  modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php
Labels: backport, bug

#758 Add styling to event category taxonomy terms (Closes #727)
  modules/custom/az_event/az_event.module
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.default.yml
Labels: backport, enhancement, task

#799 Allow id, name classes to headings, plus additional button classes in ckeditor (Closes #762)
  modules/custom/az_media/config/install/filter.format.az_standard.yml
Labels: backport, bug

#793 Fixes #691: Added spacing (padding) setting to text with background paragraph type.
  modules/custom/az_paragraphs/az_paragraphs_text_background/az_paragraphs_text_background.install
  modules/custom/az_paragraphs/az_paragraphs_text_background/templates/paragraph--az-text-background--default.html.twig
  modules/custom/az_paragraphs/css/az_paragraphs_az_text_background.css
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithBackgroundParagraphBehavior.php
Labels: backport, enhancement

#801 Wake env before doing site install
  .github/workflows/review-site.yml
Labels: backport, bug, ci

#767 Closes #766: Limit fastest to 10 parallel processes on ProboCI.
  .probo.yaml
  composer.json
Labels: backport, bug, ci

#797 Allow empty end date (Closes #725)
  composer.json
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_card.yml
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_row.yml
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.default.yml
  modules/custom/az_event/config/install/field.field.node.az_event.field_az_event_date.yml
Labels: backport

#809 Fixes #808: Corrected typo in migrate_plus.migration.az_node_person.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_node_person.yml
Labels: backport, bug, migration
