Repository az-digital/az_quickstart, pull requests merged in 2021-01, with the labels that each got.

#404 Issue/333 add proxima nova to barrio
  themes/custom/az_barrio/az_barrio.libraries.yml
  themes/custom/az_barrio/az_barrio.theme
  themes/custom/az_barrio/config/install/az_barrio.settings.yml
  themes/custom/az_barrio/config/schema/az_barrio.schema.yml
  themes/custom/az_barrio/tests/src/Functional/AzBarrioTest.php
  themes/custom/az_barrio/theme-settings.php
Labels: backport, enhancement

#426 Remove all references to Milo font.
  themes/custom/az_barrio/css/style.css
Labels: bug, good first issue

#431 Move search block to red bar and hide it on mobile
  themes/custom/az_barrio/config/install/az_barrio.settings.yml
  themes/custom/az_barrio/config/optional/block.block.az_barrio_search.yml
  themes/custom/az_barrio/templates/page.html.twig
Labels: backport, enhancement

#443 initial news content type for issue/128
  az_quickstart.info.yml
  composer.json
  modules/custom/az_news/az_news.info.yml
  modules/custom/az_news/config/install/core.base_field_override.node.az_news.promote.yml
  modules/custom/az_news/config/install/core.entity_form_display.node.az_news.default.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.default.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.teaser.yml
  modules/custom/az_news/config/install/field.field.node.az_news.field_az_article_body.yml
  modules/custom/az_news/config/install/field.field.node.az_news.field_az_attachments.yml
  modules/custom/az_news/config/install/field.field.node.az_news.field_az_byline.yml
  modules/custom/az_news/config/install/field.field.node.az_news.field_az_caption.yml
  modules/custom/az_news/config/install/field.field.node.az_news.field_az_expiration_date.yml
  modules/custom/az_news/config/install/field.field.node.az_news.field_az_extra_body_content.yml
  modules/custom/az_news/config/install/field.field.node.az_news.field_az_media_image.yml
  modules/custom/az_news/config/install/field.field.node.az_news.field_az_news_tags.yml
  modules/custom/az_news/config/install/field.field.node.az_news.field_az_published.yml
  modules/custom/az_news/config/install/field.field.node.az_news.field_az_short_title.yml
  modules/custom/az_news/config/install/field.field.node.az_news.field_az_subheading.yml
  modules/custom/az_news/config/install/field.field.node.az_news.field_az_summary.yml
  modules/custom/az_news/config/install/field.storage.node.field_az_article_body.yml
  modules/custom/az_news/config/install/field.storage.node.field_az_attachments.yml
  modules/custom/az_news/config/install/field.storage.node.field_az_byline.yml
  modules/custom/az_news/config/install/field.storage.node.field_az_caption.yml
  modules/custom/az_news/config/install/field.storage.node.field_az_expiration_date.yml
  modules/custom/az_news/config/install/field.storage.node.field_az_extra_body_content.yml
  modules/custom/az_news/config/install/field.storage.node.field_az_news_tags.yml
  modules/custom/az_news/config/install/field.storage.node.field_az_published.yml
  modules/custom/az_news/config/install/field.storage.node.field_az_short_title.yml
  modules/custom/az_news/config/install/field.storage.node.field_az_subheading.yml
  modules/custom/az_news/config/install/field.storage.node.field_az_summary.yml
  modules/custom/az_news/config/install/node.type.az_news.yml
  modules/custom/az_news/config/install/smart_title.settings.yml
  modules/custom/az_news/config/install/taxonomy.vocabulary.az_news_tags.yml
  themes/custom/az_barrio/config/optional/block.block.az_barrio_page_title.yml
Labels: backport, enhancement

#418 290: text with background.
  README.md
  az_quickstart.info.yml
  modules/custom/az_paragraphs/az_paragraphs.libraries.yml
  modules/custom/az_paragraphs/az_paragraphs_text_background/az_paragraphs_text_background.info.yml
  modules/custom/az_paragraphs/az_paragraphs_text_background/az_paragraphs_text_background.module
  modules/custom/az_paragraphs/az_paragraphs_text_background/config/install/core.entity_form_display.paragraph.az_text_background.default.yml
  modules/custom/az_paragraphs/az_paragraphs_text_background/config/install/core.entity_view_display.paragraph.az_text_background.default.yml
  modules/custom/az_paragraphs/az_paragraphs_text_background/config/install/field.field.paragraph.az_text_background.field_az_text_area.yml
  modules/custom/az_paragraphs/az_paragraphs_text_background/config/install/paragraphs.paragraphs_type.az_text_background.yml
  modules/custom/az_paragraphs/css/az_paragraphs_az_text_background.css
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithBackgroundParagraphBehavior.php
  themes/custom/az_barrio/templates/paragraph/paragraph--az-text-background--default.html.twig
Labels: enhancement

#434 Create Release Action
  .github/workflows/create-upload-release.yml
Labels: backport

#451 Add .editorconfig from drupal core - closes #449
  .editorconfig
Labels: backport, enhancement

#454 Unset bootstrap_barrio site-footer css
  themes/custom/az_barrio/az_barrio.theme
Labels: backport, bug, good first issue

#458 Fix name for "Create Release" action
  .github/workflows/create-release.yml
Labels: backport, enhancement

#459 Fixes #411: Add cropping module to Install Profile
  composer.json
  modules/custom/az_card/az_card.info.yml
  modules/custom/az_media/az_media.info.yml
  modules/custom/az_media/config/install/core.entity_form_display.media.az_image.default.yml
  modules/custom/az_media/config/install/core.entity_form_display.media.az_image.media_library.yml
  modules/custom/az_media/config/install/crop.type.az_card_image.yml
  modules/custom/az_media/config/install/image.style.az_card_image.yml
  modules/custom/az_media/config/install/media.type.az_image.yml
Labels: backport, enhancement

#435 Issue/424-251 Add Sidebar block and add missing classes.
  themes/custom/az_barrio/az_barrio.theme
  themes/custom/az_barrio/config/optional/block.block.az_barrio_sidebar_menu.yml
  themes/custom/az_barrio/templates/navigation/menu--main--az-barrio-sidebar-menu.html.twig
Labels: backport, enhancement

#452 #133 Event Content Type
  az_quickstart.info.yml
  composer.json
  config/install/user.role.az_content_admin.yml
  config/install/user.role.az_content_editor.yml
  modules/custom/az_event/az_event.info.yml
  modules/custom/az_event/az_event.module
  modules/custom/az_event/config/install/core.base_field_override.node.az_event.promote.yml
  modules/custom/az_event/config/install/core.date_format.az_event_day.yml
  modules/custom/az_event/config/install/core.date_format.az_event_month.yml
  modules/custom/az_event/config/install/core.entity_form_display.node.az_event.default.yml
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_row.yml
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.default.yml
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.teaser.yml
  modules/custom/az_event/config/install/field.field.node.az_event.field_az_attachments.yml
  modules/custom/az_event/config/install/field.field.node.az_event.field_az_body.yml
  modules/custom/az_event/config/install/field.field.node.az_event.field_az_date.yml
  modules/custom/az_event/config/install/field.field.node.az_event.field_az_event_category.yml
  modules/custom/az_event/config/install/field.field.node.az_event.field_az_link.yml
  modules/custom/az_event/config/install/field.field.node.az_event.field_az_location.yml
  modules/custom/az_event/config/install/field.field.node.az_event.field_az_photos.yml
  modules/custom/az_event/config/install/field.field.node.az_event.field_az_summary.yml
  modules/custom/az_event/config/install/field.field.node.az_event.field_az_summary_short.yml
  modules/custom/az_event/config/install/field.storage.node.field_az_body.yml
  modules/custom/az_event/config/install/field.storage.node.field_az_date.yml
  modules/custom/az_event/config/install/field.storage.node.field_az_event_category.yml
  modules/custom/az_event/config/install/field.storage.node.field_az_link.yml
  modules/custom/az_event/config/install/field.storage.node.field_az_location.yml
  modules/custom/az_event/config/install/field.storage.node.field_az_photos.yml
  modules/custom/az_event/config/install/field.storage.node.field_az_summary_short.yml
  modules/custom/az_event/config/install/node.type.az_event.yml
  modules/custom/az_event/config/install/pathauto.pattern.az_event_url_pattern.yml
  modules/custom/az_event/config/install/taxonomy.vocabulary.az_event_categories.yml
  modules/custom/az_event/config/install/views.view.az_events.yml
  modules/custom/az_event/templates/field--node--az-event.html.twig
  modules/custom/az_media/config/install/core.entity_form_display.media.az_image.default.yml
  modules/custom/az_media/config/install/core.entity_form_display.media.az_image.media_library.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_large.yml
  modules/custom/az_media/config/install/core.entity_view_mode.media.az_large.yml
  modules/custom/az_media/config/install/crop.type.az_large.yml
  modules/custom/az_media/config/install/image.style.az_large.yml
  modules/custom/az_news/config/install/smart_title.settings.yml
  themes/custom/az_barrio/config/optional/block.block.az_barrio_page_title.yml
Labels: backport, enhancement

#464 Issue/187 theme use svg logos
  composer.json
  themes/custom/az_barrio/az_barrio.theme
  themes/custom/az_barrio/config/install/az_barrio.settings.yml
  themes/custom/az_barrio/config/schema/az_barrio.schema.yml
  themes/custom/az_barrio/css/style.css
  themes/custom/az_barrio/footer_logo.png
  themes/custom/az_barrio/images/logo.png
  themes/custom/az_barrio/theme-settings.php
Labels: backport, bug, enhancement

#467 MVP Text on Media Paragraph Type
  az_quickstart.info.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_background.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_remote_video.az_background.yml
  modules/custom/az_media/config/install/core.entity_view_mode.media.az_background.yml
  modules/custom/az_paragraphs/az_paragraphs.libraries.yml
  modules/custom/az_paragraphs/az_paragraphs_text_media/az_paragraphs_text_media.info.yml
  modules/custom/az_paragraphs/az_paragraphs_text_media/az_paragraphs_text_media.module
  modules/custom/az_paragraphs/az_paragraphs_text_media/config/install/core.entity_form_display.paragraph.az_text_media.default.yml
  modules/custom/az_paragraphs/az_paragraphs_text_media/config/install/core.entity_view_display.paragraph.az_text_media.default.yml
  modules/custom/az_paragraphs/az_paragraphs_text_media/config/install/field.field.paragraph.az_text_media.field_az_media.yml
  modules/custom/az_paragraphs/az_paragraphs_text_media/config/install/field.field.paragraph.az_text_media.field_az_text_area.yml
  modules/custom/az_paragraphs/az_paragraphs_text_media/config/install/field.field.paragraph.az_text_media.field_az_title.yml
  modules/custom/az_paragraphs/az_paragraphs_text_media/config/install/field.storage.paragraph.field_az_media.yml
  modules/custom/az_paragraphs/az_paragraphs_text_media/config/install/field.storage.paragraph.field_az_title.yml
  modules/custom/az_paragraphs/az_paragraphs_text_media/config/install/paragraphs.paragraphs_type.az_text_media.yml
  modules/custom/az_paragraphs/css/az_paragraphs_az_text_media.css
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithMediaParagraphBehavior.php
  themes/custom/az_barrio/templates/paragraph/paragraph--az-text-media--default.html.twig
Labels: backport, enhancement
