Repository az-digital/az_quickstart, pull requests merged in 2021-02, with the labels that each got.

#495 Fixes #494 Fix Event Pseudo Fields
  modules/custom/az_event/az_event.module
Labels: 2.0.x, backport, bug

#489 #469: Fix Github PR template to be more clear
  .github/pull_request_template.md
Labels: backport, documentation

#488 Make composer sort packages alphabetically.
  composer.json
Labels: backport, enhancement

#493 Fixes #490 Makes plain text fields formatted text with plain text
  modules/custom/az_core/config/install/field.storage.node.field_az_caption.yml
  modules/custom/az_core/config/install/field.storage.node.field_az_subheading.yml
  modules/custom/az_core/config/install/field.storage.node.field_az_summary.yml
  modules/custom/az_event/config/install/core.entity_form_display.node.az_event.default.yml
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_row.yml
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.default.yml
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.teaser.yml
  modules/custom/az_event/config/install/field.field.node.az_event.field_az_subheading.yml
  modules/custom/az_event/config/install/field.field.node.az_event.field_az_summary.yml
  modules/custom/az_news/config/install/core.entity_form_display.node.az_news.default.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_media_list.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.default.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.teaser.yml
  modules/custom/az_news/config/install/field.field.node.az_news.field_az_caption.yml
  modules/custom/az_news/config/install/field.field.node.az_news.field_az_subheading.yml
  modules/custom/az_news/config/install/field.field.node.az_news.field_az_summary.yml
Labels: 2.0.x, backport, enhancement

#503 Add patch for menu editing experience
  composer.json
Labels: backport, bug

#508 #491: Remove paste from word ckeditor option
  modules/custom/az_paragraphs/config/optional/editor.editor.az_standard.yml
Labels: backport, bug

#505 #504: Replaced sensiolabs/security-checker script with symfonycorp/security-checker-action.
  .github/workflows/security.yml
Labels: backport, bug

#506 Configure git before creating PR
  .github/workflows/arizona-bootstrap-release.yml
Labels: backport, bug

#465 Add az_mail module
  composer.json
  modules/custom/az_mail/az_mail.info.yml
  modules/custom/az_mail/az_mail.module
  modules/custom/az_mail/config/quickstart/smtp.settings.yml
  modules/custom/az_mail/config/schema/az_mail.schema.yml
  modules/custom/az_mail/drush.services.yml
  modules/custom/az_mail/src/commands/AZMailCommands.php
Labels: backport, enhancement

#492 Issue/473 Fix logo styling and update logo path to use relative url.
  themes/custom/az_barrio/az_barrio.info.yml
  themes/custom/az_barrio/az_barrio.theme
  themes/custom/az_barrio/css/style.css
  themes/custom/az_barrio/theme-settings.php
Labels: backport, bug, enhancement

#510 Bug/365 Fix how Jquery is loaded with HTML Paragraph
  modules/custom/az_paragraphs/az_paragraphs.libraries.yml
  modules/custom/az_paragraphs/az_paragraphs_html/config/install/paragraphs.paragraphs_type.az_html.yml
Labels: backport, bug

#440 Apply patch for restricted Claro editing area
  composer.json
Labels: backport, bug

#519 Resurface edit all/drag and drop functionality for paragraphs
  modules/custom/az_paragraphs/az_paragraphs.module
Labels: backport, enhancement

#368 #338: Add Quickstart 2.0 indicator to toolbar.
  modules/custom/az_core/az_core.module
Labels: backport, enhancement

#523 Closes #522: Configure composer minimum-stability to fix Dependabot.
  composer.json
Labels: backport, bug

#527 Closes #463: Moved paragraph templates to modules.
  modules/custom/az_paragraphs/az_paragraphs.module
  modules/custom/az_paragraphs/az_paragraphs_text_background/templates/paragraph--az-text-background--default.html.twig
  modules/custom/az_paragraphs/az_paragraphs_text_media/templates/paragraph--az-text-media--default.html.twig
Labels: backport, bug

#525 Closes #466: Added lando/DDEV tooling for PHPCBF and fixed various PHPCS issues.
  .ddev/commands/web/phpcbf
  .gitattributes
  .gitignore
  .lando.yml
  modules/custom/az_mail/az_mail.module
  modules/custom/az_mail/src/commands/AZMailCommands.php
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithMediaParagraphBehavior.php
  themes/custom/az_barrio/theme-settings.php
Labels: backport, bug, enhancement

#526 Closes #524: Updated composer.json to use specific version numbers for all Drupal contrib dependencies.
  composer.json
Labels: backport, bug

#521 #350: Updated PHP versions to 7.4. Added PHPCompatibility coding standard to PHPCS config.
  .ddev/config.quickstart.yaml
  .github/workflows/create-release.yml
  .github/workflows/security.yml
  .lando.yml
  .probo.yaml
  composer.json
  modules/custom/az_core/az_core.module
  phpcs.xml.dist
Labels: backport, enhancement

#533 Closes #532: Removed extra instance of footer_sub region in AZ Barrio's page template.
  themes/custom/az_barrio/templates/page.html.twig
Labels: backport, bug

#531 Closes #530: Fixed Arizona Bootstrap JS library path.
  themes/custom/az_barrio/az_barrio.libraries.yml
Labels: backport, bug
