Repository az-digital/az_quickstart, pull requests merged in 2021-08, with the labels that each got.

#969 #964: Fix broken drush site:install command (again).
  .github/workflows/review-site.yml
Labels: backport, bug, ci

#957 Closes #956: Make display of fields conditional in full az-person template.
  themes/custom/az_barrio/templates/content/node--az-person--full.html.twig
Labels: bug, backport

#972 Closes #971: Mark RELEASES.md as draft
  RELEASES.md
Labels: documentation, backport

#974 Closes #970: Update core/contrib update policies for Quickstart releases
  RELEASES.md
Labels: documentation, backport

#977 Closes #976: Update Drupal core to 9.2.4 for SA-CORE-2021-005 (moderately critical security update).
  composer.json
Labels: bug, backport, dependencies

#978 Fixes column sizes for calendar view on small screens
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_row.yml
Labels: bug, backport

#980 Fixes #563: Set pager to zero items on Person view (to allow override)
  modules/custom/az_person/config/install/views.view.az_person.yml
Labels: bug, backport

#987 Closes #176: Added Role Delegation module and permissions.
  .probo.yaml
  az_quickstart.info.yml
  az_quickstart.profile
  composer.json
  config/install/user.role.administrator.yml
  config/install/user.role.az_user_admin.yml
Labels: enhancement, backport
