Repository az-digital/az_quickstart, pull requests merged in 2021-09, with the labels that each got.

#992 Closes #989 edit media from the parent referencing form.
  composer.json
  modules/custom/az_event/config/install/core.entity_form_display.node.az_event.default.yml
  modules/custom/az_flexible_page/config/install/core.entity_form_display.node.az_flexible_page.default.yml
  modules/custom/az_media/az_media.info.yml
  modules/custom/az_media/az_media.install
  modules/custom/az_media/az_media.module
  modules/custom/az_news/config/install/core.entity_form_display.node.az_news.default.yml
  modules/custom/az_paragraphs/az_paragraphs_photo_gallery/config/install/core.entity_form_display.paragraph.az_photo_gallery.default.yml
  modules/custom/az_paragraphs/az_paragraphs_text_media/az_paragraphs_text_media.install
  modules/custom/az_paragraphs/az_paragraphs_text_media/config/install/core.entity_form_display.paragraph.az_text_media.default.yml
  modules/custom/az_person/config/install/core.entity_form_display.node.az_person.default.yml
  modules/custom/az_seo/config/quickstart/core.entity_form_display.node.az_event.default.yml
  modules/custom/az_seo/config/quickstart/core.entity_form_display.node.az_flexible_page.default.yml
  modules/custom/az_seo/config/quickstart/core.entity_form_display.node.az_news.default.yml
  modules/custom/az_seo/config/quickstart/core.entity_form_display.node.az_person.default.yml
Labels: enhancement, blocker, backport, high priority

#1017 Closes #1016: Remove eslint-config-drupal-bundle (use existing javscript tooling instead) and apply ESlint fixes.
  .ddev/commands/web/eslint
  .ddev/commands/web/install
  .lando.yml
  .probo.yaml
  modules/custom/az_event/js/az_calendar_filter.es6.js
  modules/custom/az_event/js/az_calendar_filter.js
  modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_youtube.es6.js
Labels: bug, backport, ci, high priority

#1022 Closes #1021 Document how-to enable theme debugging.
  CONTRIBUTING.md
Labels: documentation

#1025 Allow content editors to edit any media
  config/install/user.role.az_content_admin.yml
  config/install/user.role.az_content_editor.yml
Labels: bug, backport

#1030 Closes #1029: Updated Drupal core to 9.2.6 (moderately critical security update).
  composer.json
Labels: bug, backport, dependencies

#1032 Closes #1031: Updated entity_embed module to 8.x-1.2 for SA-CONTRIB-2021-028 (moderately critical security update).
  composer.json
Labels: bug, backport, dependencies

#1033 #360: Limiting the Views options to AZ Events, AZ News and AZ Person.
  modules/custom/az_paragraphs/az_paragraphs_view/config/install/field.field.paragraph.az_view_reference.field_az_view_reference.yml
Labels: enhancement, backport

#1024 Closes #1028: Update text on media title text on dark background to be white.
  modules/custom/az_paragraphs/az_paragraphs_text_media/templates/paragraph--az-text-media--default.html.twig
Labels: bug, backport

#1037 Closes #1036: Adding taxonomy permissions for page
  config/install/user.role.az_content_admin.yml
Labels: bug, backport

#995 Closes #990: Add responsive image styles for full width background.
  config/optional/responsive_image.styles.narrow.yml
  config/optional/responsive_image.styles.wide.yml
  modules/custom/az_media/az_media.breakpoints.yml
  modules/custom/az_media/az_media.info.yml
  modules/custom/az_media/az_media.install
  modules/custom/az_media/config/install/core.entity_form_display.media.az_image.default.yml
  modules/custom/az_media/config/install/core.entity_form_display.media.az_image.media_library.yml
  modules/custom/az_media/config/install/crop.type.az_full_width_bg_extra_small.yml
  modules/custom/az_media/config/install/crop.type.az_full_width_bg_large.yml
  modules/custom/az_media/config/install/crop.type.az_full_width_bg_medium.yml
  modules/custom/az_media/config/install/crop.type.az_full_width_bg_small.yml
  modules/custom/az_media/config/install/image.style.az_full_width_bg_extra_small.yml
  modules/custom/az_media/config/install/image.style.az_full_width_bg_large.yml
  modules/custom/az_media/config/install/image.style.az_full_width_bg_medium.yml
  modules/custom/az_media/config/install/image.style.az_full_width_bg_small.yml
  modules/custom/az_media/config/install/responsive_image.styles.az_full_width_background.yml
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithMediaParagraphBehavior.php
Labels: enhancement

#1038 Closes #446: Summary link field(s) cannot use tokens.
  modules/custom/az_core/az_core.module
  modules/custom/az_demo/data/az_demo_event_node.json
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_card.yml
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_row.yml
Labels: enhancement, backport

#1052 Closes #1048: Text on media with video demo content
  modules/custom/az_demo/data/az_demo_page_node.json
  modules/custom/az_demo/data/az_demo_remote_video.json
  modules/custom/az_demo/data/az_demo_text_media_paragraph.json
  modules/custom/az_demo/migrations/az_demo_remote_video.yml
  modules/custom/az_demo/migrations/az_demo_text_media_paragraph.yml
  modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehavior.php
Labels: enhancement, backport

#1053 Closes #1043 | Add pronoun field to AZ Person
  modules/custom/az_person/README.md
  modules/custom/az_person/config/install/core.entity_form_display.node.az_person.default.yml
  modules/custom/az_person/config/install/core.entity_view_display.node.az_person.az_card.yml
  modules/custom/az_person/config/install/core.entity_view_display.node.az_person.az_row.yml
  modules/custom/az_person/config/install/core.entity_view_display.node.az_person.default.yml
  modules/custom/az_person/config/install/field.field.node.az_person.field_az_pronouns.yml
  modules/custom/az_person/config/install/field.storage.node.field_az_pronouns.yml
  modules/custom/az_seo/config/quickstart/core.entity_form_display.node.az_person.default.yml
  themes/custom/az_barrio/templates/content/node--az-person--az-card.html.twig
  themes/custom/az_barrio/templates/content/node--az-person--az_row.html.twig
  themes/custom/az_barrio/templates/content/node--az-person--full.html.twig
Labels: documentation, enhancement

#1058 Closes #771: Use system branding block to support text-based web headers and more.
  az_quickstart.profile
  modules/custom/az_core/az_core.module
  modules/custom/az_core/src/Form/QuickstartCoreSettingsForm.php
  themes/custom/az_barrio/az_barrio.info.yml
  themes/custom/az_barrio/az_barrio.theme
  themes/custom/az_barrio/config/install/az_barrio.settings.yml
  themes/custom/az_barrio/config/optional/block.block.az_barrio_branding.yml
  themes/custom/az_barrio/templates/blocks/block--system-branding-block.html.twig
  themes/custom/az_barrio/templates/layout/page.html.twig
Labels: enhancement, backport, high priority

#1045 Fixes #377 Card Followup Tasks
  modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php
Labels: enhancement, spike, high priority
