Repository az-digital/az_quickstart, pull requests merged in 2021-07, with the labels that each got.

#890 Closes #447 #448: Add captions and credit field to inline images
  modules/custom/az_media/config/install/core.entity_form_display.media.az_image.default.yml
  modules/custom/az_media/config/install/core.entity_form_display.media.az_image.media_library.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_large.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_medium.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_natural_size.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_small.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_square.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_image.default.yml
  modules/custom/az_media/config/install/field.field.media.az_image.field_az_credit.yml
  modules/custom/az_media/config/install/field.storage.media.field_az_credit.yml
Labels: backport, enhancement

#874 Closes #786: Migration for D7 marquee paragraph text (to text on media).
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_content_marquee.yml
  modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsBehavior.php
Labels: backport, migration

#903 Add Content Moderation to install profile
  az_quickstart.info.yml
Labels: bug, top priority

#703 #444 Updating sidebar nav heading styles
  themes/custom/az_barrio/templates/blocks/block--az-barrio-sidebar-menu.html.twig
Labels: backport, enhancement

#914 Fix phpcs warnings
  modules/custom/az_accordion/src/Plugin/Field/FieldFormatter/AZAccordionDefaultFormatter.php
  modules/custom/az_card/src/AZCardImageHelper.php
  modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php
  modules/custom/az_flexible_block/src/Plugin/Menu/LocalAction/AzFlexibleBlockAddLocalAction.php
  modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsChunksViewDisplayMapping.php
  modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsColumnImageFieldMerge.php
  modules/custom/az_migration/src/Plugin/migrate/source/AZFileHandle.php
  modules/custom/az_paragraphs/az_paragraphs_text_background/az_paragraphs_text_background.install
  themes/custom/az_barrio/theme-settings.php
Labels: backport, bug

#908 Closes #907: Point Quickstart indicator to quickstart.arizona.edu
  modules/custom/az_core/az_core.module
Labels: backport, enhancement

#909 Closes #656: Add padding/margin for text_media paragraph type
  modules/custom/az_paragraphs/az_paragraphs_text_media/az_paragraphs_text_media.install
  modules/custom/az_paragraphs/az_paragraphs_text_media/templates/paragraph--az-text-media--default.html.twig
  modules/custom/az_paragraphs/css/az_paragraphs_az_text_media.css
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithMediaParagraphBehavior.php
Labels: backport, enhancement

#904 Closes #902: Removing basic restricted html permissions
  config/install/filter.format.basic_html.yml
  config/install/filter.format.restricted_html.yml
  config/install/user.role.anonymous.yml
  config/install/user.role.authenticated.yml
Labels: backport, enhancement

#910 Fixes #547 Create Full Calendar Filter
  composer.json
  modules/custom/az_event/az_event.info.yml
  modules/custom/az_event/az_event.install
  modules/custom/az_event/az_event.libraries.yml
  modules/custom/az_event/az_event.views.inc
  modules/custom/az_event/config/install/core.entity_form_display.node.az_event.default.yml
  modules/custom/az_event/config/install/views.view.az_events.yml
  modules/custom/az_event/config/schema/az_event.views.filter.schema.yml
  modules/custom/az_event/css/az_calendar_filter.css
  modules/custom/az_event/js/az_calendar_filter.es6.js
  modules/custom/az_event/js/az_calendar_filter.js
  modules/custom/az_event/src/Plugin/views/filter/AZCalendarFilter.php
  themes/custom/az_barrio/config/optional/block.block.exposedformaz_eventspage_1.yml
Labels: backport, enhancement, high priority, top priority

#912 Fixes #896 embedded image alignment, and Fixes #900 add visual indicator on unpublished content.
  modules/custom/az_media/az_media.libraries.yml
  modules/custom/az_media/az_media.module
  modules/custom/az_media/config/install/core.entity_view_display.media.az_remote_video.az_large.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_remote_video.az_medium.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_remote_video.az_natural_size.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_remote_video.az_small.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_remote_video.az_square.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_remote_video.default.yml
  modules/custom/az_media/config/install/filter.format.az_standard.yml
  modules/custom/az_media/css/az-media-display.css
  modules/custom/az_media/css/az-media-edit.css
  themes/custom/az_barrio/az_barrio.info.yml
  themes/custom/az_barrio/css/style.css
Labels: backport, bug, enhancement, good first issue, www gap

#921 Closes #916 — Restore the Barrio node__content margin-top, override it on az_flexible_page.
  modules/custom/az_flexible_page/az_flexible_page.libraries.yml
  modules/custom/az_flexible_page/az_flexible_page.module
  modules/custom/az_flexible_page/css/az_flexible_page.theme.css
  themes/custom/az_barrio/css/style.css
Labels: backport, bug

#922 Closes #852: Restore the original fix, broken when re-introducing default margins.
  modules/custom/az_flexible_page/css/az_flexible_page.theme.css
Labels: backport, bug, top priority

#931 Closes #929: Fix sidebar nav can't scroll on mobile (temporary fix).
  themes/custom/az_barrio/css/style.css
Labels: backport, bug

#930 Closes #927: Fixing background on content for column (on text with media).
  modules/custom/az_paragraphs/az_paragraphs_text_media/templates/paragraph--az-text-media--default.html.twig
Labels: backport, bug, top priority

#928 Closes #925: Add documentation for how to use/install Quickstart to README.
  README.md
Labels: backport, documentation, high priority

#935 Closes #934: Label az_demo and az_migration as experimental modules.
  modules/custom/az_demo/az_demo.info.yml
  modules/custom/az_migration/az_migration.info.yml
Labels: backport, enhancement, top priority

#936 Closes #932 set new account creation to admin only
  az_quickstart.profile
  config/install/user.settings.yml
Labels: backport, enhancement, top priority

#940 Closes #939: Fix install time footer menu-block config warnings.
  themes/custom/az_barrio/config/optional/block.block.az_barrio_footer_menu_info.yml
  themes/custom/az_barrio/config/optional/block.block.az_barrio_footer_menu_main.yml
  themes/custom/az_barrio/config/optional/block.block.az_barrio_footer_menu_resources.yml
  themes/custom/az_barrio/config/optional/block.block.az_barrio_footer_menu_topics.yml
Labels: backport, bug

#945 Closes #941: Make the selectors in the CSS rule applying the margin-top override very specific.
  modules/custom/az_flexible_page/css/az_flexible_page.theme.css
Labels: backport, bug

#953 Closes #952: Updated Drupal core to 9.2.2 for SA-CORE-2021-004.
  composer.json
Labels: backport, bug

#947 Closes #926 remove az_media as a dependency of az_barrio
  modules/custom/az_media/az_media.libraries.yml
  themes/custom/az_barrio/az_barrio.info.yml
  themes/custom/az_barrio/az_barrio.libraries.yml
  themes/custom/az_barrio/css/az-media-display.css
Labels: backport, enhancement

#949 Closes #948 Update contributing docs with devel and theme debug settings.
  CONTRIBUTING.md
Labels: backport, documentation

#955 Closes #943: Adding Google Tag Manager
  az_quickstart.info.yml
  composer.json
  modules/custom/az_google_tag/az_google_tag.info.yml
  modules/custom/az_google_tag/az_google_tag.module.php
  modules/custom/az_google_tag/config/install/google_tag.container.az_comprehensive.yml
Labels: backport, enhancement

#879 Closes #814: Adding pages, events and some paragraph types, files, and taxonomy to demo content.
  modules/custom/az_demo/az_demo.info.yml
  modules/custom/az_demo/az_demo.install
  modules/custom/az_demo/data/az_demo_event_node.json
  modules/custom/az_demo/data/az_demo_event_rrule.json
  modules/custom/az_demo/data/az_demo_image_file.json
  modules/custom/az_demo/data/az_demo_menu_links.json
  modules/custom/az_demo/data/az_demo_page_node.json
  modules/custom/az_demo/data/az_demo_person_node.json
  modules/custom/az_demo/data/az_demo_text_background_paragraph.json
  modules/custom/az_demo/data/az_demo_text_media_paragraph.json
  modules/custom/az_demo/data/az_demo_text_paragraph.json
  modules/custom/az_demo/images/The_Hay_Wain_by_Hieronymus_Bosch.jpeg
  modules/custom/az_demo/images/arizona-desert.jpg
  modules/custom/az_demo/images/arizona_campus_fireworks.jpg
  modules/custom/az_demo/images/badwater_panorama.jpg
  modules/custom/az_demo/images/daisy.jpg
  modules/custom/az_demo/images/june_bugs.jpeg
  modules/custom/az_demo/images/lynx.jpg
  modules/custom/az_demo/images/mecklerphoto_mens-wearhouse.jpeg
  modules/custom/az_demo/images/sea-anemone.jpg
  modules/custom/az_demo/images/study.jpeg
  modules/custom/az_demo/migrations/az_demo_event_node.yml
  modules/custom/az_demo/migrations/az_demo_event_rrule.yml
  modules/custom/az_demo/migrations/az_demo_menu_links.yml
  modules/custom/az_demo/migrations/az_demo_page_node.yml
  modules/custom/az_demo/migrations/az_demo_person_node.yml
  modules/custom/az_demo/migrations/az_demo_text_background_paragraph.yml
  modules/custom/az_demo/migrations/az_demo_text_media_paragraph.yml
  modules/custom/az_demo/migrations/az_demo_text_paragraph.yml
  modules/custom/az_demo/tests/src/Functional/AZDemoContentTest.php
  modules/custom/az_event/src/Plugin/migrate/process/SmartDateCreateRecurrenceOnField.php
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_content_marquee.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_full_width_media_row.yml
  modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehavior.php
Labels: backport, enhancement

#837 Add configuration for anonymous review
  composer.json
  config/install/user.role.anonymous.yml
  config/install/user.role.authenticated.yml
  config/install/user.role.az_content_admin.yml
  config/optional/access_unpublished.settings.yml
Labels: contractor
