Repository az-digital/az_quickstart, pull requests merged in 2021-12, with the labels that each got.

#1163 Closes #1162: Fix notices being generated by Text with background paragraphs behavior.
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithBackgroundParagraphBehavior.php
Labels: bug, backport

#1165 Closes #1164: Add ProboCI step to check for PHP error/notice logs.
  .probo.yaml
Labels: enhancement, backport, ci

#1172 Closes #1171: Add Social Media menu
  config/install/system.menu.az-footer-social-media.yml
  themes/custom/az_barrio/config/optional/block.block.az_barrio_footer_menu_social_media.yml
Labels: enhancement, backport, www gap

#1175 Fixes #1169: Add Menu Link Attributes module
  composer.json
Labels: enhancement, backport

#1173 Fixes #1170: Added setting for disabling default user login form.
  modules/custom/az_cas/az_cas.services.yml
  modules/custom/az_cas/config/install/az_cas.settings.yml
  modules/custom/az_cas/config/schema/az_cas.schema.yml
  modules/custom/az_cas/src/Form/AzCasSettingsForm.php
  modules/custom/az_cas/src/Routing/AzCasRouteSubscriber.php
  modules/custom/az_cas/src/Subscriber/PreventPasswordResetSubscriber.php
  modules/custom/az_cas/tests/src/Functional/AzCasAdminSettingsTest.php
Labels: enhancement, backport

#1013 Closes #1012: Fixes footer styling/templates
  az_quickstart.info.yml
  composer.json
  modules/custom/az_demo/az_demo.install
  modules/custom/az_demo/data/az_demo_menu_links.json
  themes/custom/az_barrio/az_barrio.theme
  themes/custom/az_barrio/config/install/az_barrio.settings.yml
  themes/custom/az_barrio/config/optional/block.block.az_barrio_footer_menu_info.yml
  themes/custom/az_barrio/config/optional/block.block.az_barrio_footer_menu_main.yml
  themes/custom/az_barrio/config/optional/block.block.az_barrio_footer_menu_resources.yml
  themes/custom/az_barrio/config/optional/block.block.az_barrio_footer_menu_topics.yml
  themes/custom/az_barrio/templates/blocks/block--az-barrio-footer-menu-info.html.twig
  themes/custom/az_barrio/templates/blocks/block--az-barrio-footer-menu-resources.html.twig
  themes/custom/az_barrio/templates/blocks/block--az-barrio-footer-menu-topics.html.twig
  themes/custom/az_barrio/templates/navigation/menu--footer_main.html.twig
  themes/custom/az_barrio/templates/navigation/menu--sub_footer.html.twig
  themes/custom/az_barrio/templates/navigation/menu--sub_footer_topics.html.twig
Labels: bug, backport

#1178 Updating .lando.yml to be used with Apple M1 Chip
  .lando.yml
Labels: enhancement, backport, ci, dependencies

#1185 Closes #1062 Add summary link field to Person content type
  modules/custom/az_person/config/install/core.entity_form_display.node.az_person.default.yml
  modules/custom/az_person/config/install/field.field.node.az_person.field_az_link.yml
  modules/custom/az_seo/config/quickstart/core.entity_form_display.node.az_person.default.yml
  themes/custom/az_barrio/templates/content/node--az-person--az-card.html.twig
  themes/custom/az_barrio/templates/content/node--az-person--az_row.html.twig
Labels: enhancement, backport

#1186 Fixes #1184 Regression: Bottom margin on text on media paragraphs no longer works.
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithMediaParagraphBehavior.php
Labels: bug, backport

#1189 Closes #1166 Changes Content position 'none' option to say 'full-width'
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithMediaParagraphBehavior.php
Labels: enhancement, backport

#1147 Closes #1146 Migrate basic page content type (to az_page)
  modules/custom/az_migration/migrations/migrate_plus.migration.az_node_uaqs_basic_page_to_az_page.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_uaqs_basic_page_to_az_page.yml
Labels: enhancement, backport, migration

#1198 Closes #1197 Fixes content moderation workflow problem
  config/optional/workflows.workflow.editorial.yml
Labels: bug, backport

#1193 Closes #1192: Use correct field name from AzParagraphsItem source plugin in card deck migration.
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_card_deck.yml
Labels: bug, backport, migration

#1191 Closes #1150: Fix issues with Single Card paragraph migration.
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_single_card.yml
Labels: bug, backport, migration

#1205 Closes #1204: Removing problem classes from footer sub region (for now).
  themes/custom/az_barrio/config/install/az_barrio.settings.yml
Labels: bug, backport
