Repository az-digital/az_quickstart, pull requests merged in 2022-01, with the labels that each got.

#1168 Closes #656 Add option to use image aspect ratio for background aspect ratio.
  modules/custom/az_media/config/install/core.entity_form_display.media.az_remote_video.default.yml
  modules/custom/az_paragraphs/az_paragraphs_text_media/config/install/core.entity_view_display.paragraph.az_text_media.default.yml
  modules/custom/az_paragraphs/css/az_paragraphs_az_text_media.css
  modules/custom/az_paragraphs/css/az_paragraphs_full_width.css
  modules/custom/az_paragraphs/src/Plugin/Field/FieldFormatter/AZBackgroundMediaFormatter.php
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithMediaParagraphBehavior.php
Labels: documentation, enhancement, backport, www gap, high priority

#1217 Adding more information to the cards migration readme.
  modules/custom/az_migration/README.md
Labels: documentation, backport

#1216 #1150: Fixes additional single card migration issues.
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_single_card.yml
  modules/custom/az_migration/src/Plugin/migrate/source/AZParagraphsItem.php
Labels: bug, backport, migration

#1200 Closes #1049 | Adds global footer content/migration
  modules/custom/az_global_footer/README.md
  modules/custom/az_global_footer/az_global_footer.info.yml
  modules/custom/az_global_footer/az_global_footer.install
  modules/custom/az_global_footer/az_global_footer.module
  modules/custom/az_global_footer/config/install/block.block.az_barrio_footer_menu_info.yml
  modules/custom/az_global_footer/config/install/block.block.az_barrio_footer_menu_main.yml
  modules/custom/az_global_footer/config/install/block.block.az_barrio_footer_menu_resources.yml
  modules/custom/az_global_footer/config/install/block.block.az_barrio_footer_menu_social_media.yml
  modules/custom/az_global_footer/config/install/block.block.az_barrio_footer_menu_topics.yml
  modules/custom/az_global_footer/data/az_global_footer.json
  modules/custom/az_global_footer/migrations/az_global_footer_links.yml
  themes/custom/az_barrio/config/install/az_barrio.settings.yml
  themes/custom/az_barrio/css/style.css
Labels: documentation, enhancement

#1220 Closes #737 Clickable Card
  modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php
  modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehavior.php
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZCardsParagraphBehavior.php
Labels: enhancement, backport

#1227 Closes #1221: Adds classes for connect menu block
  modules/custom/az_global_footer/config/install/block.block.az_barrio_footer_menu_social_media.yml
Labels: bug

#1237 Closes #1228, closes #1229: Added new menu-specific footer theme region.
  modules/custom/az_global_footer/config/install/block.block.az_barrio_footer_menu_info.yml
  modules/custom/az_global_footer/config/install/block.block.az_barrio_footer_menu_resources.yml
  modules/custom/az_global_footer/config/install/block.block.az_barrio_footer_menu_social_media.yml
  modules/custom/az_global_footer/config/install/block.block.az_barrio_footer_menu_topics.yml
  themes/custom/az_barrio/az_barrio.info.yml
  themes/custom/az_barrio/az_barrio.theme
  themes/custom/az_barrio/config/install/az_barrio.settings.yml
  themes/custom/az_barrio/config/schema/az_barrio.schema.yml
  themes/custom/az_barrio/templates/layout/page.html.twig
Labels: enhancement

#1240 Closes #1239: Updated Drupal core to 9.2.11 for SA-CORE-2022-001 (moderately critical security update).
  composer.json
Labels: bug, backport, dependencies

#1243 Closes #1242: Update jQuery UI Datepicker to 1.2 for SA-CONTRIB-2022-004 (moderately critical security update).
  composer.json
Labels: bug, backport, dependencies

#1241 Closes #749: Add card link style options
  modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php
  modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php
Labels: enhancement

#1117 Closes #559: Adds news feed importer migration(s).
  composer.json
  modules/custom/az_news/az_news_feeds/az_news_feeds.info.yml
  modules/custom/az_news/az_news_feeds/az_news_feeds.install
  modules/custom/az_news/az_news_feeds/az_news_feeds.links.task.yml
  modules/custom/az_news/az_news_feeds/az_news_feeds.routing.yml
  modules/custom/az_news/az_news_feeds/az_news_feeds.services.yml
  modules/custom/az_news/az_news_feeds/config/install/az_news_feeds.settings.yml
  modules/custom/az_news/az_news_feeds/config/install/migrate_plus.migration.az_news_feed_stories.yml
  modules/custom/az_news/az_news_feeds/config/install/migrate_plus.migration.az_news_feed_stories_files.yml
  modules/custom/az_news/az_news_feeds/config/install/migrate_plus.migration.az_news_feed_stories_media.yml
  modules/custom/az_news/az_news_feeds/config/install/migrate_plus.migration_group.az_news_feeds.yml
  modules/custom/az_news/az_news_feeds/config/install/migrate_queue_importer.cron_migration.az_news_feeds.yml
  modules/custom/az_news/az_news_feeds/config/schema/az_news_feeds.schema.yml
  modules/custom/az_news/az_news_feeds/src/EventSubscriber/AzNewsFeedsMigrateSubscriber.php
  modules/custom/az_news/az_news_feeds/src/Form/AzNewsFeedsAdminForm.php
  modules/custom/az_news/az_news_feeds/src/Plugin/migrate/process/ArrayIntersect.php
Labels: documentation, enhancement, www gap, high priority, migration

#1250 Closes #1222: Update min-height of red bar to accommodate different theme settings.
  themes/custom/az_barrio/az_barrio.libraries.yml
  themes/custom/az_barrio/az_barrio.theme
  themes/custom/az_barrio/css/az-barrio-off-canvas-nav.css
  themes/custom/az_barrio/css/style.css
Labels: bug, backport, www gap, high priority

#1257 Fixes #1215 Image Quality Issues
  config/install/system.image.gd.yml
  config/install/system.image.yml
Labels: bug, backport, www gap, high priority

#1255 Closes #1254: Don't install quickedit module by default.
  az_quickstart.info.yml
  composer.json
Labels: bug

#1249 Closes #1248: Fix undefined index notices generated for existing cards.
  modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php
Labels: bug, backport

#1264 Update composer branch alias for dev-main to 2.2.x-dev.
  composer.json
Labels: backport, ci
