Repository az-digital/az_quickstart, pull requests merged in 2022-09, with the labels that each got.

#1878 2022-08-31 Consolidated dependabot updates.
  composer.json
Labels: dependencies, Drupal, 2.5.x only

#1882 Closes #1881: Fix broken Dependency check job in security.yml GH actions workflow.
  .github/workflows/security.yml
Labels: bug, ci, dependencies

#1865 Closes #692: Add version to info.yml during release action.
  .github/workflows/create-release.yml
Labels: enhancement, backport, ci, high priority

#1860 Closes #1837: Update URL of Global Engagement link in global footer.
  modules/custom/az_global_footer/az_global_footer.info.yml
  modules/custom/az_global_footer/az_global_footer.install
  modules/custom/az_global_footer/data/az_global_footer.json
Labels: bug, task, high priority, 2.5.x only

#1859 Closes #1858: Fix broken ProboCI 'Check for PHP errors and notices' step.
  .probo.yaml
Labels: bug, ci

#1880 Closes #647: Use linkit for Card field link elements.
  composer.json
  modules/custom/az_card/az_card.info.yml
  modules/custom/az_card/css/az-card-widget.css
  modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php
Labels: bug, enhancement, 2.5.x only

#1892 Closes #1891: Use privileged GH token for 'Create Release' workflow.
  .github/workflows/create-release.yml
Labels: bug, backport, ci, high priority, patch release

#1895 Closes #937: Fix missing icons in accordion previews.
  modules/custom/az_paragraphs/az_paragraphs.libraries.yml
Labels: bug, backport, patch release

#1905 Closes #1903: Tag correct revision during 'Create release' GH actions workflow.
  .github/workflows/create-release.yml
Labels: bug, ci, high priority

#1887 Closes #574 Adding az_menu block_content type.
  composer.json
  config/install/user.role.az_content_admin.yml
  modules/custom/az_block_types/az_custom_menu_block/az_custom_menu_block.info.yml
  modules/custom/az_block_types/az_custom_menu_block/az_custom_menu_block.module
  modules/custom/az_block_types/az_custom_menu_block/config/install/block_content.type.az_custom_menu_block.yml
  modules/custom/az_block_types/az_custom_menu_block/config/install/core.entity_form_display.block_content.az_custom_menu_block.default.yml
  modules/custom/az_block_types/az_custom_menu_block/config/install/core.entity_view_display.block_content.az_custom_menu_block.default.yml
  modules/custom/az_block_types/az_custom_menu_block/config/install/field.field.block_content.az_custom_menu_block.field_az_block.yml
  modules/custom/az_block_types/az_custom_menu_block/config/install/field.storage.block_content.field_az_block.yml
  modules/custom/az_demo/az_demo.info.yml
  modules/custom/az_demo/data/az_demo_block_content_block.json
  modules/custom/az_demo/data/az_demo_menu_links.json
  modules/custom/az_demo/data/az_demo_page_node.json
  modules/custom/az_demo/data/az_demo_splitscreen_paragraph.json
  modules/custom/az_demo/data/az_demo_text_paragraph.json
  modules/custom/az_demo/migrations/az_demo_block_content_menu.yml
  themes/custom/az_barrio/css/style.css
  themes/custom/az_barrio/templates/navigation/menu--sidebar.html.twig
Labels: enhancement, QS1 feature parity, 2.5.x only

#1899 Closes #1864: Add new breadcrumb-item-home class to front page segment.
  config/install/easy_breadcrumb.settings.yml
  themes/custom/az_barrio/az_barrio.theme
  themes/custom/az_barrio/config/optional/block.block.az_barrio_breadcrumbs.yml
  themes/custom/az_barrio/templates/navigation/breadcrumb.html.twig
Labels: enhancement, 2.5.x only

#1937 Closes #1936: Add patch to fix CAS module session handling on Drupal 9.2+.
  composer.json
Labels: bug, high priority, patch release

#1943 #1942: Update Drupal core to 9.3.22 for SA-CORE-2022-016 (critical security update).
  composer.json
Labels: dependencies, high priority, Drupal, patch release, 2.3.x only

#1944 #1942: Update Drupal core to 9.4.7 for SA-CORE-2022-016 (critical security update).
  composer.json
Labels: dependencies, high priority, Drupal, patch release

#1919 Don't call parent::prepareRow() in Paragraphs Item source plugin.
  composer.json
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_callout.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_card_deck.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_carousel.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_chucks_view.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_column_image.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_content_marquee.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_extra_info.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_file_download.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_full_width_bg_wrapper.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_full_width_media_row.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_gallery.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_headed_text.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_html.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_jumbotron.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_panel_group.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_plain_text.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_single_card.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_well.yml
  modules/custom/az_migration/src/Plugin/migrate/source/AZParagraphsItem.php
Labels: migration

#1533 Closes #1530 Adding theme-debug tooling for lando and ddev.
  .ddev/commands/web/theme-debug
  .lando.yml
  CONTRIBUTING.md
Labels: enhancement

#1934 Closes #1933 Remove migrate_plus.migration prefix on migration YAML filenames
  modules/custom/az_migration/migrations/az_cas_user.yml
  modules/custom/az_migration/migrations/az_event_categories.yml
  modules/custom/az_migration/migrations/az_files.yml
  modules/custom/az_migration/migrations/az_flexible_page_categories.yml
  modules/custom/az_migration/migrations/az_media.yml
  modules/custom/az_migration/migrations/az_menu_links.yml
  modules/custom/az_migration/migrations/az_news_tags.yml
  modules/custom/az_migration/migrations/az_node_carousel.yml
  modules/custom/az_migration/migrations/az_node_event.yml
  modules/custom/az_migration/migrations/az_node_flexible_page.yml
  modules/custom/az_migration/migrations/az_node_news.yml
  modules/custom/az_migration/migrations/az_node_person.yml
  modules/custom/az_migration/migrations/az_node_uaqs_basic_page_to_az_page.yml
  modules/custom/az_migration/migrations/az_paragraph_callout.yml
  modules/custom/az_migration/migrations/az_paragraph_card_deck.yml
  modules/custom/az_migration/migrations/az_paragraph_carousel.yml
  modules/custom/az_migration/migrations/az_paragraph_chucks_view.yml
  modules/custom/az_migration/migrations/az_paragraph_column_image.yml
  modules/custom/az_migration/migrations/az_paragraph_contact.yml
  modules/custom/az_migration/migrations/az_paragraph_content_marquee.yml
  modules/custom/az_migration/migrations/az_paragraph_extra_info.yml
  modules/custom/az_migration/migrations/az_paragraph_file_download.yml
  modules/custom/az_migration/migrations/az_paragraph_flexible_page_sub.yml
  modules/custom/az_migration/migrations/az_paragraph_full_width_bg_wrapper.yml
  modules/custom/az_migration/migrations/az_paragraph_full_width_media_row.yml
  modules/custom/az_migration/migrations/az_paragraph_gallery.yml
  modules/custom/az_migration/migrations/az_paragraph_headed_text.yml
  modules/custom/az_migration/migrations/az_paragraph_html.yml
  modules/custom/az_migration/migrations/az_paragraph_jumbotron.yml
  modules/custom/az_migration/migrations/az_paragraph_panel_group.yml
  modules/custom/az_migration/migrations/az_paragraph_plain_text.yml
  modules/custom/az_migration/migrations/az_paragraph_single_card.yml
  modules/custom/az_migration/migrations/az_paragraph_uaqs_basic_page_to_az_page.yml
  modules/custom/az_migration/migrations/az_paragraph_well.yml
  modules/custom/az_migration/migrations/az_person_categories.yml
  modules/custom/az_migration/migrations/az_person_categories_secondary.yml
  modules/custom/az_migration/migrations/az_user.yml
Labels: migration, 2.5.x only

#1918 Closes #1917 Adding config schema for az_migration module.
  modules/custom/az_migration/config/schema/az_migration.schema.yml
Labels: bug, blocker, migration

#1910 Fixes #1877 Snapshot only Necessary Config on Override
  modules/custom/az_core/az_core.services.yml
  modules/custom/az_core/src/AZConfigOverride.php
Labels: bug, 2.5.x only

#1950 Closes #1830: Update AZ Event Default view display to fix heading tags, reorder content
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.default.yml
Labels: low priority, 2.5.x only, visual change

#1797 Closes #1763, Closes #1918 - Adding config for optionally importing archived paragraphs.
  composer.json
  modules/custom/az_migration/README.md
  modules/custom/az_migration/config/install/az_migration.settings.yml
  modules/custom/az_migration/config/schema/az_migration.schema.yml
  modules/custom/az_migration/migrations/az_paragraph_callout.yml
  modules/custom/az_migration/migrations/az_paragraph_card_deck.yml
  modules/custom/az_migration/migrations/az_paragraph_carousel.yml
  modules/custom/az_migration/migrations/az_paragraph_chucks_view.yml
  modules/custom/az_migration/migrations/az_paragraph_column_image.yml
  modules/custom/az_migration/migrations/az_paragraph_contact.yml
  modules/custom/az_migration/migrations/az_paragraph_content_marquee.yml
  modules/custom/az_migration/migrations/az_paragraph_extra_info.yml
  modules/custom/az_migration/migrations/az_paragraph_file_download.yml
  modules/custom/az_migration/migrations/az_paragraph_full_width_bg_wrapper.yml
  modules/custom/az_migration/migrations/az_paragraph_full_width_media_row.yml
  modules/custom/az_migration/migrations/az_paragraph_gallery.yml
  modules/custom/az_migration/migrations/az_paragraph_headed_text.yml
  modules/custom/az_migration/migrations/az_paragraph_html.yml
  modules/custom/az_migration/migrations/az_paragraph_jumbotron.yml
  modules/custom/az_migration/migrations/az_paragraph_panel_group.yml
  modules/custom/az_migration/migrations/az_paragraph_plain_text.yml
  modules/custom/az_migration/migrations/az_paragraph_single_card.yml
  modules/custom/az_migration/migrations/az_paragraph_well.yml
  modules/custom/az_migration/src/Plugin/migrate/source/AZParagraphsItem.php
Labels: bug, migration, 2.5.x only
