Repository az-digital/az_quickstart, pull requests merged in 2022-07, with the labels that each got.

#1683 Closes #1677: Update Text on Media Bottom Style
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithMediaParagraphBehavior.php
Labels: enhancement, 2.4.x only

#1721 Closes #1719 - Update node version in `.lando` file
  .lando.yml
Labels: enhancement, ci, dependencies, 2.4.x only

#1592 Closes #1550 Initial Intelligence Bank integration.
  composer.json
  config/install/user.role.az_content_editor.yml
  modules/custom/az_digital_asset_library/az_digital_asset_library.info.yml
  modules/custom/az_digital_asset_library/az_digital_asset_library.links.action.yml
  modules/custom/az_digital_asset_library/az_digital_asset_library.module
  modules/custom/az_digital_asset_library/config/install/entity_browser.browser.az_digital_asset_library.yml
  modules/custom/az_digital_asset_library/config/quickstart/ib_dam.settings.yml
  modules/custom/az_digital_asset_library/config/quickstart/ib_dam_media.settings.yml
Labels: enhancement, 2.4.x only

#1594 Closes #1593: Increase PHPStan analysis level and fix existing problems.
  composer.json
  modules/custom/az_accordion/src/Plugin/Field/FieldFormatter/AZAccordionDefaultFormatter.php
  modules/custom/az_accordion/src/Plugin/Field/FieldType/AZAccordionItem.php
  modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php
  modules/custom/az_card/src/Plugin/Field/FieldType/AZCardItem.php
  modules/custom/az_cas/tests/src/Functional/AzCasAdminSettingsTest.php
  modules/custom/az_cas/tests/src/Functional/AzCasTest.php
  modules/custom/az_core/src/Form/QuickstartCoreSettingsForm.php
  modules/custom/az_core/src/PageCache/DenyMonitoringPage.php
  modules/custom/az_core/tests/src/Traits/AllowDrupalLoginSetupTrait.php
  modules/custom/az_demo/tests/src/Functional/AZDemoContentTest.php
  modules/custom/az_event/az_event.module
  modules/custom/az_event/src/Plugin/migrate/process/SmartDateCreateRecurrenceOnField.php
  modules/custom/az_event/src/Plugin/views/filter/AZCalendarFilter.php
  modules/custom/az_flexible_page/az_flexible_page.module
  modules/custom/az_mail/az_mail.module
  modules/custom/az_mail/src/Commands/AZMailCommands.php
  modules/custom/az_media/az_media.module
  modules/custom/az_metrics/az_metrics.module
  modules/custom/az_metrics/src/EventSubscriber/AZMetricsSubscriber.php
  modules/custom/az_migration/src/Plugin/migrate/process/DateTimeToSmartDate.php
  modules/custom/az_migration/src/Plugin/migrate/process/TextFormatRecognizer.php
  modules/custom/az_migration/src/Plugin/migrate/process/ViewsReferenceMapping.php
  modules/custom/az_news/az_news.install
  modules/custom/az_news/az_news_feeds/src/EventSubscriber/AzNewsFeedsMigrateSubscriber.php
  modules/custom/az_news/az_news_feeds/src/Form/AzNewsFeedsAdminForm.php
  modules/custom/az_paragraphs/az_paragraphs_text_background/az_paragraphs_text_background.install
  modules/custom/az_paragraphs/az_paragraphs_text_media/az_paragraphs_text_media.install
  modules/custom/az_paragraphs/src/Plugin/Field/FieldFormatter/AZBackgroundMediaFormatter.php
  modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehaviorSettings.php
  modules/custom/az_paragraphs/tests/src/Functional/AZParagraphsTest.php
  modules/custom/az_paragraphs/tests/src/FunctionalJavascript/AZParagraphsJavascriptTest.php
  phpstan-contrib.neon
  phpstan.neon
  themes/custom/az_barrio/az_barrio.theme
  themes/custom/az_barrio/tests/src/Functional/AzBarrioTest.php
  themes/custom/az_barrio/theme-settings.php
Labels: enhancement, ci, no backport, 2.4.x only

#1729 Fixes #1728 Fix course PHPstan errors.
  modules/custom/az_course/src/CourseMigrateBatchExecutable.php
  modules/custom/az_course/src/CourseSearch.php
  modules/custom/az_course/src/Form/CourseImportForm.php
  modules/custom/az_course/src/Plugin/migrate_plus/data_fetcher/RetryHttp.php
Labels: bug, enhancement, 2.4.x only

#1726 Closes #1716: Add overrides for claro node form layout styles.
  modules/custom/az_core/az_core.libraries.yml
  modules/custom/az_core/az_core.module
  modules/custom/az_core/css/claro-node-form-overrides.css
Labels: bug, 2.4.x only

#1727 Closes #1697: Fix JS error when Text with Background, Text on Media are not full-width
  modules/custom/az_paragraphs/az_paragraphs.libraries.yml
  modules/custom/az_paragraphs/js/az_paragraphs_full_width.es6.js
  modules/custom/az_paragraphs/js/az_paragraphs_full_width.js
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithBackgroundParagraphBehavior.php
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithMediaParagraphBehavior.php
Labels: bug, backport, patch release

#1680 Closes #1651: Add grayscale background color options
  modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php
  modules/custom/az_demo/az_demo.module
  modules/custom/az_demo/data/az_demo_card_paragraph.json
  modules/custom/az_demo/data/az_demo_menu_links.json
  modules/custom/az_demo/data/az_demo_page_node.json
  modules/custom/az_demo/data/az_demo_splitscreen_paragraph.json
  modules/custom/az_demo/data/az_demo_text_background_paragraph.json
  modules/custom/az_demo/data/az_demo_text_paragraph.json
  modules/custom/az_demo/migrations/az_demo_card_paragraph.yml
  modules/custom/az_demo/migrations/az_demo_page_node.yml
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZSplitScreenParagraphBehavior.php
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithBackgroundParagraphBehavior.php
Labels: enhancement, 2.4.x only

#1713 Closes #1700: Update text on media transparent classes
  modules/custom/az_demo/data/az_demo_text_media_paragraph.json
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_content_marquee.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_full_width_media_row.yml
  modules/custom/az_paragraphs/az_paragraphs_text_media/az_paragraphs_text_media.install
  modules/custom/az_paragraphs/css/az_paragraphs_az_text_media.css
  modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehaviorSettings.php
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithMediaParagraphBehavior.php
Labels: enhancement, migration, no backport, 2.4.x only

#1735 Closes #1734: Add patch for known issue affecting field_group module on 9.4.x.
  composer.json
Labels: bug, high priority, 2.4.x only

#1754 Closes #1743 Fix block embeds
  modules/custom/az_paragraphs/js/az_paragraphs_full_width.es6.js
  modules/custom/az_paragraphs/js/az_paragraphs_full_width.js
  themes/custom/az_barrio/js/button-no-conflict.es6.js
  themes/custom/az_barrio/js/button-no-conflict.js
Labels: bug, high priority, 2.4.x only

#1751 #1749: Label az_course as experimental module and disable link to course nodes for now.
  modules/custom/az_course/az_course.info.yml
  modules/custom/az_course/config/install/core.entity_view_display.node.az_course.az_card.yml
Labels: enhancement, 2.4.x only

#1746 Closes #1745: Use correct full-width setting name when adding full-width library.
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithMediaParagraphBehavior.php
Labels: bug, backport, high priority, patch release

#1744 Closes #1742: Update references to removed light and dark classes in Text on Media Paragraphs Behavior.
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithMediaParagraphBehavior.php
Labels: bug, high priority, 2.4.x only

#1759 Closes #1741 Hide default intelligenceBank Media Type.
  composer.json
  modules/custom/az_digital_asset_library/az_digital_asset_library.module
  modules/custom/az_digital_asset_library/config/install/entity_browser.browser.az_digital_asset_library.yml
Labels: bug, blocker, high priority, 2.4.x only

#1737 Closes #1736: Update Drupal core to 9.3.18.
  composer.json
Labels: dependencies, Drupal, 2.3.x only

#1768 Closes #1767: Update Drupal core to 9.4.3 (critical security update).
  composer.json
Labels: bug, dependencies, Drupal, patch release, 2.4.x only

#1769 Closes #1766: Update Drupal core to 9.3.19 (critical security update).
  composer.json
Labels: bug, dependencies, Drupal, patch release, 2.3.x only

#1778 Closes #1777: Add patch for IntelligenceBank issue breaking entity_embeds.
  composer.json
Labels: bug, high priority, 2.4.x only

#1784 Closes #1782: Add mesa as background color option to cards, text on background, and split screen.
  modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_full_width_bg_wrapper.yml
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZSplitScreenParagraphBehavior.php
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithBackgroundParagraphBehavior.php
Labels: enhancement, patch release

#1773 Closes #1382: Add role_delegation patch for restricting access to cancel/remove admin users
  composer.json
Labels: bug, patch release

#1788 Closes #1787: Restore missing Drupal core backbone-min.js.map file (2.3.x only)
  composer.json
Labels: bug, Drupal, 2.3.x only

#1791 Closes #1790, Closes #1792: Update Pathauto patterns for Drupal 9.3+ and use drupal/ctools:4.0.1.
  composer.json
  modules/custom/az_event/config/install/pathauto.pattern.az_event_url_pattern.yml
  modules/custom/az_news/config/install/pathauto.pattern.news_content_type.yml
  modules/custom/az_person/config/install/pathauto.pattern.az_person_url_pattern.yml
Labels: bug, backport, dependencies, high priority, Drupal, patch release
