Repository az-digital/az_quickstart, pull requests merged in 2022-05, with the labels that each got.

#1467 Closes #1462 Optimize javascript behaviors for full width elements.
  modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_youtube.es6.js
  modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_youtube.js
  modules/custom/az_paragraphs/js/az_paragraphs_full_width.es6.js
  modules/custom/az_paragraphs/js/az_paragraphs_full_width.js
Labels: enhancement, 2.3.x only

#1532 Closes #1531 Update quick_node_clone to 1.15 for SA-CONTRIB-2022-038
  composer.json
Labels: bug, backport, dependencies, Drupal, patch release

#1518 Closes #1490: Adding content admin/editor permissions for node clone, block classes, metatag, reports
  config/install/user.role.az_content_admin.yml
  config/install/user.role.az_content_editor.yml
  modules/custom/az_core/src/Form/QuickstartCoreSettingsForm.php
Labels: enhancement, 2.3.x only

#1536 Fixes #1535 Allow subthemes to override paragraphs and alphabetical listing.
  modules/custom/az_alphabetical_listing/az_alphabetical_listing.module
  modules/custom/az_paragraphs/az_paragraphs.module
Labels: bug, patch release

#1420 Closes #1500 Feature display mode for the news feature
  modules/custom/az_core/config/install/core.entity_view_mode.node.az_feature.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_feature.yml
Labels: documentation, enhancement, 2.3.x only

#1526 Closes #1207 - Change card breakpoints to match Bootstrap 4 (break sooner)
  modules/custom/az_paragraphs/az_paragraphs.install
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZCardsParagraphBehavior.php
Labels: bug, enhancement, 2.3.x only

#1300 Closes #1299: Adding documentation surrounding developing and applying updates to quickstart sites.
  CONTRIBUTING.md
  README.md
Labels: documentation, backport, patch release

#1473 Closes #1472: Consolidated contrib module updates for 2.3.x
  composer.json
  modules/custom/az_carousel/config/install/slick.optionset.center_mode.yml
  modules/custom/az_media/config/install/image.style.az_card_image.yml
  modules/custom/az_media/config/install/image.style.az_full_width_bg_extra_small.yml
  modules/custom/az_media/config/install/image.style.az_full_width_bg_large.yml
  modules/custom/az_media/config/install/image.style.az_full_width_bg_medium.yml
  modules/custom/az_media/config/install/image.style.az_full_width_bg_small.yml
  modules/custom/az_media/config/install/image.style.az_large.yml
Labels: dependencies, Drupal, 2.3.x only

#1400 Closes #1363 Use navbar_offcanvas_attributes set in .theme file.
  themes/custom/az_barrio/az_barrio.theme
  themes/custom/az_barrio/js/az-barrio-off-canvas-nav.es6.js
  themes/custom/az_barrio/js/az-barrio-off-canvas-nav.js
  themes/custom/az_barrio/templates/layout/page.html.twig
  themes/custom/az_barrio/tests/src/Functional/AzBarrioTest.php
Labels: bug, task, 2.3.x only

#1349 Closes #1348: Remove deprecated ParagraphsBehavior migrate process plugin.
  modules/custom/az_demo/data/az_demo_text_background_paragraph.json
  modules/custom/az_demo/data/az_demo_text_paragraph.json
  modules/custom/az_demo/migrations/az_demo_text_background_paragraph.yml
  modules/custom/az_demo/migrations/az_demo_text_paragraph.yml
  modules/custom/az_migration/README.md
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_headed_text.yml
  modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehavior.php
Labels: migration, 2.3.x only

#1539 Closes #1103: Add new AZ News view displays
  modules/custom/az_news/az_news.info.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_feature.yml
  modules/custom/az_news/config/install/views.view.az_news.yml
Labels: enhancement, 2.3.x only

#1556 Closes #1555: Cleanup existing PHPCS warnings ahead of 2.3.0.
  .probo.yaml
  modules/custom/az_core/src/Form/QuickstartCoreSettingsForm.php
  modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsExtraInfoFieldMerge.php
  modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsFWMediaRowFieldMerge.php
  modules/custom/az_migration/src/Plugin/migrate/process/ViewsReferenceMapping.php
  modules/custom/az_migration/src/Plugin/migrate/source/AZFileHandle.php
  modules/custom/az_migration/src/Plugin/migrate/source/NodeWithFieldCollection.php
  modules/custom/az_paragraphs/src/Plugin/Field/FieldFormatter/AZBackgroundMediaFormatter.php
Labels: task, 2.3.x only

#1516 Fixes #1340 Drupal 9.3 Permissions Updates
  modules/custom/az_core/az_core.module
  modules/custom/az_core/src/AZConfigOverride.php
  modules/custom/az_core/src/Plugin/ConfigProvider/QuickstartConfigProvider.php
Labels: bug, blocker, high priority, 2.3.x only

#1562 #1561: Update composer branch alias for dev-main to 2.4.x-dev.
  composer.json
Labels: backport

#1565 #1561: 2.3.x branch-specific changes for CI configs.
  .ddev/commands/web/install
  .github/workflows/security.yml
  .lando.yml
  .probo.yaml
Labels: task, ci, 2.3.x only

#1571 Closes #1570: Ensure better_exposed_filters module is installed.
  modules/custom/az_news/az_news.install
Labels: bug, high priority, 2.3.x only

#1560 Closes #1559: 2.2.x Backport of minor entity view display fixes from #1181.
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_card.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_marquee.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.default.yml
Labels: bug, 2.2.x only

#1563 Update text in description of crop type `az_full_width_bg_large`
  modules/custom/az_media/config/install/crop.type.az_full_width_bg_large.yml
Labels: backport, patch release

#1588 Closes #1584: Fix sidebar nav top margin calculation
  modules/custom/az_paragraphs/css/az_paragraphs_full_width.css
  modules/custom/az_paragraphs/js/az_paragraphs_full_width.es6.js
  modules/custom/az_paragraphs/js/az_paragraphs_full_width.js
Labels: bug, blocker

#1582 Closes #1581: Remove non-existent permissions from Quickstart roles.
  config/install/user.role.az_content_admin.yml
  config/install/user.role.az_content_editor.yml
Labels: high priority, 2.3.x only

#1578 #1340 Allow Import of Dependent Permissions
  modules/custom/az_core/az_core.services.yml
  modules/custom/az_core/src/AZConfigOverride.php
  modules/custom/az_core/src/Plugin/ConfigProvider/QuickstartConfigProvider.php
Labels: bug, 2.3.x only

#1599 Closes #1598: Update embed to 8.x-1.5 for SA-CONTRIB-2022-042.
  composer.json
Labels: bug, backport, patch release

#1603 #1600: Update Drupal core to 9.2.20 for SA-CORE-2022-010/CVE-2022-29248.
  composer.json
Labels: bug, backport, patch release

#1601 #1600: Drupal core to 9.3.14 for SA-CORE-2022-010/CVE-2022-29248.
  composer.json
Labels: bug, patch release, 2.3.x only

#1608 Closes #1118 - Add Data Studio dashboard link to admin toolbar.
  modules/custom/az_core/az_core.module
Labels: enhancement, 2.4.x only
