Repository az-digital/az_quickstart, pull requests merged in 2022-12, with the labels that each got.

#2044 Closes #2009: Include Quickstart version in az_metrics (when available).
  modules/custom/az_metrics/az_metrics.module
Labels: enhancement, patch release

#1989 Closes #1648 - Convert AZ Person display to Drupal UI
  modules/custom/az_core/config/install/core.entity_view_mode.taxonomy_term.az_badge.yml
  modules/custom/az_core/config/install/smart_title.settings.yml
  modules/custom/az_person/az_person.info.yml
  modules/custom/az_person/config/install/core.entity_view_display.node.az_person.az_card.yml
  modules/custom/az_person/config/install/core.entity_view_display.node.az_person.az_row.yml
  modules/custom/az_person/config/install/core.entity_view_display.node.az_person.default.yml
  modules/custom/az_person/config/install/core.entity_view_display.taxonomy_term.az_person_categories.az_badge.yml
  modules/custom/az_person/config/install/core.entity_view_display.taxonomy_term.az_person_categories_secondary.az_badge.yml
  modules/custom/az_person/css/az_person.css
  themes/custom/az_barrio/css/az-media-display.css
  themes/custom/az_barrio/templates/content/node--az-person--az-card.html.twig
  themes/custom/az_barrio/templates/content/node--az-person--az_row.html.twig
  themes/custom/az_barrio/templates/content/node--az-person--full.html.twig
  themes/custom/az_barrio/templates/field/field--node--field_az_degrees--az_person.html.twig
  themes/custom/az_barrio/templates/field/field--node--field_az_email--az_person.html.twig
  themes/custom/az_barrio/templates/field/field--node--field_az_fname--az_person.html.twig
  themes/custom/az_barrio/templates/field/field--node--field_az_lname--az_person.html.twig
  themes/custom/az_barrio/templates/field/field--node--field_az_person_category--az_person.html.twig
  themes/custom/az_barrio/templates/field/field--node--field_az_person_category_sec--az_person.html.twig
  themes/custom/az_barrio/templates/field/field--node--field_az_pronouns--az_person.html.twig
Labels: enhancement, QS1 feature parity, 2.6.x only

#1720 Closes #1694: Add granular class selector to search block Submit button
  themes/custom/az_barrio/config/optional/block.block.az_barrio_search.yml
  themes/custom/az_barrio/css/style.css
Labels: low priority, 2.6.x only, needs-CWS-testing

#2086 Fixes #2010 Add calendar cell information to non-view paths.
  modules/custom/az_event/js/az_calendar_filter.es6.js
  modules/custom/az_event/js/az_calendar_filter.js
  modules/custom/az_event/src/Plugin/views/filter/AZCalendarFilter.php
Labels: bug, enhancement, accessibility, 2.6.x only
