Repository az-digital/az_quickstart, pull requests merged in 2022-11, with the labels that each got.

#2024 Closes #2023 - Add `HTML administrator` role and shift permissions
  .probo.yaml
  config/install/user.role.administrator.yml
  config/install/user.role.az_content_admin.yml
  config/install/user.role.az_html_admin.yml
Labels: bug, enhancement, high priority, 2.6.x only

#2034 Closes #2031 - Fix unusable row weights in reorder view
  composer.json
Labels: bug, backport, patch release, accessibility

#2038 Closes #2035 - Include notice that "reordering overrides alphabetical sorting"
  modules/custom/az_person/config/install/views.view.az_reorder.yml
Labels: documentation, backport, patch release

#2040 Closes #1695: Replaced drush en with drush install
  .github/workflows/review-site.yml
  .probo.yaml
  modules/custom/az_migration/README.md
Labels: enhancement, backport, ci, patch release

#2033 Closes #2032: Move Event subtitle below title on default display
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.default.yml
Labels: enhancement, visual change, 2.6.x only

#2046 Closes #2045: Add patch for Drupal core PHP 8.1 deprecation errors affecting status report.
  composer.json
Labels: bug, backport, dependencies, Drupal, patch release

#2063 Closes #2062: Skip migrate processing for event link field values if missing.
  modules/custom/az_migration/migrations/az_node_event.yml
Labels: bug, migration, patch release

#2056 #1917 AZ News: Add read more text to imported news content to denote an external link.
  modules/custom/az_news/az_news_feeds/config/install/migrate_plus.migration.az_news_feed_stories.yml
Labels: enhancement, QS1 feature parity, 2.6.x only, needs-CWS-testing
