Repository az-digital/az_quickstart, pull requests merged in 2022-04, with the labels that each got.

#1442 Fixes #1438: Add patch for AP Style Date module time display issue
  composer.json
Labels: bug, top priority, patch release

#1431 Closes #1426: Change default CAS hostname to shibboleth.arizona.edu
  modules/custom/az_cas/config/quickstart/cas.settings.yml
  modules/custom/az_core/tests/src/Functional/ConfigOverrideTest.php
Labels: bug, task, patch release

#1434 Closes #1433 Fix alignment and label issues with Quickstart Select Menu
  modules/custom/az_select_menu/css/az-select-menu.css
  modules/custom/az_select_menu/templates/az-select-menu.html.twig
Labels: bug, patch release

#1455 Closes #1454: Add steps to test to PR template.
  .github/pull_request_template.md
Labels: documentation, backport, patch release

#1451 Closes #1302: Fix AZ News Feed if <30 stories match configured tag(s).
  modules/custom/az_news/az_news_feeds/src/EventSubscriber/AzNewsFeedsMigrateSubscriber.php
  modules/custom/az_news/az_news_feeds/src/Form/AzNewsFeedsAdminForm.php
Labels: bug, backport, patch release

#1440 Closes #1394: Updating views re-order notice blocks to use render arrays and Url::fromRoute.
  modules/custom/az_carousel/src/Plugin/Block/AZCarouselNotice.php
  modules/custom/az_person/src/Plugin/Block/AZPersonReorderNotice.php
Labels: bug, patch release

#1458 Closes #986: Strip HTML tags from Person address field during migration.
  modules/custom/az_migration/migrations/migrate_plus.migration.az_node_person.yml
Labels: bug, backport, high priority, migration, patch release

#1109 Closes #880: Add new ViewsReferenceMapping process plugin with views argument lookup handling.
  modules/custom/az_migration/README.md
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_chucks_view.yml
  modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsChunksViewDisplayMapping.php
  modules/custom/az_migration/src/Plugin/migrate/process/ViewsReferenceMapping.php
Labels: enhancement, migration, 2.3.x only

#1470 Closes #1366 Allow upgrade of smart_date and fix demo menu links migration.
  composer.json
  modules/custom/az_demo/data/az_demo_event_node.json
  modules/custom/az_demo/migrations/az_demo_event_node.yml
  modules/custom/az_demo/migrations/az_demo_menu_links.yml
Labels: bug, backport, patch release

#1461 Closes #1322: Add core patch to fix issue with CKEditor fields not always saving.
  composer.json
Labels: bug, backport, high priority, Drupal, patch release

#1464 az-digital/az-icons#17: Update icon font with vimeo icon
  themes/custom/az_barrio/libraries/az-icons/.gitignore
  themes/custom/az_barrio/libraries/az-icons/az-icons-styles.css
  themes/custom/az_barrio/libraries/az-icons/fonts/az-icons.eot
  themes/custom/az_barrio/libraries/az-icons/fonts/az-icons.svg
  themes/custom/az_barrio/libraries/az-icons/fonts/az-icons.ttf
  themes/custom/az_barrio/libraries/az-icons/fonts/az-icons.woff
  themes/custom/az_barrio/libraries/az-icons/png/Icon 
  themes/custom/az_barrio/libraries/az-icons/png/pinterest.png
  themes/custom/az_barrio/libraries/az-icons/png/vimeo.png
  themes/custom/az_barrio/libraries/az-icons/svg/vimeo.svg
Labels: bug, backport, patch release

#1469 Closes 1403: Added style for Natural Image behavior
  modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_natural_size.yml
  modules/custom/az_media/config/install/image.style.az_natural.yml
Labels: bug, enhancement, backport, patch release

#1471 Fixes #1460 Allow for Delayed Configuration Overrides.
  modules/custom/az_core/src/AZConfigOverride.php
  modules/custom/az_core/src/Plugin/ConfigProvider/QuickstartConfigProvider.php
  modules/custom/az_security/az_security.install
Labels: bug, backport, high priority, patch release

#1482 Closes #1481: Increase soft limit widths to 1920px for az_full_width_bg_large image style.
  modules/custom/az_media/config/install/crop.type.az_full_width_bg_large.yml
  modules/custom/az_media/config/install/image.style.az_full_width_bg_large.yml
Labels: bug, backport, patch release

#1485 Closes #1484: Provide default Antibot module config overrides in Quickstart Security module.
  modules/custom/az_security/config/quickstart/antibot.settings.yml
Labels: enhancement, backport, patch release

#1383 Add info about PHPStan to contributing document.
  CONTRIBUTING.md
Labels: documentation, backport, patch release

#1286 #1280: Add some functional tests to check that modules can be uninstalled and reinstalled without errors.
  modules/custom/az_global_footer/tests/src/Functional/AzGlobalFooterTest.php
  modules/custom/az_select_menu/tests/src/Functional/AzSelectMenuTest.php
Labels: enhancement, ci, dependencies, 2.3.x only

#1499 Closes #1498: Update eslint and prettier
  .eslintrc.json
  .prettierignore
  .prettierrc.json
  modules/custom/az_alphabetical_listing/js/alphabetical_listing.es6.js
  modules/custom/az_alphabetical_listing/js/alphabetical_listing.js
  modules/custom/az_event/js/az_calendar_filter.es6.js
  modules/custom/az_event/js/az_calendar_filter.js
  modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_youtube.es6.js
  modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_youtube.js
  modules/custom/az_paragraphs/js/az_paragraphs_full_width.es6.js
  modules/custom/az_paragraphs/js/az_paragraphs_full_width.js
  modules/custom/az_select_menu/js/az-select-menu.es6.js
  modules/custom/az_select_menu/js/az-select-menu.js
  package.json
Labels: enhancement, 2.3.x only

#1503 Closes #1501: Add environment_indicator module.
  .probo.yaml
  az_quickstart.install
  composer.json
  config/install/user.role.az_content_editor.yml
Labels: enhancement, backport, patch release
