Repository az-digital/az_quickstart, pull requests merged in 2022-10, with the labels that each got.

#1975 Closes #1974 Move ArrayIntersect migrate process plugin into az_core from az_news_feeds.
  modules/custom/az_core/src/Plugin/migrate/process/ArrayIntersect.php
Labels: enhancement, migration, 2.6.x only

#1977 Closes #1976 Add bottom spacing options to contact paragraphs
  modules/custom/az_paragraphs/az_paragraphs_contact/config/install/paragraphs.paragraphs_type.az_contact.yml
Labels: bug, enhancement, 2.5.x only

#1981 Closes #1963: Add bootstrap_barrio patch for node template contextual menu issue.
  composer.json
Labels: bug, QS1 feature parity, 2.6.x only

#1990 Closes #408, Closes #1449 Remove reorder people block and add contextual links.
  composer.json
  modules/custom/az_person/az_person.install
  modules/custom/az_person/config/install/views.view.az_reorder.yml
  modules/custom/az_person/config/optional/block.block.az_person_reorder_notification.yml
  modules/custom/az_person/src/Plugin/Block/AZPersonReorderNotice.php
Labels: bug, documentation, backport, patch release

#1948 Closes #1913, Closes #1997 Update az_custom_menu_block title style and fix demo content where the card deck page shows menu blocks.
  modules/custom/az_block_types/az_custom_menu_block/az_custom_menu_block.module
  modules/custom/az_demo/data/az_demo_block_content_block.json
  modules/custom/az_demo/data/az_demo_page_node.json
  modules/custom/az_demo/data/az_demo_splitscreen_paragraph.json
  modules/custom/az_demo/data/az_demo_text_paragraph.json
Labels: bug, backport, patch release, visual change

#2003 Closes #2002: Fix memory leak in core to improve stability of migrations.
  composer.json
Labels: bug, backport, dependencies, migration, Drupal

#2004 Update PR template formatting
  .github/pull_request_template.md
Labels: task

#1966 Closes #1552 AZ News: Update view mode displays to allow editing the "Read More" text for links
  modules/custom/az_core/az_core.module
  modules/custom/az_demo/data/az_demo_news_node.json
  modules/custom/az_demo/migrations/az_demo_news_node.yml
  modules/custom/az_news/az_news.module
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_card.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_feature.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_marquee.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_media_list.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_medium_media_list.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_minimal_media_list.yml
  modules/custom/az_news/config/install/field.field.node.az_news.field_az_link.yml
Labels: enhancement, QS1 feature parity, 2.6.x only

#2026 Closes #2025 - Enable all views options on views paragraphs
  modules/custom/az_paragraphs/az_paragraphs_view/config/install/field.field.paragraph.az_view_reference.field_az_view_reference.yml
Labels: enhancement, 2.6.x only
