Repository az-digital/az_quickstart, pull requests merged in 2022-03, with the labels that each got.

#1325 Closes #1306: Update PR template for better alignment with our minor/patch release definitions
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/pull_request_template.md
Labels: documentation, patch release

#1347 Closes #1344 Migration: Extra (blank) Text Boxes are showing up
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_flexible_page_sub.yml
Labels: bug, backport, migration, patch release

#1353 Closes #1208: Added classes to page template depending on contents of off-canvas-nav
  themes/custom/az_barrio/css/az-barrio-off-canvas-nav.css
  themes/custom/az_barrio/templates/layout/page.html.twig
Labels: bug, backport, patch release

#1321 Fixes #756 Embedded Entity Migration
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_headed_text.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_html.yml
  modules/custom/az_migration/src/Plugin/migrate/process/EntityEmbedProcess.php
Labels: bug, enhancement, backport, migration, patch release

#1362 Fixes #1361 NodeWithFieldCollection source plugin not accessible.
  modules/custom/az_migration/src/Plugin/migrate/source/NodeWithFieldCollection.php
Labels: bug, backport, migration, patch release

#1337 Closes #1336: Add antibot module to az_security
  composer.json
  config/install/user.role.authenticated.yml
  modules/custom/az_security/az_security.install
Labels: enhancement

#1355 Fixes #1354 Lando database doesn't play nicely with M1 Mac.
  .lando.yml
Labels: bug, backport, patch release

#1360 Closes #1331: Make sidebar not overlap text for Text with Background
  modules/custom/az_paragraphs/css/az_paragraphs_az_text_media.css
  modules/custom/az_paragraphs/css/az_paragraphs_full_width.css
Labels: bug, backport, high priority, patch release

#1351 Closes #1350: Implement more flexible update hook numbering scheme.
  RELEASES.md
  az_quickstart.install
  az_quickstart.profile
Labels: enhancement, blocker, high priority, 2.1.x only, no backport, patch release

#1352 #1350: 2.0.x backport of flexible update hook numbering scheme implementation.
  RELEASES.md
  az_quickstart.install
  az_quickstart.profile
Labels: enhancement, backport, 2.0.x only, high priority

#1258 Jan 2022 Consolidated contrib module updates.
  composer.json
Labels: dependencies

#1334 Closes #1333: Configure system mail interface to use SMTP during install.
  modules/custom/az_mail/az_mail.install
Labels: bug, backport, patch release

#1332 Closes #1317: Add update hook to delete problematic legacy global footer menu blocks.
  az_quickstart.install
  modules/custom/az_global_footer/README.md
Labels: bug, high priority, 2.1.x only, no backport, patch release

#1372 Closes #1371: Add az prefix to EntityEmbedProcess migrate plugin ID.
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_headed_text.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_html.yml
  modules/custom/az_migration/src/Plugin/migrate/process/EntityEmbedProcess.php
Labels: enhancement, 2.2.x only

#1345 Closes #892: Reduce paragraphs behavior settings migrate plugin complexity
  modules/custom/az_demo/data/az_demo_text_media_paragraph.json
  modules/custom/az_demo/migrations/az_demo_text_media_paragraph.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_callout.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_card_deck.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_carousel.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_chucks_view.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_column_image.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_content_marquee.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_extra_info.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_file_download.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_flexible_page_sub.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_full_width_bg_wrapper.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_full_width_media_row.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_gallery.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_html.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_jumbotron.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_panel_group.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_plain_text.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_single_card.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_well.yml
  modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehavior.php
  modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehaviorSettings.php
Labels: enhancement, migration, 2.2.x only

#1377 #1367: Update composer branch alias for dev-main to 2.3.x-dev
  composer.json
Labels: backport, ci, patch release

#1378 #1367: 2.2.x branch-specific changes for CI configs.
  .ddev/commands/web/install
  .github/workflows/security.yml
  .lando.yml
  .probo.yaml
Labels: ci, 2.2.x only

#1393 Fixes #1384 Global Footer (after 2.2 Update) Formatting Incorrect
  themes/custom/az_barrio/templates/layout/page.html.twig
Labels: bug, backport, high priority, patch release

#1392 Closes #1390 by setting maxlength of Card Link URL field to 2048 characters
  modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php
Labels: bug, backport, patch release

#1398 Fixes #1397 Update migrations to add text_media_spacing default and change bg_attach to bg_attachment
  modules/custom/az_demo/migrations/az_demo_text_media_paragraph.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_content_marquee.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_full_width_media_row.yml
Labels: bug, migration, no backport, patch release

#877 Closes #876: Enable testing of related az-quickstart-dev branches in main repo CI builds.
  .ddev/commands/web/install
  .github/workflows/security.yml
  .lando.yml
  .probo.yaml
Labels: enhancement, backport, ci

#1417 Fixes #1415: Add required default_theme property to all tests.
  modules/custom/az_core/tests/src/Functional/ConfigOverrideTest.php
  modules/custom/az_demo/tests/src/Functional/AZDemoContentTest.php
  modules/custom/az_paragraphs/tests/src/Functional/AZParagraphsTest.php
  modules/custom/az_paragraphs/tests/src/FunctionalJavascript/AZParagraphsJavascriptTest.php
Labels: bug, ci, high priority, patch release

#1422 Closes #1421: Update Drupal core to 9.2.16 for SA-CORE-2022-006.
  composer.json
Labels: bug, dependencies, high priority, Drupal, patch release

#915 Closes #595: Add az_security module
  composer.json
  modules/custom/az_security/config/quickstart/seckit.settings.yml
Labels: enhancement, hacktoberfest-accepted, backport

#1312 Closes #1311: Default XDebug config for VS Code
  .lando.yml
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/php.ini
  README.md
Labels: enhancement, ci, patch release

#1423 Closes #396 Updated CKEditor icons for embed buttons
  modules/custom/az_paragraphs/config/optional/embed.button.az_embed_content.yml
  modules/custom/az_paragraphs/config/optional/embed.button.az_embed_content_block.yml
Labels: bug, enhancement

#1416 Fixes #1232 Optionally add html paragraphs to migration lookup, and remove contacts from page migration.
  .probo.yaml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_node_flexible_page.yml
Labels: bug, backport, migration, patch release

#1411 Closes #1231: Migrate front page
  modules/custom/az_migration/migrations/az_site_frontpage.yml
Labels: bug, backport, migration, patch release

#1419 Closes #1133 Adding required markup for subhead and moving to the top of flexible page migration.
  modules/custom/az_migration/migrations/migrate_plus.migration.az_node_flexible_page.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_flexible_page_sub.yml
Labels: bug, backport, migration, patch release
