Repository az-digital/az_quickstart, pull requests merged in 2022-08, with the labels that each got.

#1804 Closes #1803: Allow more open dependabot PRs.
  .github/dependabot.yml
Labels: enhancement, dependencies

#1798 Closes #1523 use az_entity_embed_process before passing to text_format_recognizer
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_html.yml
Labels: bug, backport, migration, patch release

#1833 Closes #177 - Adds masquerade module
  composer.json
Labels: enhancement, patch release, QS1 feature parity

#1840 Closes #1839 Add entity_embed_process plugin to field_az_text_area in az_paragraph_html migration.
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_html.yml
Labels: bug, backport, migration, patch release

#1846 Closes #1844 - Fix twig variable index for alt text on gallery images
  modules/custom/az_paragraphs/az_paragraphs_photo_gallery/templates/paragraph--az-photo-gallery.html.twig
Labels: bug, backport, high priority, patch release, accessibility

#1842 Closes #1841: "Downgrade" ctools to 8.x-3.11.
  composer.json
Labels: bug, backport, dependencies, Drupal, patch release

#1821 Closes #1820: Update Drupal core to 9.3.21 (2.3.x only).
  composer.json
Labels: dependencies, Drupal, 2.3.x only

#1849 Closes #1848: Fix PHPstan errors since updating to phpstan-drupal 1.1.25.
  modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php
Labels: bug, backport, ci, patch release

#1857 Closes #1856: Fix deprecation warning caused by empty card/accordion body fields on PHP 8.1+.
  modules/custom/az_accordion/src/Plugin/Field/FieldFormatter/AZAccordionDefaultFormatter.php
  modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php
Labels: bug, backport, patch release

#1796 Fixes #515 Version indicator changes
  modules/custom/az_core/az_core.module
Labels: enhancement, low priority, 2.5.x only

#1843 Closes #1534 Adding multi-byte character support to EntityEmbedProcess migrate plugin.
  modules/custom/az_migration/src/Plugin/migrate/process/EntityEmbedProcess.php
Labels: bug, migration

#1836 Closes #397 - Add linkit module
  composer.json
  modules/custom/az_core/az_core.info.yml
  modules/custom/az_core/az_core.install
  modules/custom/az_core/config/install/image.style.az_tiny_thumbnail.yml
  modules/custom/az_core/config/install/linkit.linkit_profile.az_linkit.yml
  modules/custom/az_media/az_media.info.yml
  modules/custom/az_media/config/install/filter.format.az_standard.yml
  modules/custom/az_paragraphs/config/optional/editor.editor.az_standard.yml
Labels: enhancement, 2.5.x only

#1800 Closes #1674 Fix up links in migrations
  modules/custom/az_migration/migrations/migrate_plus.migration.az_node_carousel.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_node_event.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_node_news.yml
Labels: bug, migration
