Repository az-digital/az_quickstart, pull requests merged in 2022-06, with the labels that each got.

#1629 Closes #1627 Skip az_paragraphs update if there are no paragraphs.
  modules/custom/az_paragraphs/az_paragraphs.install
Labels: bug, high priority, top priority, 2.3.x only

#1635 Closes #1634: Fix invalid count comparisons in existing hook_update_N() implementations.
  modules/custom/az_paragraphs/az_paragraphs_text_background/az_paragraphs_text_background.install
  modules/custom/az_paragraphs/az_paragraphs_text_media/az_paragraphs_text_media.install
Labels: bug, backport, patch release

#1624 Closes #1443 - Add bg-white to accordion's card-body
  modules/custom/az_accordion/templates/az-accordion.html.twig
Labels: bug, backport, patch release

#1633 Closes #1630: Change demo content email addresses to @arizona.edu
  modules/custom/az_demo/data/az_demo_person_node.json
Labels: bug, backport, low priority

#1545 Closes #1544: Add workaround and patch for Paragraphs 1.14 migrate plugin issues.
  composer.json
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_callout.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_card_deck.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_carousel.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_chucks_view.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_column_image.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_content_marquee.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_extra_info.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_file_download.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_full_width_bg_wrapper.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_full_width_media_row.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_gallery.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_headed_text.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_html.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_jumbotron.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_panel_group.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_plain_text.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_single_card.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_well.yml
Labels: bug, dependencies, migration, patch release, 2.3.x only

#1625 Closes #1071, #1621: Use noConflict() method to fix Bootstrap/jQuery UI conflict breaking dialog close icons.
  modules/custom/az_paragraphs/az_paragraphs.libraries.yml
  themes/custom/az_barrio/az_barrio.libraries.yml
  themes/custom/az_barrio/js/button-no-conflict.es6.js
  themes/custom/az_barrio/js/button-no-conflict.js
Labels: bug, patch release

#1644 Closes #1643 Ensure Migrate Magician is enabled
  modules/custom/az_migration/az_migration.install
Labels: bug, patch release, 2.3.x only

#1488 Adds a source migration plugin that filters out old content
  modules/custom/az_migration/src/Plugin/migrate/source/AZNode.php
Labels: enhancement, backport, migration

#1653 Closes #1513: Changes az_barrio style library setting to theme.
  themes/custom/az_barrio/az_barrio.libraries.yml
Labels: bug, 2.4.x only

#1661 Security Issue #1660 Update Drupal core to 9.3.16 for SA-CORE-2022-011
  composer.json
Labels: high priority, 2.3.x only

#1662 Security Issue #1660 Update Drupal core to 9.2.21 for SA-CORE-2022-011
  composer.json
Labels: high priority, 2.2.x only

#1655 Closes #746: Adds bottom margin to Person, News, Events
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.default.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.default.yml
  themes/custom/az_barrio/templates/content/node--az-person--full.html.twig
Labels: enhancement, 2.4.x only

#1628 Closes #1328: Truncate long emails on card displays of AZ Person
  modules/custom/az_person/config/install/field.field.node.az_person.field_az_email.yml
  themes/custom/az_barrio/templates/content/node--az-person--az-card.html.twig
Labels: bug, low priority

#1642 Fixes #1626 Add calendar category filter
  modules/custom/az_event/az_event.module
  modules/custom/az_event/config/install/views.view.az_events.yml
  modules/custom/az_event/css/az_calendar_filter.css
  modules/custom/az_event/js/az_calendar_filter.es6.js
  modules/custom/az_event/js/az_calendar_filter.js
Labels: enhancement, 2.4.x only

#1650 Closes #1623 - Add Split Screen component
  modules/custom/az_demo/az_demo.info.yml
  modules/custom/az_demo/data/az_demo_menu_links.json
  modules/custom/az_demo/data/az_demo_page_node.json
  modules/custom/az_demo/data/az_demo_splitscreen_paragraph.json
  modules/custom/az_demo/migrations/az_demo_page_node.yml
  modules/custom/az_demo/migrations/az_demo_splitscreen_paragraph.yml
  modules/custom/az_paragraphs/az_paragraphs_splitscreen/README.md
  modules/custom/az_paragraphs/az_paragraphs_splitscreen/az_paragraphs_splitscreen.info.yml
  modules/custom/az_paragraphs/az_paragraphs_splitscreen/az_paragraphs_splitscreen.libraries.yml
  modules/custom/az_paragraphs/az_paragraphs_splitscreen/az_paragraphs_splitscreen.module
  modules/custom/az_paragraphs/az_paragraphs_splitscreen/config/install/core.entity_form_display.paragraph.az_splitscreen.default.yml
  modules/custom/az_paragraphs/az_paragraphs_splitscreen/config/install/core.entity_view_display.paragraph.az_splitscreen.default.yml
  modules/custom/az_paragraphs/az_paragraphs_splitscreen/config/install/field.field.paragraph.az_splitscreen.field_az_media.yml
  modules/custom/az_paragraphs/az_paragraphs_splitscreen/config/install/field.field.paragraph.az_splitscreen.field_az_text_area.yml
  modules/custom/az_paragraphs/az_paragraphs_splitscreen/config/install/paragraphs.paragraphs_type.az_splitscreen.yml
  modules/custom/az_paragraphs/az_paragraphs_splitscreen/css/az_splitscreen.css
  modules/custom/az_paragraphs/az_paragraphs_splitscreen/templates/paragraph--az-splitscreen--default.html.twig
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZSplitScreenParagraphBehavior.php
  themes/custom/az_barrio/css/style.css
Labels: enhancement, high priority, 2.4.x only

#1692 Closes #1489: Fix media permission denied for authenticated user role.
  config/install/user.role.authenticated.yml
Labels: bug, high priority, patch release

#1681 Closes #1607, Closes #1678: Change disable_login_form functionality, disable login form by default, add link to webauth to login form.
  .probo.yaml
  modules/custom/az_cas/az_cas.module
  modules/custom/az_cas/config/install/az_cas.settings.yml
  modules/custom/az_cas/config/quickstart/cas.settings.yml
  modules/custom/az_cas/src/Routing/AzCasRouteSubscriber.php
  modules/custom/az_cas/tests/src/Functional/AzCasAdminSettingsTest.php
  modules/custom/az_cas/tests/src/Functional/AzCasTest.php
  modules/custom/az_core/tests/src/Functional/ClearCacheTest.php
  modules/custom/az_core/tests/src/Functional/MonitoringPageTest.php
  modules/custom/az_core/tests/src/Functional/QuickstartFunctionalTestBase.php
  modules/custom/az_core/tests/src/FunctionalJavascript/QuickstartFunctionalJavascriptTestBase.php
  modules/custom/az_core/tests/src/Traits/AllowDrupalLoginSetupTrait.php
  modules/custom/az_demo/tests/src/Functional/AZDemoContentTest.php
  modules/custom/az_paragraphs/az_paragraphs.info.yml
  modules/custom/az_paragraphs/tests/src/Functional/AZParagraphsTest.php
  modules/custom/az_paragraphs/tests/src/FunctionalJavascript/AZParagraphsJavascriptTest.php
  themes/custom/az_barrio/az_barrio.info.yml
  themes/custom/az_barrio/tests/src/Functional/AzBarrioTest.php
Labels: enhancement, 2.4.x only, QS1 feature parity

#1691 Closes #1690: Update Drupal core to 9.3.17.
  composer.json
Labels: bug, dependencies, high priority, Drupal, patch release, 2.3.x only

#1673 Closes #1476, #1520, #1521 Migrate az_remote_video
  modules/custom/az_migration/README.md
  modules/custom/az_migration/migrations/migrate_plus.migration.az_files.yml
  modules/custom/az_migration/migrations/migrate_plus.migration.az_media.yml
  modules/custom/az_migration/src/Plugin/migrate/process/MediaBundleRecognizer.php
Labels: bug, migration, patch release

#1573 Closes #1566: Prepare Quickstart for Drupal 9.4.x.
  .ddev/config.quickstart.yaml
  .github/workflows/create-release.yml
  .github/workflows/review-site.yml
  .github/workflows/security.yml
  .lando.yml
  .probo.yaml
  composer.json
  modules/custom/az_accordion/src/Plugin/Field/FieldWidget/AZAccordionWidget.php
  modules/custom/az_card/src/AZCardImageHelper.php
  modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php
  modules/custom/az_core/src/Plugin/ConfigProvider/QuickstartConfigProvider.php
  modules/custom/az_media/az_media.module
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZCardsParagraphBehavior.php
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZDefaultParagraphsBehavior.php
Labels: dependencies, Drupal, 2.4.x only

#1709 Closes #1707: Update Terminus and PHP versions in review site GH actions workflow.
  .github/workflows/review-site.yml
Labels: bug, ci
