Repository az-digital/az_quickstart, pull requests merged in 2022-02, with the labels that each got.

#1266 2.1.x branch-specific changes for CI configs.
  .ddev/commands/web/install
  .github/workflows/security.yml
  .lando.yml
  .probo.yaml
Labels: ci, 2.1.x only

#1263 Closes #1262: Make az_barrio alert theme region full-width.
  themes/custom/az_barrio/config/install/az_barrio.settings.yml
  themes/custom/az_barrio/templates/layout/page.html.twig
Labels: bug, enhancement, www gap

#1270 Fixes #1265: Redirect Migration Status Code Fix
  modules/custom/az_migration/migrations/az_redirects.yml
Labels: bug, backport, migration

#1271 Fix module name in az_metrics.services.yml
  modules/custom/az_metrics/az_metrics.services.yml
Labels: bug, backport

#1261 Closes #1260: Views grouped exposed taxonomy term filters do not work
  composer.json
Labels: bug, backport

#1259 Closes #576 Add dropdown select menu block
  modules/custom/az_select_menu/az_select_menu.info.yml
  modules/custom/az_select_menu/az_select_menu.libraries.yml
  modules/custom/az_select_menu/az_select_menu.module
  modules/custom/az_select_menu/config/schema/az_select_menu.schema.yml
  modules/custom/az_select_menu/css/az-select-menu.css
  modules/custom/az_select_menu/js/az-select-menu.es6.js
  modules/custom/az_select_menu/js/az-select-menu.js
  modules/custom/az_select_menu/src/Plugin/Block/AzSelectMenu.php
  modules/custom/az_select_menu/templates/az-select-menu.html.twig
Labels: documentation, enhancement, blocker, www gap

#1269 Closes #1268: Dropping Drupal 8.x compatibility.
  az_quickstart.info.yml
  modules/custom/az_accordion/az_accordion.info.yml
  modules/custom/az_alphabetical_listing/az_alphabetical_listing.info.yml
  modules/custom/az_block_types/az_block_types.info.yml
  modules/custom/az_block_types/az_block_types_quick_links/az_block_types_quick_links.info.yml
  modules/custom/az_card/az_card.info.yml
  modules/custom/az_carousel/az_carousel.info.yml
  modules/custom/az_cas/az_cas.info.yml
  modules/custom/az_core/az_core.info.yml
  modules/custom/az_demo/az_demo.info.yml
  modules/custom/az_event/az_event.info.yml
  modules/custom/az_flexible_block/az_flexible_block.info.yml
  modules/custom/az_flexible_page/az_flexible_page.info.yml
  modules/custom/az_global_footer/az_global_footer.info.yml
  modules/custom/az_google_tag/az_google_tag.info.yml
  modules/custom/az_mail/az_mail.info.yml
  modules/custom/az_media/az_media.info.yml
  modules/custom/az_metrics/az_metrics.info.yml
  modules/custom/az_migration/az_migration.info.yml
  modules/custom/az_news/az_news.info.yml
  modules/custom/az_news/az_news_feeds/az_news_feeds.info.yml
  modules/custom/az_paragraphs/az_paragraphs.info.yml
  modules/custom/az_paragraphs/az_paragraphs_accordion/az_paragraphs_accordion.info.yml
  modules/custom/az_paragraphs/az_paragraphs_cards/az_paragraphs_cards.info.yml
  modules/custom/az_paragraphs/az_paragraphs_contact/az_paragraphs_contact.info.yml
  modules/custom/az_paragraphs/az_paragraphs_html/az_paragraphs_html.info.yml
  modules/custom/az_paragraphs/az_paragraphs_photo_gallery/az_paragraphs_photo_gallery.info.yml
  modules/custom/az_paragraphs/az_paragraphs_text/az_paragraphs_text.info.yml
  modules/custom/az_paragraphs/az_paragraphs_text_background/az_paragraphs_text_background.info.yml
  modules/custom/az_paragraphs/az_paragraphs_text_media/az_paragraphs_text_media.info.yml
  modules/custom/az_paragraphs/az_paragraphs_view/az_paragraphs_view.info.yml
  modules/custom/az_person/az_person.info.yml
  modules/custom/az_security/az_security.info.yml
  modules/custom/az_select_menu/az_select_menu.info.yml
  modules/custom/az_seo/az_seo.info.yml
  themes/custom/az_barrio/az_barrio.info.yml
Labels: task, dependencies

#1281 Closes #1280 Add block_class as dependency and make az_global_footer a dependency of its config.
  modules/custom/az_global_footer/README.md
  modules/custom/az_global_footer/az_global_footer.info.yml
  modules/custom/az_global_footer/config/install/block.block.az_barrio_footer_menu_info.yml
  modules/custom/az_global_footer/config/install/block.block.az_barrio_footer_menu_main.yml
  modules/custom/az_global_footer/config/install/block.block.az_barrio_footer_menu_resources.yml
  modules/custom/az_global_footer/config/install/block.block.az_barrio_footer_menu_social_media.yml
  modules/custom/az_global_footer/config/install/block.block.az_barrio_footer_menu_topics.yml
Labels: bug, backport, 2.1.x only

#1284 Closes #1283: Update RELEASES.md
  RELEASES.md
Labels: documentation, backport

#1298 Closes #1297: Making global footer match QS1 on mobile
  themes/custom/az_barrio/az_barrio.theme
Labels: bug, www gap, high priority, patch release

#1295 Closes #1293 Make header columns configurable
  az_quickstart.profile
  themes/custom/az_barrio/az_barrio.theme
  themes/custom/az_barrio/config/install/az_barrio.settings.yml
  themes/custom/az_barrio/config/schema/az_barrio.schema.yml
  themes/custom/az_barrio/templates/layout/page.html.twig
  themes/custom/az_barrio/tests/src/Functional/AzBarrioTest.php
  themes/custom/az_barrio/theme-settings.php
Labels: documentation, www gap, high priority, patch release

#1310 Closes #1303: Add Drupal core patch to fix missing az_news_feeds local menu task when content_moderation module not installed.
  composer.json
Labels: bug, patch release

#1308 Closes #1307: Allow unpublishing of published content and allow the latest revision to be a draft.
  config/install/user.role.az_content_admin.yml
  config/install/user.role.az_content_editor.yml
  config/optional/workflows.workflow.editorial.yml
Labels: bug, backport, patch release

#1277 Closes #1274: Custom Migration Source for Nodes with Field Collections
  modules/custom/az_migration/src/Plugin/migrate/source/NodeWithFieldCollection.php
Labels: enhancement, migration

#1324 Closes #1323: Updated Drupal core to 9.2.13 for SA-CORE-2022-003 & SA-CORE-2022-004.
  composer.json
Labels: bug, backport, Drupal, patch release

#1320 Closes #682: Added Better Exposed Filters module.
  composer.json
Labels: enhancement, backport, patch release

#1314 Closes #1296: Use views label instead of rendered views inside paragraph previews.
  composer.json
  modules/custom/az_paragraphs/az_paragraphs_view/config/install/core.entity_view_display.paragraph.az_view_reference.preview.yml
Labels: bug, backport, Drupal, patch release

#1335 Closes #739 - Accordions should match Bootstrap
  modules/custom/az_accordion/templates/az-accordion.html.twig
Labels: bug, backport, patch release

#1279 Closes #1278: Refactoring ParagraphMappingFlexiblePage Class
  modules/custom/az_migration/src/Plugin/migrate/process/ParagraphMappingFlexiblePage.php
Labels: bug, backport, migration, patch release

#1226 Closes #1225: Removing setting the class array as a string everywhere, and fixing bottom spacing issue.
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZDefaultParagraphsBehavior.php
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithMediaParagraphBehavior.php
  themes/custom/az_barrio/az_barrio.theme
Labels: bug, backport, patch release

#1315 Closes #1309 Adding quick node clone
  composer.json
Labels: documentation, enhancement, backport, patch release

#1319 Closes #960: Adding exclude_node_title per node setting migration.
  modules/custom/az_migration/README.md
  modules/custom/az_migration/migrations/az_exclude_node_title.yml
  modules/custom/az_migration/src/Plugin/migrate/source/AZNode.php
Labels: migration, 2.1.x only

#1342 Closes #1341: fix line break issues with names in AZ Person Grid View
  themes/custom/az_barrio/templates/content/node--az-person--az-card.html.twig
  themes/custom/az_barrio/templates/content/node--az-person--az_row.html.twig
  themes/custom/az_barrio/templates/content/node--az-person--full.html.twig
Labels: bug, backport, patch release
