Repository az-digital/az_quickstart, pull requests merged in 2023-07, with the labels that each got.

#2435 Closes #2433 Add users to ManualMigrationLookup
  modules/custom/az_core/src/Plugin/migrate/process/ManualMigrationLookup.php
Labels: enhancement, migration, patch release

#2577 Closes #2576 Line breaks converted to HTML in embedded entities
  modules/custom/az_media/config/install/filter.format.az_standard.yml
Labels: bug, 2.7.x only

#2571 Closes #2570 Adding update to install az_curated_views
  modules/custom/az_publication/az_publication.install
Labels: bug, 2.7.x only

#2447 Closes #2446 Allow CKEditor5 to use arizona-bootstrap CSS
  themes/custom/az_barrio/az_barrio.info.yml
Labels: enhancement, Drupal, editor experience

#2605 Closes #2604 Change port number in az_mail module from 587 to 2587
  modules/custom/az_mail/config/quickstart/smtp.settings.yml
Labels: bug, backport, patch release

#2590 Initial view displays and content type displays
  modules/custom/az_core/config/install/core.entity_view_mode.node.az_row_with_background.yml
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_row_with_background.yml
  modules/custom/az_event/config/install/views.view.az_events.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_row_with_background.yml
  modules/custom/az_news/config/install/views.view.az_news.yml
Labels: enhancement

#2555 Fixes #2524 Author Entity Autolabel Length
  modules/custom/az_publication/az_publication.install
  modules/custom/az_publication/src/Entity/AZAuthor.php
Labels: bug, high priority, patch release, 2.7.x only

#2618 Closes #2617 Remove the back slash from the analytics dashboard link
  modules/custom/az_google_tag/az_google_tag.module
Labels: bug, backport, patch release
