Repository az-digital/az_quickstart, pull requests merged in 2023-04, with the labels that each got.

#2311 Closes #1528: Allow users to replace files, also rename files through re-upload
  az_quickstart.info.yml
  az_quickstart.install
  composer.json
  modules/custom/az_media/az_media.info.yml
  modules/custom/az_media/config/install/core.entity_form_display.media.az_document.default.yml
Labels: enhancement, editor experience, 2.7.x only

#2285 Documentation: Update various pre-migration suggestions to include checking pathauto settings
  modules/custom/az_migration/README.md
Labels: documentation, migration, patch release

#2271 Closes #2265 Add manual migration lookup process plugin for migrate.
  modules/custom/az_core/src/Plugin/migrate/process/ManualMigrationLookup.php
  modules/custom/az_migration/README.md
Labels: enhancement, migration, patch release

#2343 Closes #2341: Enable use of description on Person's CV field
  modules/custom/az_person/config/install/field.field.node.az_person.field_az_attachments.yml
Labels: bug, patch release

#2344 Closes #2342: Change links to chili on Event displays
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_card.yml
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_row.yml
Labels: bug, patch release

#2351 Closes #2350: Update Drupal core to 9.4.14 for SA-CORE-2023-005 (2.5.x only)
  composer.json
Labels: dependencies, high priority, Drupal, patch release, 2.5.x only

#2379 Fixes #2378 Academicpuma/locales abandoned
  composer.json
Labels: bug, high priority, patch release

#2369 Closes #2368 Add option to move Sidebar First region below page content on mobile
  themes/custom/az_barrio/az_barrio.theme
  themes/custom/az_barrio/theme-settings.php
Labels: enhancement, QS1 feature parity, 2.7.x only

#2373 Closes #2371: Transform IDs in both source and destination paths for migrated redirects.
  modules/custom/az_migration/migrations/az_redirects.yml
Labels: bug, migration, patch release

#2316 Fixes #2313 Update Citation Style Configuration
  composer.json
  modules/custom/az_publication/az_publication.module
  modules/custom/az_publication/config/install/az_publication.az_citation_style.az_ama.yml
  modules/custom/az_publication/config/install/az_publication.az_citation_style.az_apa.yml
  modules/custom/az_publication/config/install/az_publication.az_citation_style.az_bluebook.yml
  modules/custom/az_publication/config/install/az_publication.az_citation_style.az_chicago.yml
  modules/custom/az_publication/config/install/az_publication.az_citation_style.az_ieee.yml
  modules/custom/az_publication/config/install/az_publication.az_citation_style.az_mla.yml
  modules/custom/az_publication/config/schema/az_citation_style.schema.yml
  modules/custom/az_publication/src/Entity/AZQuickstartCitationStyle.php
  modules/custom/az_publication/src/Entity/AZQuickstartCitationStyleInterface.php
  modules/custom/az_publication/src/Form/AZQuickstartCitationStyleForm.php
Labels: enhancement, spike, 2.7.x only
