Repository az-digital/az_quickstart, pull requests merged in 2023-01, with the labels that each got.

#2108 Update config for Drupal 9.5
  config/install/block.block.az_barrio_main_menu.yml
  config/install/block.block.az_utility_links.yml
  config/install/block.block.claro_breadcrumbs.yml
  config/install/block.block.claro_content.yml
  config/install/block.block.claro_help.yml
  config/install/block.block.claro_local_actions.yml
  config/install/block.block.claro_messages.yml
  config/install/block.block.claro_page_title.yml
  config/install/block.block.claro_primary_local_tasks.yml
  config/install/block.block.claro_secondary_local_tasks.yml
  config/install/core.entity_view_display.user.user.compact.yml
  config/install/core.entity_view_display.user.user.default.yml
  config/install/easy_breadcrumb.settings.yml
  config/install/editor.editor.basic_html.yml
  modules/custom/az_cas/config/quickstart/cas.settings.yml
  modules/custom/az_core/config/install/image.style.az_tiny_thumbnail.yml
  modules/custom/az_core/config/install/linkit.linkit_profile.az_linkit.yml
  modules/custom/az_event/config/install/views.view.az_events.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_audio.media_library.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_document.media_library.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_background.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_card_image.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_carousel_item.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_large.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_medium.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_natural_size.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_small.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_square.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_thumbnail.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_image.default.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_image.media_library.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_remote_video.media_library.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_video.media_library.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.default.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.teaser.yml
  modules/custom/az_paragraphs/az_paragraphs_contact/config/install/paragraphs.paragraphs_type.az_contact.yml
  modules/custom/az_paragraphs/config/optional/editor.editor.az_standard.yml
  modules/custom/az_person/config/install/core.entity_view_display.node.az_person.teaser.yml
  themes/custom/az_barrio/config/optional/block.block.az_barrio_branding.yml
  themes/custom/az_barrio/config/optional/block.block.az_barrio_content.yml
  themes/custom/az_barrio/config/optional/block.block.az_barrio_footer.yml
  themes/custom/az_barrio/config/optional/block.block.az_barrio_help.yml
  themes/custom/az_barrio/config/optional/block.block.az_barrio_local_actions.yml
  themes/custom/az_barrio/config/optional/block.block.az_barrio_local_tasks.yml
  themes/custom/az_barrio/config/optional/block.block.az_barrio_messages.yml
  themes/custom/az_barrio/config/optional/block.block.az_barrio_offcanvas_searchform.yml
  themes/custom/az_barrio/config/optional/block.block.az_barrio_page_title.yml
  themes/custom/az_barrio/config/optional/block.block.az_barrio_powered.yml
  themes/custom/az_barrio/config/optional/block.block.az_barrio_sidebar_menu.yml
  themes/custom/az_barrio/config/optional/block.block.exposedformaz_eventspage_1.yml
  themes/custom/az_barrio/config/optional/block.block.views_block__az_events_az_sidebar.yml
  themes/custom/az_barrio/config/optional/block.block.views_block__az_news_az_sidebar.yml
  themes/custom/az_barrio/config/optional/block.block.views_block__az_news_marquee.yml
Labels: 2.6.x only

#2107 #1938: Backportable changes from Drupal 9.5.x compatibility updates.
  modules/custom/az_global_footer/az_global_footer.install
  modules/custom/az_paragraphs/az_paragraphs.install
  modules/custom/az_paragraphs/az_paragraphs_photo_gallery/templates/paragraph--az-photo-gallery.html.twig
  modules/custom/az_paragraphs/az_paragraphs_text_background/az_paragraphs_text_background.install
  modules/custom/az_paragraphs/az_paragraphs_text_media/az_paragraphs_text_media.install
Labels: bug, backport, Drupal, patch release

#1973 Closes #1908: Added Workbench Access module.
  composer.json
  config/install/user.role.az_content_admin.yml
  config/install/user.role.az_content_editor.yml
  config/install/user.role.az_user_admin.yml
Labels: documentation, enhancement, dependencies, patch release

#2131 Fixes #2130 Barrio webform required field issue.
  composer.json
Labels: bug, backport, patch release, accessibility

#2059 Closes #1452: Ensure entity embed process plugin is run on all migrated fields that may contain embeds.
  modules/custom/az_migration/migrations/az_node_carousel.yml
  modules/custom/az_migration/migrations/az_node_event.yml
  modules/custom/az_migration/migrations/az_node_news.yml
  modules/custom/az_migration/migrations/az_node_person.yml
  modules/custom/az_migration/migrations/az_paragraph_callout.yml
  modules/custom/az_migration/migrations/az_paragraph_card_deck.yml
  modules/custom/az_migration/migrations/az_paragraph_content_marquee.yml
  modules/custom/az_migration/migrations/az_paragraph_extra_info.yml
  modules/custom/az_migration/migrations/az_paragraph_full_width_bg_wrapper.yml
  modules/custom/az_migration/migrations/az_paragraph_full_width_media_row.yml
  modules/custom/az_migration/migrations/az_paragraph_jumbotron.yml
  modules/custom/az_migration/migrations/az_paragraph_panel_group.yml
  modules/custom/az_migration/migrations/az_paragraph_plain_text.yml
  modules/custom/az_migration/migrations/az_paragraph_single_card.yml
  modules/custom/az_migration/migrations/az_paragraph_well.yml
Labels: bug, migration, patch release

#2141 Closes #2140 Fix condition for displaying Content Top region in page template
  themes/custom/az_barrio/templates/layout/page.html.twig
Labels: bug, backport, patch release

#2146 Closes #2144: Update Drupal core to 9.4.10 for SA-CORE-2023-001.
  composer.json
Labels: bug, backport, dependencies, high priority, Drupal, patch release

#2153 Closes #2109 adding concurrency key to queue sequential jobs when merging to main.
  .github/workflows/review-site.yml
Labels: enhancement, ci

#2159 Closes #2156, Fixes #2156: Ubuntu 18.04 actions runner is deprecated, update to ubuntu-latest
  .github/workflows/arizona-bootstrap-release.yml
  .github/workflows/create-release.yml
Labels: bug, enhancement, ci

#2161 Closes #2160 Fix ordering of regions on Block Layout page
  themes/custom/az_barrio/az_barrio.info.yml
Labels: bug, enhancement, backport, patch release

#2143 Closes #2139 Update logger_channel object type
  modules/custom/az_core/src/AZConfigOverride.php
Labels: bug, enhancement, backport, patch release

#2164 Closes #2122 Update release policy to cover experimental modules.
  .github/pull_request_template.md
  RELEASES.md
Labels: documentation, enhancement

#2135 Closes #2110 Add Upgrade Status Report Step to Probo.
  .probo.yaml
Labels: enhancement, ci, 2.6.x only

#2172 Closes #2171 Remove unused regions from AZ Barrio page template
  themes/custom/az_barrio/templates/layout/page.html.twig
Labels: bug, 2.6.x only

#2158 Closes #2157: Enable dependabot for GitHub actions workflows.
  .github/dependabot.yml
Labels: task, ci

#2189 Closes #2188 - Category filter exceeds allowed space
  modules/custom/az_event/css/az_calendar_filter.css
Labels: bug, backport, patch release

#2191 Closes #2190 Update workflow files to use major versions
  .github/workflows/create-release.yml
  .github/workflows/review-site.yml
  .github/workflows/security.yml
Labels: enhancement, ci, dependencies
