Repository az-digital/az_quickstart, pull requests merged in 2023-08, with the labels that each got.

#2360 Closes #2327 - Initial Marketing Cloud integration
  modules/custom/az_marketing_cloud/az_marketing_cloud.info.yml
  modules/custom/az_marketing_cloud/az_marketing_cloud.libraries.yml
  modules/custom/az_marketing_cloud/az_marketing_cloud.links.task.yml
  modules/custom/az_marketing_cloud/az_marketing_cloud.module
  modules/custom/az_marketing_cloud/config/install/core.entity_view_display.node.az_news.az_marketing_cloud_30_70_layout.yml
  modules/custom/az_marketing_cloud/config/install/core.entity_view_display.node.az_news.az_marketing_cloud_50_50_layout.yml
  modules/custom/az_marketing_cloud/config/install/core.entity_view_display.node.az_news.az_marketing_cloud_text_layout.yml
  modules/custom/az_marketing_cloud/config/install/core.entity_view_mode.node.az_marketing_cloud_30_70_layout.yml
  modules/custom/az_marketing_cloud/config/install/core.entity_view_mode.node.az_marketing_cloud_50_50_layout.yml
  modules/custom/az_marketing_cloud/config/install/core.entity_view_mode.node.az_marketing_cloud_text_layout.yml
  modules/custom/az_marketing_cloud/config/install/crop.type.az_marketing_cloud_30_70_layout.yml
  modules/custom/az_marketing_cloud/config/install/crop.type.az_marketing_cloud_50_50_layout.yml
  modules/custom/az_marketing_cloud/config/install/image.style.az_marketing_cloud_30_70_layout.yml
  modules/custom/az_marketing_cloud/config/install/image.style.az_marketing_cloud_50_50_layout.yml
  modules/custom/az_marketing_cloud/config/install/views.view.az_marketing_cloud.yml
  modules/custom/az_marketing_cloud/js/az-marketing-cloud-admin.js
  modules/custom/az_marketing_cloud/templates/block--az-barrio-page-title--az-marketing-cloud.html.twig
  modules/custom/az_marketing_cloud/templates/block--az-marketing-cloud.html.twig
  modules/custom/az_marketing_cloud/templates/container--view--az-marketing-cloud.html.twig
  modules/custom/az_marketing_cloud/templates/html--export--marketing-cloud.html.twig
  modules/custom/az_marketing_cloud/templates/node--view--az-marketing-cloud--30-70-layout.html.twig
  modules/custom/az_marketing_cloud/templates/node--view--az-marketing-cloud--50-50-layout.html.twig
  modules/custom/az_marketing_cloud/templates/node--view--az-marketing-cloud--text-layout.html.twig
  modules/custom/az_marketing_cloud/templates/page--export--marketing-cloud.html.twig
  modules/custom/az_marketing_cloud/templates/region--az-marketing-cloud.html.twig
  modules/custom/az_marketing_cloud/templates/views-view--az-marketing-cloud.html.twig
  modules/custom/az_marketing_cloud/templates/views-view-unformatted--az-marketing-cloud.html.twig
  modules/custom/az_media/config/install/core.entity_form_display.media.az_image.default.yml
  modules/custom/az_media/config/install/core.entity_form_display.media.az_image.media_library.yml
Labels: enhancement, Integrations, 2.7.x only, trellis

#2454 Closes #2413 Change field label for 'main content' field to match documentation.
  modules/custom/az_flexible_block/config/install/field.field.block_content.az_flexible_block.field_az_main_content.yml
  modules/custom/az_flexible_page/config/install/field.field.node.az_flexible_page.field_az_main_content.yml
  modules/custom/az_news/config/install/field.field.node.az_news.field_az_main_content.yml
Labels: editor experience, user experience, needs discussion, 2.8.x only

#2651 Closes #2644: Marketing Cloud module initial feedback
  modules/custom/az_marketing_cloud/az_marketing_cloud.module
  modules/custom/az_marketing_cloud/config/install/views.view.az_marketing_cloud.yml
Labels: patch release, trellis

#2657 Closes #2656: Switch back to d.o. version of background_image_formatter module.
  composer.json
Labels: task, dependencies, patch release

#2660 #2614 Update config_distro and config_sync for Drush 12 compatibility.
  composer.json
Labels: dependencies, patch release

#2226 Fixes #2212 Adding a README for our add-permissions drush command
  modules/custom/az_core/src/Commands/README.md
Labels: documentation, needs discussion

#2664 Closes #2663 - Allow multiple access schemes with Workbench Access
  composer.json
Labels: bug, dependencies, patch release

#2620 Fixes #2619 News export API empty value handling
  modules/custom/az_news/az_news_export/az_news_export.services.yml
  modules/custom/az_news/az_news_export/src/AZNewsDataEmpty.php
  modules/custom/az_news/az_news_export/src/Normalizer/AZNewsDataEmptyNormalizer.php
  modules/custom/az_news/az_news_export/src/Plugin/views/row/AZNewsDataFieldRow.php
Labels: enhancement, patch release, Integrations, 2.7.x only, needs discussion, trellis

#2678 Closes #2677: Fix broken Google Tag config upgrade.
  composer.json
  modules/custom/az_google_tag/config/install/google_tag.container.az_comprehensive.yml
Labels: bug, high priority, top priority, patch release

#2681 Fixes #2680 News Content Topic and Audiences Attributes only
  modules/custom/az_news/config/install/core.entity_form_display.node.az_news.default.yml
  modules/custom/az_seo/config/quickstart/core.entity_form_display.node.az_news.default.yml
Labels: patch release, Integrations, 2.7.x only, news, trellis

#2673 Closes #2549 remove horizontal scroll in mobile browsers when off canvas nav buttons appear on the page.
  themes/custom/az_barrio/css/az-barrio-off-canvas-nav.css
  themes/custom/az_barrio/templates/layout/page.html.twig
Labels: bug, backport, patch release, user experience

#2666 Closes #2645: Add events to Quickstart for Marketing Cloud module
  modules/custom/az_marketing_cloud/az_marketing_cloud.info.yml
  modules/custom/az_marketing_cloud/az_marketing_cloud.module
  modules/custom/az_marketing_cloud/config/install/core.entity_view_display.node.az_event.az_marketing_cloud_event_layout.yml
  modules/custom/az_marketing_cloud/config/install/core.entity_view_mode.node.az_marketing_cloud_event_layout.yml
  modules/custom/az_marketing_cloud/config/install/views.view.az_marketing_cloud.yml
  modules/custom/az_marketing_cloud/templates/node--view--az-marketing-cloud--event-layout.html.twig
Labels: enhancement, Integrations, trellis

#2684 Closes #2683: Update Campus Safety link in Global footer
  modules/custom/az_global_footer/az_global_footer.install
  modules/custom/az_global_footer/data/az_global_footer.json
Labels: backport, patch release
