Repository az-digital/az_quickstart, pull requests merged in 2023-09, with the labels that each got.

#2682 Closes #1436: Remove photo caption from AZ Person displays
  modules/custom/az_person/config/install/core.entity_view_display.node.az_person.az_row.yml
  modules/custom/az_person/config/install/core.entity_view_display.node.az_person.default.yml
Labels: bug, enhancement, QS1 feature parity, visual change, 2.8.x only

#2695 Closes #1152: Use default theme logo when "Use the logo supplied by the theme" is checked
  themes/custom/az_barrio/az_barrio.info.yml
  themes/custom/az_barrio/az_barrio.theme
Labels: bug, patch release

#2704 Closes #2703 Remove permission for deleted quickedit module.
  config/install/user.role.az_content_editor.yml
Labels: bug, backport, high priority, patch release

#2687 Closes #2686 Fix AZCardWidget deprecation warnings and broken default (empty) URL.
  modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php
  modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php
Labels: bug, backport, patch release

#2692 Closes #2688: Replace DraggableViews weights issue patch.
  composer.json
Labels: bug, backport, dependencies, Drupal, patch release

#2690 Closes #2646: Add hero layout to Marketing Cloud
  modules/custom/az_marketing_cloud/az_marketing_cloud.module
  modules/custom/az_marketing_cloud/config/install/core.entity_view_display.node.az_news.az_marketing_cloud_hero_layout.yml
  modules/custom/az_marketing_cloud/config/install/core.entity_view_mode.node.az_marketing_cloud_hero_layout.yml
  modules/custom/az_marketing_cloud/config/install/crop.type.az_marketing_cloud_hero_layout.yml
  modules/custom/az_marketing_cloud/config/install/image.style.az_marketing_cloud_hero_layout.yml
  modules/custom/az_marketing_cloud/config/install/views.view.az_marketing_cloud.yml
  modules/custom/az_marketing_cloud/templates/node--view--az-marketing-cloud--hero-layout.html.twig
  modules/custom/az_media/config/install/core.entity_form_display.media.az_image.default.yml
  modules/custom/az_media/config/install/core.entity_form_display.media.az_image.media_library.yml
Labels: patch release, 2.7.x only, trellis

#2716 Closes #2712: Fix sidebar news heading level accessibility
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_minimal_media_list.yml
Labels: bug, patch release, accessibility

#2715 Closes #2713 Event rows without thumbnails are missing top padding on mobile devices
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_row.yml
Labels: bug, visual change, 2.8.x only

#2583 Closes #1663 New paragraph type for side-by-side Event and News views
  modules/custom/az_core/config/install/core.entity_view_mode.node.az_row_with_background.yml
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_row_with_background.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_row_with_background.yml
  modules/custom/az_paragraphs/az_paragraphs_views_side_by_side/az_paragraphs_views_side_by_side.info.yml
  modules/custom/az_paragraphs/az_paragraphs_views_side_by_side/az_paragraphs_views_side_by_side.module
  modules/custom/az_paragraphs/az_paragraphs_views_side_by_side/config/install/core.entity_form_display.paragraph.az_views_side_by_side.default.yml
  modules/custom/az_paragraphs/az_paragraphs_views_side_by_side/config/install/core.entity_view_display.paragraph.az_views_side_by_side.default.yml
  modules/custom/az_paragraphs/az_paragraphs_views_side_by_side/config/install/field.field.paragraph.az_views_side_by_side.field_az_first_view_button.yml
  modules/custom/az_paragraphs/az_paragraphs_views_side_by_side/config/install/field.field.paragraph.az_views_side_by_side.field_az_second_view.yml
  modules/custom/az_paragraphs/az_paragraphs_views_side_by_side/config/install/field.field.paragraph.az_views_side_by_side.field_az_second_view_button.yml
  modules/custom/az_paragraphs/az_paragraphs_views_side_by_side/config/install/field.field.paragraph.az_views_side_by_side.field_az_second_view_title.yml
  modules/custom/az_paragraphs/az_paragraphs_views_side_by_side/config/install/field.field.paragraph.az_views_side_by_side.field_az_title.yml
  modules/custom/az_paragraphs/az_paragraphs_views_side_by_side/config/install/field.field.paragraph.az_views_side_by_side.field_az_view_reference.yml
  modules/custom/az_paragraphs/az_paragraphs_views_side_by_side/config/install/field.storage.paragraph.field_az_first_view_button.yml
  modules/custom/az_paragraphs/az_paragraphs_views_side_by_side/config/install/field.storage.paragraph.field_az_second_view.yml
  modules/custom/az_paragraphs/az_paragraphs_views_side_by_side/config/install/field.storage.paragraph.field_az_second_view_button.yml
  modules/custom/az_paragraphs/az_paragraphs_views_side_by_side/config/install/field.storage.paragraph.field_az_second_view_title.yml
  modules/custom/az_paragraphs/az_paragraphs_views_side_by_side/config/install/paragraphs.paragraphs_type.az_views_side_by_side.yml
  modules/custom/az_paragraphs/az_paragraphs_views_side_by_side/config/install/views.view.az_side_by_side_views.yml
  modules/custom/az_paragraphs/az_paragraphs_views_side_by_side/templates/field--field-az-first-view-button.html.twig
  modules/custom/az_paragraphs/az_paragraphs_views_side_by_side/templates/field--field-az-second-view-button.html.twig
Labels: enhancement, 2.8.x only

#2729 Closes #2728: Allow split screen paragraph content to span full width.
  modules/custom/az_paragraphs/az_paragraphs_splitscreen/css/az_splitscreen.css
Labels: bug, backport, patch release, visual change

#2731 Closes #2723: Update marketing cloud template text layout
  modules/custom/az_marketing_cloud/templates/node--view--az-marketing-cloud--text-layout.html.twig
Labels: bug, patch release

#2751 Closes #2750: Update Drupal core to 10.0.11 for SA-CORE-006 (critical security update).
  composer.json
Labels: bug, high priority, Drupal, patch release, 2.7.x only

#2752 #2750: Update Drupal core to 9.5.11 for SA-CORE-006 (critical security update).
  composer.json
Labels: bug, high priority, Drupal, patch release, 2.6.x only

#2734 Closes #2733: Add AZ Person View Display
  modules/custom/az_person/config/install/views.view.az_person.yml
Labels: enhancement, visual change, 2.8.x only

#2587 Closes #2573: Upgrade Drupal core to 10.1.x.
  .eslintrc.json
  .probo.yaml
  composer.json
  config/install/block.block.claro_breadcrumbs.yml
  config/install/block.block.claro_content.yml
  config/install/block.block.claro_help.yml
  config/install/block.block.claro_local_actions.yml
  config/install/block.block.claro_messages.yml
  config/install/block.block.claro_page_title.yml
  config/install/block.block.claro_primary_local_tasks.yml
  config/install/block.block.claro_secondary_local_tasks.yml
  config/install/user.role.az_content_admin.yml
  config/install/user.role.az_content_editor.yml
  config/install/views.view.block_content.yml
  modules/custom/az_card/js/az-card-no-follow.js
  modules/custom/az_core/css/claro-node-form-overrides.css
  modules/custom/az_core/src/Plugin/ConfigProvider/QuickstartConfigProvider.php
  modules/custom/az_course/migrations/az_courses.yml
  modules/custom/az_demo/migrations/az_demo_block_content_menu.yml
  modules/custom/az_demo/migrations/az_demo_card_paragraph.yml
  modules/custom/az_demo/migrations/az_demo_event_rrule.yml
  modules/custom/az_demo/migrations/az_demo_splitscreen_paragraph.yml
  modules/custom/az_demo/migrations/az_demo_text_background_paragraph.yml
  modules/custom/az_demo/migrations/az_demo_text_media_paragraph.yml
  modules/custom/az_demo/migrations/az_demo_text_paragraph.yml
  modules/custom/az_migration/az_migration.info.yml
  modules/custom/az_migration/migrations/az_block_content_flexible_block.yml
  modules/custom/az_migration/migrations/az_node_carousel.yml
  modules/custom/az_migration/migrations/az_node_event.yml
  modules/custom/az_migration/migrations/az_node_flexible_page.yml
  modules/custom/az_migration/migrations/az_node_person.yml
  modules/custom/az_migration/migrations/az_paragraph_card_deck.yml
  modules/custom/az_migration/migrations/az_paragraph_carousel.yml
  modules/custom/az_migration/migrations/az_paragraph_column_image.yml
  modules/custom/az_migration/migrations/az_paragraph_content_marquee.yml
  modules/custom/az_migration/migrations/az_paragraph_full_width_bg_wrapper.yml
  modules/custom/az_migration/migrations/az_paragraph_full_width_media_row.yml
  modules/custom/az_migration/migrations/az_paragraph_gallery.yml
  modules/custom/az_migration/migrations/az_paragraph_single_card.yml
  modules/custom/az_migration/migrations/az_paragraph_well.yml
  modules/custom/az_migration/migrations/az_redirects.yml
  modules/custom/az_paragraphs/tests/src/Unit/AZVideoEmbedHelperTest.php
  modules/custom/az_publication/src/Controller/AZAuthorController.php
  modules/custom/az_publication/src/Form/AZAuthorRevisionDeleteForm.php
  modules/custom/az_publication/src/Form/AZAuthorRevisionRevertForm.php
  modules/custom/az_select_menu/js/az-select-menu.js
  phpstan.neon
Labels: enhancement, dependencies, high priority, Drupal, 2.8.x only

#2714 Closes #2710 Remove Arizona Bootstrap overrides.
  themes/custom/az_barrio/css/az-barrio-off-canvas-nav.css
Labels: task, patch release, 2.7.x only

#2773 Fixes #2772 Error loading CSS library prevents adding paragraphs
  composer.json
Labels: bug, high priority, 2.8.x only

#2777 Closes #2770 Page edit form too narrow on wide screens
  modules/custom/az_core/css/claro-node-form-overrides.css
Labels: bug, user experience, 2.8.x only

#2768 Closes #2767 Re-export config ahead of 2.8.0 release.
  modules/custom/az_media/config/install/core.entity_view_display.media.az_remote_video.az_background.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_remote_video.az_large.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_remote_video.az_medium.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_remote_video.az_natural_size.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_remote_video.az_small.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_remote_video.az_square.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_remote_video.default.yml
  modules/custom/az_person/config/install/core.entity_view_display.node.az_person.az_card.yml
Labels: task, 2.8.x only
