Repository az-digital/az_quickstart, pull requests merged in 2023-05, with the labels that each got.

#2393 Closes #2106 Allow <code> and/or <pre> HTML elements in az_standard text format
  config/install/filter.format.basic_html.yml
  modules/custom/az_demo/data/az_demo_menu_links.json
  modules/custom/az_demo/data/az_demo_page_node.json
  modules/custom/az_demo/data/az_demo_text_paragraph.json
  modules/custom/az_media/config/install/filter.format.az_standard.yml
Labels: enhancement, editor experience

#2364 Closes #2363: Use arm64-compatible webdriver image for lando.
  .lando.yml
Labels: bug, ci

#2396 Closes #2395 - Enable Splitscreen by default
  az_quickstart.info.yml
  az_quickstart.install
Labels: enhancement, editor experience, 2.7.x only

#2376 Closes #2375 Adding Flag module to Quickstart with Basic Permissions
  composer.json
  config/install/user.role.az_content_admin.yml
Labels: enhancement, 2.7.x only

#2438 Closes #2437 - Fix Slack channel and meeting information in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#2421 Closes #2418: Update drupal/core-recommended to 9.4.15 (2.5.x only)
  composer.json
Labels: bug, dependencies, Drupal, patch release, 2.5.x only

#2430 Closes #2417: Fix double-encoded publication file URLs.
  modules/custom/az_publication/az_publication.module
Labels: bug, patch release

#2411 #2403: Refactor AllowDrupalLogin test trait to not override parent::setup().
  modules/custom/az_core/tests/src/Functional/QuickstartFunctionalTestBase.php
  modules/custom/az_core/tests/src/FunctionalJavascript/QuickstartFunctionalJavascriptTestBase.php
  modules/custom/az_core/tests/src/Traits/AllowDrupalLoginSetupTrait.php
Labels: bug, enhancement

#2381 Closes #1396: Added 3-col view display for AZ Person
  modules/custom/az_person/config/install/views.view.az_person.yml
Labels: bug, enhancement, 2.7.x only

#2444 Closes #2382 - Fix PHP 8 code deprecation in custom smart_date migrate plugin.
  modules/custom/az_event/src/Plugin/migrate/process/SmartDateCreateRecurrenceOnField.php
Labels: bug, patch release

#2432 Closes #2431 Allow content administrators to manage their own url aliases.
  config/install/user.role.az_content_admin.yml
Labels: bug, documentation, enhancement, 2.7.x only

#2425 Close #2424 Adding badge display for all default taxonomy vocabularies.
  modules/custom/az_core/config/install/smart_title.settings.yml
  modules/custom/az_event/config/install/core.entity_view_display.taxonomy_term.az_event_categories.az_badge.yml
  modules/custom/az_flexible_page/config/install/core.entity_view_display.taxonomy_term.az_page_categories.az_badge.yml
  modules/custom/az_news/config/install/core.entity_view_display.taxonomy_term.az_news_tags.az_badge.yml
Labels: enhancement, patch release
