Repository az-digital/az_quickstart, pull requests merged in 2023-02, with the labels that each got.

#2077 Closes #1993 - Add "modal" view display to AZ Person
  modules/custom/az_media/config/install/core.entity_form_display.media.az_image.default.yml
  modules/custom/az_media/config/install/core.entity_form_display.media.az_image.media_library.yml
  modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_modal_image.yml
  modules/custom/az_media/config/install/core.entity_view_mode.media.az_modal_image.yml
  modules/custom/az_media/config/install/crop.type.az_modal_image.yml
  modules/custom/az_media/config/install/image.style.az_modal_image.yml
  modules/custom/az_person/az_person.module
  modules/custom/az_person/config/install/views.view.az_person.yml
  modules/custom/az_person/css/az_person.css
Labels: documentation, enhancement, 2.6.x only

#2196 Closes #2195: Move Import Courses link to Quickstart section of admin menu.
  modules/custom/az_course/az_course.links.menu.yml
Labels: bug, backport, patch release

#2208 Fixes #2074 Add drush command for adding missing permissions to Quickstart roles.
  modules/custom/az_core/drush.services.yml
  modules/custom/az_core/src/Commands/AZCoreConfigCommands.php
  modules/custom/az_core/src/Plugin/ConfigProvider/QuickstartConfigProvider.php
Labels: bug, enhancement, 2.6.x only

#2211 Fixes #2201 Custom form display disabled on module uninstall.
  modules/custom/az_core/src/Plugin/ConfigProvider/QuickstartConfigProvider.php
Labels: bug, enhancement, high priority, 2.6.x only, needs-CWS-testing

#2168 Closes #2167 AZ Person 'Link to external bio' is not currently implemented
  modules/custom/az_person/config/install/core.entity_view_display.node.az_person.az_card.yml
  modules/custom/az_person/config/install/core.entity_view_display.node.az_person.az_row.yml
Labels: enhancement, QS1 feature parity, 2.6.x only

#2194 Fixes #2094 Improve markup of default fields.
  themes/custom/az_barrio/css/style.css
  themes/custom/az_barrio/templates/field/field.html.twig
Labels: enhancement, low priority, visual change, 2.6.x only

#2192 Closes #570 Add title field to Cards paragraph type
  modules/custom/az_paragraphs/az_paragraphs_cards/config/install/core.entity_form_display.paragraph.az_cards.default.yml
  modules/custom/az_paragraphs/az_paragraphs_cards/config/install/core.entity_view_display.paragraph.az_cards.default.yml
  modules/custom/az_paragraphs/az_paragraphs_cards/config/install/core.entity_view_display.paragraph.az_cards.preview.yml
  modules/custom/az_paragraphs/az_paragraphs_cards/config/install/field.field.paragraph.az_cards.field_az_title.yml
Labels: documentation, enhancement, visual change, 2.6.x only, needs-CWS-testing, user experience

#2210 Closes #2198: Add MVP Trellis Events integration as experimental module.
  modules/custom/az_event/az_event_trellis/az_event_trellis.info.yml
  modules/custom/az_event/az_event_trellis/az_event_trellis.links.task.yml
  modules/custom/az_event/az_event_trellis/az_event_trellis.module
  modules/custom/az_event/az_event_trellis/az_event_trellis.routing.yml
  modules/custom/az_event/az_event_trellis/az_event_trellis.services.yml
  modules/custom/az_event/az_event_trellis/config/install/az_event_trellis.settings.yml
  modules/custom/az_event/az_event_trellis/config/install/migrate_plus.migration.az_trellis_events.yml
  modules/custom/az_event/az_event_trellis/config/install/migrate_plus.migration_group.az_trellis_events.yml
  modules/custom/az_event/az_event_trellis/config/install/migrate_queue_importer.cron_migration.az_event_trellis.yml
  modules/custom/az_event/az_event_trellis/src/Form/TrellisEventImportForm.php
  modules/custom/az_event/az_event_trellis/src/Form/TrellisEventSettingsForm.php
  modules/custom/az_event/az_event_trellis/src/Plugin/migrate/process/TrellisFormatDate.php
  modules/custom/az_event/az_event_trellis/src/TrellisHelper.php
  modules/custom/az_event/config/install/core.entity_form_display.node.az_event.default.yml
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_card.yml
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_row.yml
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.default.yml
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.teaser.yml
  modules/custom/az_event/config/install/field.field.node.az_event.field_az_trellis_id.yml
  modules/custom/az_event/config/install/field.storage.node.field_az_trellis_id.yml
  modules/custom/az_seo/config/quickstart/core.entity_form_display.node.az_event.default.yml
Labels: enhancement, high priority, Integrations, 2.6.x only, needs-CWS-testing

#2166 Closes #2017 Add Landing Page functionality to Quickstart
  config/install/user.role.az_content_admin.yml
  modules/custom/az_demo/az_demo.install
  modules/custom/az_demo/data/az_demo_menu_links.json
  modules/custom/az_demo/data/az_demo_page_node.json
  modules/custom/az_demo/data/az_demo_text_background_paragraph.json
  modules/custom/az_demo/data/az_demo_text_media_paragraph.json
  modules/custom/az_demo/data/az_demo_text_paragraph.json
  modules/custom/az_demo/migrations/az_demo_page_node.yml
  modules/custom/az_flexible_page/az_flexible_page.info.yml
  modules/custom/az_flexible_page/az_flexible_page.links.task.yml
  modules/custom/az_flexible_page/az_flexible_page.module
  modules/custom/az_flexible_page/az_flexible_page.permissions.yml
  modules/custom/az_flexible_page/az_flexible_page.routing.yml
  modules/custom/az_flexible_page/config/install/az_flexible_page.settings.yml
  modules/custom/az_flexible_page/config/install/core.entity_form_display.node.az_flexible_page.default.yml
  modules/custom/az_flexible_page/config/install/core.entity_view_display.node.az_flexible_page.az_card.yml
  modules/custom/az_flexible_page/config/install/core.entity_view_display.node.az_flexible_page.az_row.yml
  modules/custom/az_flexible_page/config/install/core.entity_view_display.node.az_flexible_page.default.yml
  modules/custom/az_flexible_page/config/install/field.field.node.az_flexible_page.field_az_marketing_page_style.yml
  modules/custom/az_flexible_page/config/install/field.storage.node.field_az_marketing_page_style.yml
  modules/custom/az_flexible_page/config/schema/az_flexible_page.schema.yml
  modules/custom/az_flexible_page/src/Form/AzFlexiblePageSettingsForm.php
  modules/custom/az_seo/config/quickstart/core.entity_form_display.node.az_flexible_page.default.yml
Labels: enhancement, high priority, 2.6.x only

#2064 Closes #1517 Add flexible block migration
  modules/custom/az_migration/migrations/az_block_content_flexible_block.yml
  modules/custom/az_migration/src/Plugin/migrate/process/EntityEmbedProcess.php
  modules/custom/az_migration/src/Plugin/migrate/source/AZBean.php
Labels: enhancement, migration, 2.6.x only

#2217 Update Arizona Bootstrap to 2.0.23
  composer.json
  themes/custom/az_barrio/includes/common.inc
Labels: dependencies, 2.6.x only

#2006 Closes #1967 AZ News: Remove "links" display, and unused field groups for all view modes.
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_card.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_feature.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_marquee.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_media_list.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_medium_media_list.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_minimal_media_list.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.default.yml
Labels: task, visual change, 2.6.x only

#2218 Update composer branch alias in preparation for 2.6.0 pre-release.
  composer.json
Labels: backport

#2220 Update fallback branch references in CI & local dev tools for 2.6.x branch
  .ddev/commands/web/install
  .github/workflows/security.yml
  .lando.yml
  .probo.yaml
Labels: 2.6.x only

#2223 Closes #2222: Require PHP 8.0+ for experimental Trellis Events integration module.
  modules/custom/az_event/az_event_trellis/az_event_trellis.info.yml
Labels: bug, 2.6.x only, php

#2232 Closes #2229: Ensure block_class module is installed.
  az_quickstart.install
Labels: bug, 2.6.x only

#2235 Closes #2234: Update drupal/smart_date from 3.6.1 to 3.7.0.
  composer.json
Labels: backport, dependencies, Drupal, patch release

#2231 Fixes #2214 Add a View to Publications to have all searches in one View
  modules/custom/az_paragraphs/az_paragraphs_view/config/install/field.field.paragraph.az_view_reference.field_az_view_reference.yml
  modules/custom/az_publication/az_publication.info.yml
  modules/custom/az_publication/az_publication.module
  modules/custom/az_publication/config/install/views.view.az_publications.yml
  modules/custom/az_publication/config/install/views.view.az_publications_author.yml
  modules/custom/az_publication/config/install/views.view.az_publications_title.yml
  modules/custom/az_publication/config/install/views.view.az_publications_type.yml
  modules/custom/az_publication/templates/views-exposed-form--az-publications.html.twig
Labels: enhancement, accessibility, 2.6.x only, needs-CWS-testing, usability

#2236 Fixes #2233 Make Publication citation style not dependent on View Mode
  config/install/exclude_node_title.settings.yml
  modules/custom/az_paragraphs/az_paragraphs_view/config/install/field.field.paragraph.az_view_reference.field_az_view_reference.yml
  modules/custom/az_publication/az_publication.links.menu.yml
  modules/custom/az_publication/az_publication.links.task.yml
  modules/custom/az_publication/az_publication.module
  modules/custom/az_publication/az_publication.routing.yml
  modules/custom/az_publication/az_publication.views.inc
  modules/custom/az_publication/config/install/az_publication.az_citation_style.full.yml
  modules/custom/az_publication/config/install/az_publication.settings.yml
  modules/custom/az_publication/config/install/core.entity_view_display.node.az_publication.az_ama.yml
  modules/custom/az_publication/config/install/core.entity_view_display.node.az_publication.az_apa.yml
  modules/custom/az_publication/config/install/core.entity_view_display.node.az_publication.az_chicago.yml
  modules/custom/az_publication/config/install/core.entity_view_display.node.az_publication.az_ieee.yml
  modules/custom/az_publication/config/install/core.entity_view_display.node.az_publication.az_mla.yml
  modules/custom/az_publication/config/install/core.entity_view_display.node.az_publication.az_publication_reference.yml
  modules/custom/az_publication/config/install/core.entity_view_mode.node.az_ama.yml
  modules/custom/az_publication/config/install/core.entity_view_mode.node.az_apa.yml
  modules/custom/az_publication/config/install/core.entity_view_mode.node.az_bluebook.yml
  modules/custom/az_publication/config/install/core.entity_view_mode.node.az_chicago.yml
  modules/custom/az_publication/config/install/core.entity_view_mode.node.az_ieee.yml
  modules/custom/az_publication/config/install/core.entity_view_mode.node.az_publication_reference.yml
  modules/custom/az_publication/config/install/views.view.az_publications.yml
  modules/custom/az_publication/config/install/views.view.az_publications_person.yml
  modules/custom/az_publication/config/schema/az_publication.schema.yml
  modules/custom/az_publication/src/Entity/AZAuthor.php
  modules/custom/az_publication/src/Entity/AZQuickstartCitationStyle.php
  modules/custom/az_publication/src/Form/AZQuickstartCitationStyleForm.php
  modules/custom/az_publication/src/Form/AzPublicationSettingsForm.php
  modules/custom/az_publication/src/Plugin/views/argument/AZCitationStyleArgument.php
  modules/custom/az_publication/templates/block--block-content--views-reference--az-publications--az-author-person.html.twig
  modules/custom/az_publication/templates/block--views-block--az-publications-az-author-person.html.twig
Labels: enhancement, accessibility, 2.6.x only, editor experience

#2228 Closes #2227 re-add linked image in az_person az_row view mode.
  modules/custom/az_person/config/install/core.entity_view_display.node.az_person.az_card.yml
  modules/custom/az_person/config/install/core.entity_view_display.node.az_person.az_row.yml
  modules/custom/az_person/css/az_person.css
  themes/custom/az_barrio/css/style.css
Labels: bug, 2.6.x only

#2238 #2234: Allow smart_date 3.6.1 to be used since 3.7.0 requires PHP 8.0+.
  composer.json
Labels: bug, dependencies, Drupal, 2.6.x only

#2241 Closes #2239: Remove unnecesssary timezone processing from Trellis Events importer.
  modules/custom/az_event/az_event_trellis/config/install/migrate_plus.migration.az_trellis_events.yml
  modules/custom/az_event/az_event_trellis/src/Plugin/migrate/process/TrellisFormatDate.php
Labels: bug, 2.6.x only

#2246 Closes #2245 Unused imports in flexible page settings form
  modules/custom/az_flexible_page/src/Form/AzFlexiblePageSettingsForm.php
Labels: bug, enhancement, 2.7.x only

#2244 Closes #2119 Add categories to events and pages in demo content
  modules/custom/az_demo/data/az_demo_event_categories.json
  modules/custom/az_demo/data/az_demo_event_node.json
  modules/custom/az_demo/data/az_demo_page_categories.json
  modules/custom/az_demo/data/az_demo_page_node.json
  modules/custom/az_demo/migrations/az_demo_event_categories.yml
  modules/custom/az_demo/migrations/az_demo_event_node.yml
  modules/custom/az_demo/migrations/az_demo_page_categories.yml
  modules/custom/az_demo/migrations/az_demo_page_node.yml
Labels: bug, enhancement, 2.7.x only

#2242 Backport #2238 for 2.5.x Allow smart_date 3.7.0 to be used if PHP 8.0+ is available.
  composer.json
Labels: backport, dependencies, 2.5.x only

#2252 Closes #2251 Remove block_class config for `az_barrio_search` block and add `az-search-block` class via preprocess hook.
  themes/custom/az_barrio/az_barrio.theme
  themes/custom/az_barrio/config/optional/block.block.az_barrio_search.yml
Labels: bug, high priority

#2250 Closes #2249: Fix migration config for link field on news and events that is generating PHP warnings.
  modules/custom/az_migration/migrations/az_node_event.yml
  modules/custom/az_migration/migrations/az_node_news.yml
Labels: bug, backport, migration, patch release

#2254 Closes #2253 - Add az_flexible_page to smart_title settings
  modules/custom/az_core/config/install/smart_title.settings.yml
Labels: bug, backport, patch release
