Repository az-digital/az_quickstart, pull requests merged in 2023-12, with the labels that each got.

#2978 #2967: Coding standards fixes for Drupal 10.2.x
  az_quickstart.install
  modules/custom/az_accordion/src/Plugin/Field/FieldFormatter/AZAccordionDefaultFormatter.php
  modules/custom/az_cas/az_cas.module
  modules/custom/az_core/az_core.module
  modules/custom/az_core/az_enterprise_attributes_import/src/Form/AZEnterpriseAttributesImportForm.php
  modules/custom/az_core/src/AZConfigOverride.php
  modules/custom/az_core/src/Commands/AZCoreConfigCommands.php
  modules/custom/az_core/src/Plugin/Field/FieldFormatter/AZEnterpriseTextExportFormatter.php
  modules/custom/az_core/src/Plugin/Field/FieldWidget/AZAttributeWidget.php
  modules/custom/az_core/tests/src/Functional/QuickstartFunctionalTestBase.php
  modules/custom/az_course/src/CourseSearch.php
  modules/custom/az_course/src/Form/CourseImportForm.php
  modules/custom/az_course/src/Plugin/migrate_plus/data_fetcher/RetryHttp.php
  modules/custom/az_curated_views/src/Plugin/views/field/AZCuratedViewsField.php
  modules/custom/az_demo/az_demo.install
  modules/custom/az_digital_asset_library/az_digital_asset_library.module
  modules/custom/az_event/az_event.module
  modules/custom/az_event/az_event_trellis/src/EventSubscriber/AZEventTrellisDataSubscriber.php
  modules/custom/az_event/az_event_trellis/src/Plugin/views/field/AZEventTrellisViewsField.php
  modules/custom/az_event/az_event_trellis/src/Plugin/views/filter/AZEventTrellisViewsAttributeFilter.php
  modules/custom/az_event/az_event_trellis/src/TrellisHelper.php
  modules/custom/az_event/src/Plugin/views/filter/AZCalendarFilter.php
  modules/custom/az_flexible_page/az_flexible_page.module
  modules/custom/az_mail/src/Commands/AZMailCommands.php
  modules/custom/az_marketing_cloud/src/Plugin/views/field/AzDropbutton.php
  modules/custom/az_media/az_media.module
  modules/custom/az_metrics/src/EventSubscriber/AZMetricsSubscriber.php
  modules/custom/az_migration/src/Plugin/migrate/process/EntityEmbedProcess.php
  modules/custom/az_migration/src/Plugin/migrate/process/MigratedPathLookup.php
  modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsColumnImageFieldMerge.php
  modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsFileDownloadFieldMerge.php
  modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsUpdateMediaCaption.php
  modules/custom/az_migration/src/Plugin/migrate/process/TextFormatRecognizer.php
  modules/custom/az_migration/src/Plugin/migrate/source/AZFileHandle.php
  modules/custom/az_migration/tests/src/Functional/MigrateExceptionsTest.php
  modules/custom/az_news/az_news.module
  modules/custom/az_news/az_news_export/src/Normalizer/AZNewsDataEmptyNormalizer.php
  modules/custom/az_news/az_news_export/src/Plugin/views/row/AZNewsDataFieldRow.php
  modules/custom/az_paragraphs/src/Plugin/Field/FieldFormatter/AZBackgroundMediaFormatter.php
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithMediaParagraphBehavior.php
  modules/custom/az_publication/az_publication.module
  modules/custom/az_publication/az_publication_bibtex/src/Form/AZPublicationBibtexForm.php
  modules/custom/az_publication/az_publication_bibtex/src/Plugin/migrate_plus/data_parser/AZBibtex.php
  modules/custom/az_publication/az_publication_doi/src/Form/AZPublicationDOIForm.php
  modules/custom/az_publication/az_publication_import/src/EventSubscriber/AZPublicationImportEventSubscriber.php
  modules/custom/az_publication/src/AZAuthorAccessControlHandler.php
  modules/custom/az_publication/src/AZAuthorStorage.php
  modules/custom/az_publication/src/AZAuthorStorageInterface.php
  modules/custom/az_publication/src/AZPublicationLocaleMetadata.php
  modules/custom/az_publication/src/Controller/AZAuthorController.php
  modules/custom/az_publication/src/Entity/AZAuthor.php
  modules/custom/az_publication/src/Entity/AZAuthorInterface.php
  modules/custom/az_publication/src/Entity/AZQuickstartCitationStyle.php
  modules/custom/az_publication/src/Form/AZAuthorRevisionRevertForm.php
  modules/custom/az_publication/src/Form/AZAuthorRevisionRevertTranslationForm.php
  modules/custom/az_publication/src/Form/AZQuickstartCitationStyleForm.php
  themes/custom/az_barrio/theme-settings.php
Labels: enhancement, 2.9.x only

#2995 Closes #1946 Embedded images in demo content are not found
  modules/custom/az_demo/data/az_demo_image_file.json
  modules/custom/az_demo/migrations/az_demo_image_file.yml
Labels: bug, good first issue, patch release

#2422 Closes #2197 use card title field in demo content, Closes #2426 Add view paragraphs to demo content.
  modules/custom/az_demo/data/az_demo_card_paragraph.json
  modules/custom/az_demo/data/az_demo_menu_links.json
  modules/custom/az_demo/data/az_demo_page_categories.json
  modules/custom/az_demo/data/az_demo_page_node.json
  modules/custom/az_demo/data/az_demo_text_paragraph.json
  modules/custom/az_demo/data/az_demo_view_paragraph.json
  modules/custom/az_demo/migrations/az_demo_card_paragraph.yml
  modules/custom/az_demo/migrations/az_demo_page_node.yml
  modules/custom/az_demo/migrations/az_demo_view_paragraph.yml
Labels: enhancement, needs discussion

#3026 Fixes #3025 Use Core Field Delete Button for Cards
  modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php
Labels: bug, enhancement, high priority, editor experience, 2.9.x only

#3023 Close #3022 Change argument array syntax in .service.yml files to make it easier to review changes.
  modules/custom/az_card/az_card.services.yml
  modules/custom/az_cas/az_cas.services.yml
  modules/custom/az_core/az_core.services.yml
  modules/custom/az_core/drush.services.yml
  modules/custom/az_course/az_course.services.yml
  modules/custom/az_event/az_event_trellis/az_event_trellis.services.yml
  modules/custom/az_mail/drush.services.yml
  modules/custom/az_metrics/az_metrics.services.yml
  modules/custom/az_news/az_news_feeds/az_news_feeds.services.yml
  modules/custom/az_publication/az_publication.services.yml
  modules/custom/az_publication/az_publication_import/az_publication_import.services.yml
Labels: enhancement, good first issue, Drupal, no backport, 2.9.x only

#2963 Close #2962 handle empty values in TextFormatRecognizer.php
  modules/custom/az_migration/src/Plugin/migrate/process/TextFormatRecognizer.php
Labels: bug, enhancement, migration, 2.9.x only

#2953 Closes #2952 Clone permissions in the Quick Node Clone module do not reflect custom access rules
  composer.json
Labels: bug, dependencies, Drupal, patch release

#2915 Closes #2911: PHP 8.2 compatibility.
  .ddev/config.quickstart.yaml
  .github/workflows/create-release.yml
  .github/workflows/review-site.yml
  .github/workflows/security.yml
  .lando.yml
  .probo.yaml
  composer.json
  modules/custom/az_core/az_core.module
  modules/custom/az_event/az_event.module
  modules/custom/az_mail/src/Commands/AZMailCommands.php
  modules/custom/az_news/az_news.module
  modules/custom/az_paragraphs/src/Plugin/Field/FieldFormatter/AZBackgroundMediaFormatter.php
  modules/custom/az_publication/src/Form/AZAuthorRevisionRevertForm.php
  phpcs.xml.dist
  phpstan.neon
Labels: php, 2.9.x only

#3020 #3017 Deprecate the Block Content Permissions module and no longer install by default
  az_quickstart.info.yml
  az_quickstart.install
  az_quickstart.post_update.php
  config/install/user.role.az_content_admin.yml
  config/install/user.role.az_content_editor.yml
Labels: task, dependencies, 2.9.x only

#3029 Close #3028 Update throbber template to use Arizona Bootstrap spinner.
  themes/custom/az_barrio/az_barrio.info.yml
  themes/custom/az_barrio/az_barrio.libraries.yml
  themes/custom/az_barrio/js/az-ajax.es6.js
  themes/custom/az_barrio/js/az-ajax.js
Labels: enhancement, visual change, user experience, 2.9.x only

#2968 Closes #2967, Closes #1138, Closes #3025: Upgrade Drupal core to 10.2.x.
  composer.json
  config/install/editor.editor.basic_html.yml
  config/install/user.role.az_content_admin.yml
  config/install/user.role.az_content_editor.yml
  modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php
  modules/custom/az_carousel/src/Plugin/Block/AZCarouselNotice.php
  modules/custom/az_cas/src/Form/AzCasSettingsForm.php
  modules/custom/az_core/config/install/core.entity_view_mode.node.az_card.yml
  modules/custom/az_core/config/install/core.entity_view_mode.node.az_card_alternate.yml
  modules/custom/az_core/config/install/core.entity_view_mode.node.az_feature.yml
  modules/custom/az_core/config/install/core.entity_view_mode.node.az_marquee.yml
  modules/custom/az_core/config/install/core.entity_view_mode.node.az_media_list.yml
  modules/custom/az_core/config/install/core.entity_view_mode.node.az_medium_media_list.yml
  modules/custom/az_core/config/install/core.entity_view_mode.node.az_minimal_media_list.yml
  modules/custom/az_core/config/install/core.entity_view_mode.node.az_row.yml
  modules/custom/az_core/config/install/core.entity_view_mode.node.az_row_with_background.yml
  modules/custom/az_core/config/install/core.entity_view_mode.taxonomy_term.az_badge.yml
  modules/custom/az_core/config/install/views.view.az_taxonomy.yml
  modules/custom/az_core/src/Form/QuickstartCoreSettingsForm.php
  modules/custom/az_event/config/install/views.view.az_events.yml
  modules/custom/az_flexible_page/config/install/views.view.az_page_by_category.yml
  modules/custom/az_media/config/install/core.entity_view_mode.media.az_background.yml
  modules/custom/az_media/config/install/core.entity_view_mode.media.az_card_image.yml
  modules/custom/az_media/config/install/core.entity_view_mode.media.az_carousel_item.yml
  modules/custom/az_media/config/install/core.entity_view_mode.media.az_large.yml
  modules/custom/az_media/config/install/core.entity_view_mode.media.az_medium.yml
  modules/custom/az_media/config/install/core.entity_view_mode.media.az_modal_image.yml
  modules/custom/az_media/config/install/core.entity_view_mode.media.az_natural_size.yml
  modules/custom/az_media/config/install/core.entity_view_mode.media.az_small.yml
  modules/custom/az_media/config/install/core.entity_view_mode.media.az_square.yml
  modules/custom/az_media/config/install/core.entity_view_mode.media.az_thumbnail.yml
  modules/custom/az_news/az_news_feeds/src/Form/AzNewsFeedsAdminForm.php
  modules/custom/az_news/config/install/views.view.az_news.yml
  modules/custom/az_paragraphs/config/optional/editor.editor.az_standard.yml
  modules/custom/az_person/config/install/views.view.az_person.yml
  modules/custom/az_publication/az_publication_bibtex/src/Form/AZPublicationBibtexForm.php
  modules/custom/az_publication/src/Controller/AZAuthorController.php
  modules/custom/az_publication/src/Form/AZAuthorRevisionDeleteForm.php
  modules/custom/az_publication/src/Form/AZAuthorRevisionRevertForm.php
  modules/custom/az_select_menu/src/Plugin/Block/AzSelectMenu.php
  themes/custom/az_barrio/az_barrio.theme
  themes/custom/az_barrio/templates/layout/page.html.twig
  themes/custom/az_barrio/theme-settings.php
Labels: dependencies, high priority, Drupal, 2.9.x only

#3038 #3014: Add critical new block_content permissions to AZQS roles (added in Drupal 10.1.x)
  config/install/user.role.az_content_admin.yml
  config/install/user.role.az_content_editor.yml
Labels: bug, high priority, patch release

#3027 Closes #3014, Closes #3017: Update roles with additional block content permissions added to Drupal core 10.1 and deprecate block_content_permissions module.
  az_quickstart.info.yml
  az_quickstart.install
  az_quickstart.post_update.php
  config/install/user.role.az_content_admin.yml
  config/install/user.role.az_content_editor.yml
Labels: enhancement, high priority, Drupal, editor experience, 2.9.x only

#3052 Prepare 2.8.x branch for new minor release branch 2.9.x
  composer.json
Labels: 2.8.x only

#3051 Prepare repository for new minor release branch 2.9.x
  .ddev/commands/web/install
  .github/workflows/create-release.yml
  .github/workflows/security.yml
  .lando.yml
  .probo.yaml
  composer.json
Labels: 2.9.x only

#3050 Fix branch naming convention for minor release workflow and add new release branches.
  .github/workflows/prepare-for-minor-release.yml
Labels: bug, ci

#3053 Prepare repository for new minor release branch 2.9.x
  composer.json
Labels: 2.10.x only
