Repository az-digital/az_quickstart, pull requests merged in 2023-06, with the labels that each got.

#2291 Closes #2289: Add basic linkchecker extractor for az_card, and az_accordion field types.
  modules/custom/az_core/src/Plugin/LinkExtractor/AzLinkExtractor.php
  phpstan.neon
Labels: enhancement, 2.7.x only

#2459 Closes #2458 Update az_carousel required modules: slick, slick_views, blazy.
  composer.json
Labels: bug, dependencies, Drupal, patch release

#2469 Fixes #2362 Publication Views exposed filters overlap
  modules/custom/az_publication/az_publication.module
  modules/custom/az_publication/templates/views-exposed-form--az-publications.html.twig
Labels: bug, enhancement, patch release

#2262 Fixes #2255, Fixes #2299 API Endpoint for News Export
  modules/custom/az_core/az_core.info.yml
  modules/custom/az_core/az_core.libraries.yml
  modules/custom/az_core/az_core.module
  modules/custom/az_core/az_enterprise_attributes_import/az_enterprise_attributes_import.info.yml
  modules/custom/az_core/az_enterprise_attributes_import/az_enterprise_attributes_import.install
  modules/custom/az_core/az_enterprise_attributes_import/az_enterprise_attributes_import.links.task.yml
  modules/custom/az_core/az_enterprise_attributes_import/az_enterprise_attributes_import.module
  modules/custom/az_core/az_enterprise_attributes_import/az_enterprise_attributes_import.routing.yml
  modules/custom/az_core/az_enterprise_attributes_import/config/install/az_enterprise_attributes_import.settings.yml
  modules/custom/az_core/az_enterprise_attributes_import/config/schema/az_enterprise_attributes_import.yml
  modules/custom/az_core/az_enterprise_attributes_import/migrations/az_enterprise_attributes_import.yml
  modules/custom/az_core/az_enterprise_attributes_import/src/Form/AZEnterpriseAttributesImportForm.php
  modules/custom/az_core/az_enterprise_attributes_import/src/Plugin/migrate_plus/data_parser/AZEnterpriseAttributesJson.php
  modules/custom/az_core/config/install/az_core.settings.yml
  modules/custom/az_core/config/install/core.entity_form_display.taxonomy_term.az_enterprise_attributes.default.yml
  modules/custom/az_core/config/install/core.entity_view_display.taxonomy_term.az_enterprise_attributes.default.yml
  modules/custom/az_core/config/install/field.field.taxonomy_term.az_enterprise_attributes.field_az_attribute_key.yml
  modules/custom/az_core/config/install/field.field.taxonomy_term.az_enterprise_attributes.field_az_attribute_type.yml
  modules/custom/az_core/config/install/field.storage.node.field_az_enterprise_attributes.yml
  modules/custom/az_core/config/install/field.storage.taxonomy_term.field_az_attribute_key.yml
  modules/custom/az_core/config/install/field.storage.taxonomy_term.field_az_attribute_type.yml
  modules/custom/az_core/config/install/image.style.az_enterprise_thumbnail.yml
  modules/custom/az_core/config/install/image.style.az_enterprise_thumbnail_small.yml
  modules/custom/az_core/config/install/taxonomy.vocabulary.az_enterprise_attributes.yml
  modules/custom/az_core/config/schema/az_core.schema.yml
  modules/custom/az_core/css/az-enterprise-attributes.css
  modules/custom/az_core/src/Form/QuickstartCoreSettingsForm.php
  modules/custom/az_core/src/Plugin/Field/FieldFormatter/AZEnterpriseTextExportFormatter.php
  modules/custom/az_core/src/Plugin/Field/FieldWidget/AZAttributeWidget.php
  modules/custom/az_news/az_news_export/az_news_export.info.yml
  modules/custom/az_news/az_news_export/config/install/views.view.az_news_export.yml
  modules/custom/az_news/az_news_export/src/Plugin/views/row/AZNewsDataFieldRow.php
  modules/custom/az_news/config/install/core.entity_form_display.node.az_news.default.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_card.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_feature.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_marquee.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_media_list.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_medium_media_list.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_minimal_media_list.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.default.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.teaser.yml
  modules/custom/az_news/config/install/field.field.node.az_news.field_az_enterprise_attributes.yml
  modules/custom/az_seo/config/quickstart/core.entity_form_display.node.az_news.default.yml
Labels: enhancement, spike, Integrations, 2.7.x only

#2474 Closes #2473: Update display of links and CV fields in default Person display
  modules/custom/az_person/config/install/core.entity_view_display.node.az_person.default.yml
Labels: enhancement, 2.7.x only

#2453 #2321: Add page and block template workarounds for empty sidebars issue affecting recent Menu Block releases.
  themes/custom/az_barrio/templates/blocks/block--system-menu-block.html.twig
  themes/custom/az_barrio/templates/layout/page.html.twig
Labels: bug, enhancement, dependencies, Drupal, 2.7.x only

#2484 Closes #2383 Enable az_digital_asset_library by default
  .probo.yaml
  az_quickstart.info.yml
Labels: enhancement, 2.7.x only

#2461 Fixes #2440 Publication Translations
  modules/custom/az_publication/az_publication.module
  modules/custom/az_publication/az_publication.services.yml
  modules/custom/az_publication/src/AZPublicationLocaleMetadata.php
Labels: enhancement, visual change, accessibility, usability, user experience, 2.7.x only

#2481 Closes #2380 Adding permissions for using shortcuts.
  config/install/user.role.az_content_admin.yml
  config/install/user.role.az_content_editor.yml
Labels: enhancement, needs-CWS-testing, editor experience, 2.7.x only

#2358 Fixes #2247 Publication BibTeX Import
  composer.json
  modules/custom/az_publication/az_publication_bibtex/az_publication_bibtex.info.yml
  modules/custom/az_publication/az_publication_bibtex/az_publication_bibtex.links.menu.yml
  modules/custom/az_publication/az_publication_bibtex/az_publication_bibtex.routing.yml
  modules/custom/az_publication/az_publication_bibtex/migrations/az_publication_bibtex_import.yml
  modules/custom/az_publication/az_publication_bibtex/src/Form/AZPublicationBibtexForm.php
  modules/custom/az_publication/az_publication_bibtex/src/Plugin/migrate_plus/data_parser/AZBibtex.php
  modules/custom/az_publication/az_publication_bibtex/src/Processor/AZDateProcessor.php
  modules/custom/az_publication/az_publication_bibtex/src/Processor/AZLatexProcessor.php
  modules/custom/az_publication/az_publication_doi/az_publication_doi.info.yml
  modules/custom/az_publication/az_publication_doi/az_publication_doi.links.menu.yml
  modules/custom/az_publication/az_publication_doi/az_publication_doi.routing.yml
  modules/custom/az_publication/az_publication_doi/src/Form/AZPublicationDOIForm.php
  modules/custom/az_publication/az_publication_import/az_publication_import.info.yml
  modules/custom/az_publication/az_publication_import/az_publication_import.links.menu.yml
  modules/custom/az_publication/az_publication_import/az_publication_import.links.task.yml
  modules/custom/az_publication/az_publication_import/az_publication_import.routing.yml
  modules/custom/az_publication/az_publication_import/az_publication_import.services.yml
  modules/custom/az_publication/az_publication_import/src/Controller/AZPublicationImportController.php
  modules/custom/az_publication/az_publication_import/src/EventSubscriber/AZPublicationImportEventSubscriber.php
Labels: enhancement, usability, 2.7.x only

#2480 Closes #2366 Allow linking images that are embedded in content.
  modules/custom/az_media/config/install/filter.format.az_standard.yml
Labels: enhancement, editor experience, 2.7.x only

#2406 Closes #2383 Upgrade tag page view.
  modules/custom/az_core/config/install/views.view.az_taxonomy.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_row.yml
Labels: enhancement, needs-CWS-testing, 2.7.x only

#2452 Closes #2442: Update drupal/bootstrap_barrio from 4.30 to 5.1.10.
  composer.json
  themes/custom/az_barrio/theme-settings.php
Labels: enhancement, dependencies, Drupal, 2.7.x only

#2489 Closes #2486: Remove tooling for Drupal console 😢.
  .ddev/commands/web/drupal
  .lando.yml
  CONTRIBUTING.md
Labels: backport, ci, dependencies, patch release

#2354 Closes #2081: Upgrade Drupal core to 10.0.9
  .lando.yml
  .probo.yaml
  az_quickstart.info.yml
  composer.json
  modules/custom/az_cas/tests/src/Functional/AzCasAdminSettingsTest.php
  modules/custom/az_cas/tests/src/Functional/AzCasTest.php
  modules/custom/az_core/src/Plugin/Field/FieldWidget/AZAttributeWidget.php
  modules/custom/az_core/tests/src/Functional/ClearCacheTest.php
  modules/custom/az_course/src/CourseMigrateBatchExecutable.php
  modules/custom/az_course/src/Plugin/migrate_plus/data_fetcher/RetryHttp.php
  modules/custom/az_event/js/az_calendar_filter.es6.js
  modules/custom/az_event/js/az_calendar_filter.js
  modules/custom/az_migration/migrations/az_node_carousel.yml
  modules/custom/az_migration/migrations/az_node_event.yml
  modules/custom/az_migration/migrations/az_node_flexible_page.yml
  modules/custom/az_migration/migrations/az_node_news.yml
  modules/custom/az_migration/migrations/az_node_person.yml
  modules/custom/az_migration/migrations/az_node_uaqs_basic_page_to_az_page.yml
  modules/custom/az_publication/az_publication.libraries.yml
  modules/custom/az_publication/js/az_publication_date_picker.es6.js
  modules/custom/az_publication/js/az_publication_date_picker.js
  phpcs.xml.dist
  phpstan.neon
Labels: dependencies, high priority, Drupal, needs-CWS-testing, 2.7.x only

#2492 Update composer branch alias in preparation for 2.7.0 pre-release.
  composer.json
Labels: task

#2493 2.7.x default branch changes
  .ddev/commands/web/install
  .github/workflows/security.yml
  .lando.yml
  .probo.yaml
Labels: task

#2505 Closes #2499: Add viewsreference patch to address Ajax failures.
  composer.json
Labels: bug, high priority, patch release, 2.7.x only

#2498 Closes #2497 Reorder people row weight input boxes don't show values
  composer.json
Labels: bug, backport, patch release

#2513 Fixes #2512 Cursor missing in new text area on Chrome
  composer.json
Labels: bug, patch release, 2.7.x only

#2511 Closes #2502: Update Analytics Dashboard link in toolbar.
  modules/custom/az_google_tag/az_google_tag.module
Labels: enhancement, backport, patch release

#2507 #2331 Update slack channel names from #azdigital-general to #azdigital-support
  CONTRIBUTING.md
Labels: documentation

#2517 Closes #2516: Apply patch for XML sitemap D10 incompatibility issue.
  composer.json
Labels: bug, dependencies, Drupal, 2.7.x only

#2508 #2330 Update slack channel names from #friday-meetings to #azdigital-meetings
  CONTRIBUTING.md
Labels: documentation

#2501 Closes #2503: Update view display for AZ Person
  modules/custom/az_person/config/install/core.entity_view_display.node.az_person.default.yml
Labels: bug, patch release, 2.7.x only

#2510 Fixes #2509 Content editor role unintentionally deleted.
  config/install/user.role.az_content_editor.yml
  modules/custom/az_digital_asset_library/az_digital_asset_library.install
Labels: bug, high priority, 2.7.x only

#2514 Closes #2504 News articles are not displaying thumbnail images on view displays
  modules/custom/az_news/az_news.install
  modules/custom/az_news/az_news.post_update.php
Labels: bug, patch release, 2.7.x only

#2520 Closes #2518 RC2 Bug Fixes introduced extra space to the main navigation
  themes/custom/az_barrio/templates/blocks/block--system-menu-block.html.twig
Labels: bug, 2.7.x only

#2526 Closes #2525 Add error handling to 2.7.x az_news database update.
  modules/custom/az_news/az_news.install
Labels: bug, patch release, 2.7.x only

#2553 Closes #2552 Cannot remove instances of recurring events
  composer.json
Labels: bug

#2556 Closes #2541 Downgrade az_digital_asset_library back to experimental due to login issues.
  az_quickstart.info.yml
  modules/custom/az_digital_asset_library/az_digital_asset_library.info.yml
Labels: task, 2.7.x only

#2531 Closes #2529: Remove DB updates added before 2.6.0.
  az_quickstart.install
  modules/custom/az_core/az_core.install
  modules/custom/az_event/az_event.install
  modules/custom/az_flexible_page/az_flexible_page.install
  modules/custom/az_global_footer/az_global_footer.install
  modules/custom/az_mail/az_mail.install
  modules/custom/az_media/az_media.install
  modules/custom/az_migration/az_migration.install
  modules/custom/az_news/az_news.install
  modules/custom/az_paragraphs/az_paragraphs.install
  modules/custom/az_paragraphs/az_paragraphs_text_background/az_paragraphs_text_background.install
  modules/custom/az_paragraphs/az_paragraphs_text_media/az_paragraphs_text_media.install
  modules/custom/az_person/az_person.install
  modules/custom/az_security/az_security.install
  modules/custom/az_seo/az_seo.install
Labels: task, 2.7.x only

#2544 Closes #2300 Enable Search Keywords view filter
  composer.json
Labels: bug, dependencies, patch release, 2.7.x only

#2542 Closes #2491: Re-exported configuration files for 2.7.x
  config/install/block.block.az_barrio_main_menu.yml
  config/install/block.block.az_utility_links.yml
  config/install/block.block.claro_breadcrumbs.yml
  config/install/block.block.claro_content.yml
  config/install/block.block.claro_help.yml
  config/install/block.block.claro_local_actions.yml
  config/install/block.block.claro_messages.yml
  config/install/block.block.claro_page_title.yml
  config/install/block.block.claro_primary_local_tasks.yml
  config/install/block.block.claro_secondary_local_tasks.yml
  modules/custom/az_event/az_event_trellis/config/install/migrate_plus.migration.az_trellis_events.yml
  modules/custom/az_flexible_page/config/install/core.entity_view_display.node.az_flexible_page.default.yml
  modules/custom/az_media/config/install/core.entity_form_display.media.az_audio.default.yml
  modules/custom/az_media/config/install/core.entity_form_display.media.az_audio.media_library.yml
  modules/custom/az_media/config/install/core.entity_form_display.media.az_document.media_library.yml
  modules/custom/az_media/config/install/core.entity_form_display.media.az_image.default.yml
  modules/custom/az_media/config/install/core.entity_form_display.media.az_image.media_library.yml
  modules/custom/az_media/config/install/core.entity_form_display.media.az_video.default.yml
  modules/custom/az_media/config/install/core.entity_form_display.media.az_video.media_library.yml
Labels: task, 2.7.x only

#2545 Closes #2543 Retire theme-debug lando/ddev tooling.
  .ddev/commands/web/theme-debug
  .lando.yml
  CONTRIBUTING.md
Labels: bug, documentation, backport, ci, patch release

#2561 #2560 Update github action to use specific release branch of scaffolding repo
  .github/workflows/create-release.yml
Labels: bug, ci, 2.5.x only

#2562 #2560 Update github action to use specific release branch (2.6.x) of scaffolding repo
  .github/workflows/create-release.yml
Labels: bug, ci, 2.6.x only

#2563 #2560 Update github action to use specific release branch (2.7.x) of scaffolding repo
  .github/workflows/create-release.yml
Labels: bug, ci, 2.7.x only
