Repository az-digital/az_quickstart, pull requests merged in 2023-03, with the labels that each got.

#2260 Closes #2259 use null coallesce operator when creating strings to print from deeply nested array values (ParagraphsExtraInfoFieldMerge).
  modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsExtraInfoFieldMerge.php
Labels: bug, migration, patch release, 2.6.x only

#2274 Closes #2273: Fix az_events_trellis coding standards issues.
  modules/custom/az_event/az_event_trellis/az_event_trellis.module
  modules/custom/az_event/az_event_trellis/src/Form/TrellisEventImportForm.php
Labels: bug, patch release, 2.6.x only

#2269 Closes #2268: Add drupal/asset_injector as optional module.
  composer.json
Labels: enhancement, 2.7.x only

#2292 Closes #2288 Fix broken az_barrio footer logo field validation
  themes/custom/az_barrio/theme-settings.php
Labels: bug, patch release

#2284 Documentation: Add pre-migration task to menu links migration docs.
  modules/custom/az_migration/README.md
Labels: documentation, migration, patch release

#2270 Fixes #2257, Fixes #2258 Publication Person Block Title, Add Publication Taxonomy
  config/install/user.role.az_content_admin.yml
  modules/custom/az_publication/az_publication.info.yml
  modules/custom/az_publication/config/install/core.entity_form_display.node.az_publication.default.yml
  modules/custom/az_publication/config/install/core.entity_view_display.node.az_publication.az_publication_reference.yml
  modules/custom/az_publication/config/install/core.entity_view_display.node.az_publication.default.yml
  modules/custom/az_publication/config/install/core.entity_view_display.node.az_publication.teaser.yml
  modules/custom/az_publication/config/install/field.field.node.az_publication.field_az_publication_category.yml
  modules/custom/az_publication/config/install/field.storage.node.field_az_publication_category.yml
  modules/custom/az_publication/config/install/taxonomy.vocabulary.az_publication_categories.yml
  modules/custom/az_publication/config/install/views.view.az_publications.yml
Labels: bug, enhancement, patch release, 2.6.x only, usability, editor experience

#2283 Fixes #2282 News, Event, Person external links do not migrate.
  modules/custom/az_migration/migrations/az_node_event.yml
  modules/custom/az_migration/migrations/az_node_news.yml
  modules/custom/az_migration/migrations/az_node_person.yml
Labels: bug, backport, migration, patch release

#2278 Fixes #2277 Text Area, and Single Card paragraphs behavior settings migrating incorrectly.
  modules/custom/az_migration/migrations/az_paragraph_headed_text.yml
  modules/custom/az_migration/migrations/az_paragraph_single_card.yml
  modules/custom/az_paragraphs/az_paragraphs.install
Labels: bug, backport, migration, patch release

#2297 Closes #2294: Update Drupal core to 9.5.5 (moderately critical security update).
  composer.json
Labels: bug, dependencies, high priority, Drupal, patch release, 2.6.x only

#2296 Closes #2295: Update Drupal core to 9.4.12 (moderately critical security update).
  composer.json
Labels: bug, dependencies, high priority, Drupal, patch release, 2.5.x only

#2281 Closes #2264 Migrate path aliases for nodes if they exist, otherwise turn on Pathauto.
  modules/custom/az_migration/migrations/az_node_carousel.yml
  modules/custom/az_migration/migrations/az_node_event.yml
  modules/custom/az_migration/migrations/az_node_flexible_page.yml
  modules/custom/az_migration/migrations/az_node_news.yml
  modules/custom/az_migration/migrations/az_node_person.yml
  modules/custom/az_migration/migrations/az_node_uaqs_basic_page_to_az_page.yml
Labels: bug, backport, migration, patch release

#2318 Fixes #2312 Changes to existing news, event and person content do not update without clearing cache.
  modules/custom/az_news/az_news.module
Labels: bug, high priority, patch release, 2.6.x only
