Repository az-digital/az_quickstart, pull requests merged in 2023-10, with the labels that each got.

#2653 Closes #2572 Update Trellis Event Importer to use Trellis Event Search API
  composer.json
  modules/custom/az_event/az_event_trellis/az_event_trellis.info.yml
  modules/custom/az_event/az_event_trellis/az_event_trellis.libraries.yml
  modules/custom/az_event/az_event_trellis/az_event_trellis.links.task.yml
  modules/custom/az_event/az_event_trellis/az_event_trellis.module
  modules/custom/az_event/az_event_trellis/az_event_trellis.routing.yml
  modules/custom/az_event/az_event_trellis/az_event_trellis.services.yml
  modules/custom/az_event/az_event_trellis/az_event_trellis.views.inc
  modules/custom/az_event/az_event_trellis/config/install/az_event_trellis.settings.yml
  modules/custom/az_event/az_event_trellis/config/install/migrate_plus.migration.az_trellis_events.yml
  modules/custom/az_event/az_event_trellis/config/install/migrate_queue_importer.cron_migration.az_event_trellis.yml
  modules/custom/az_event/az_event_trellis/config/install/views.view.az_event_trellis_import.yml
  modules/custom/az_event/az_event_trellis/config/schema/az_event_trellis.schema.yml
  modules/custom/az_event/az_event_trellis/css/az_event_trellis_datewrapper.css
  modules/custom/az_event/az_event_trellis/js/az_event_trellis_date.es6.js
  modules/custom/az_event/az_event_trellis/js/az_event_trellis_date.js
  modules/custom/az_event/az_event_trellis/src/EventSubscriber/AZEventTrellisDataSubscriber.php
  modules/custom/az_event/az_event_trellis/src/Form/TrellisEventImportForm.php
  modules/custom/az_event/az_event_trellis/src/Plugin/migrate/source/AZTrellisEventSource.php
  modules/custom/az_event/az_event_trellis/src/Plugin/views/field/AZEventTrellisViewsField.php
  modules/custom/az_event/az_event_trellis/src/Plugin/views/filter/AZEventTrellisViewsAttributeFilter.php
  modules/custom/az_event/az_event_trellis/src/Plugin/views/filter/AZEventTrellisViewsDateFilter.php
  modules/custom/az_event/az_event_trellis/src/TrellisHelper.php
Labels: enhancement, high priority, Integrations, editor experience, 2.8.x only, trellis

#2769 Closes #807, Closes #1987, #2446 Switch to CKEditor5 and update text editor and format settings.
  az_quickstart.info.yml
  az_quickstart.install
  composer.json
  config/install/editor.editor.basic_html.yml
  config/install/filter.format.basic_html.yml
  modules/custom/az_media/config/install/filter.format.az_standard.yml
  modules/custom/az_paragraphs/az_paragraphs.libraries.yml
  modules/custom/az_paragraphs/config/optional/editor.editor.az_standard.yml
  modules/custom/az_paragraphs/config/optional/embed.button.az_embed_content.yml
  modules/custom/az_paragraphs/config/optional/embed.button.az_embed_content_block.yml
  themes/custom/az_barrio/az_barrio.info.yml
  themes/custom/az_barrio/css/ckeditor5.css
Labels: enhancement, dependencies, high priority, Drupal, 2.8.x only

#2722 Closes #2668: Add click to copy functionality to Marketing Cloud integration
  modules/custom/az_marketing_cloud/az_marketing_cloud.module
  modules/custom/az_marketing_cloud/az_marketing_cloud.views.inc
  modules/custom/az_marketing_cloud/config/install/views.view.az_marketing_cloud.yml
  modules/custom/az_marketing_cloud/css/az-marketing-cloud-admin.css
  modules/custom/az_marketing_cloud/images/30-70-layout.png
  modules/custom/az_marketing_cloud/images/50-50-layout.png
  modules/custom/az_marketing_cloud/images/event-layout.png
  modules/custom/az_marketing_cloud/images/hero-layout.png
  modules/custom/az_marketing_cloud/images/text-layout.png
  modules/custom/az_marketing_cloud/js/az-marketing-cloud-admin.es6.js
  modules/custom/az_marketing_cloud/js/az-marketing-cloud-admin.js
  modules/custom/az_marketing_cloud/src/Plugin/views/field/AzDropbutton.php
Labels: enhancement, patch release, trellis

#2719 Closes #2718: Update pagination sr-only heading levels
  themes/custom/az_barrio/templates/navigation/pager.html.twig
  themes/custom/az_barrio/templates/views/views-mini-pager.html.twig
Labels: bug, backport, patch release, accessibility

#2756 Closes #2755 Update create release workflow ahead of API changes.
  .github/workflows/create-release.yml
Labels: ci, dependencies, github_actions

#2793 Closes #1710 Add new GH Actions workflow for preparing a minor release
  .github/workflows/prepare-for-minor-release.yml
Labels: enhancement, ci

#2796 #1710: Fix new GH actions workflow for preparing a minor release
  .github/workflows/prepare-for-minor-release.yml
Labels: bug, ci

#2792 Closes #2685: Deprecate background_image_formatter module and add AZQS deprecated modules warning to status report.
  az_quickstart.install
  composer.json
Labels: enhancement, dependencies, 2.8.x only

#2762 Closes #2624: Open specific external links in new tab
  az_quickstart.info.yml
  az_quickstart.install
  composer.json
  config/install/extlink.settings.yml
Labels: enhancement, 2.8.x only, trellis

#2780 #2584: Add missing fields to news export for feature parity with legacy news feed
  modules/custom/az_news/az_news_export/config/install/views.view.az_news_export.yml
  modules/custom/az_news/az_news_export/src/Plugin/views/row/AZNewsDataFieldRow.php
Labels: documentation, enhancement, Integrations, 2.8.x only

#2803 Closes #2802: Add patch for Linkit 6.1.1 regression.
  composer.json
Labels: bug, dependencies, high priority, Drupal, 2.8.x only

#2809 Update RELEASES.md with information about beta and rc releases
  RELEASES.md
Labels: documentation

#2830 Closes #2825, Closes #2827 Add module installer for views_remote_data in update hook.
  modules/custom/az_event/az_event_trellis/az_event_trellis.install
Labels: bug, 2.8.x only, 2.8 beta

#2826 Closes #2824 Visual changes to node edit form with 2.8 pre-release
  modules/custom/az_core/az_core.libraries.yml
  modules/custom/az_core/az_core.module
  modules/custom/az_core/css/arizona-bootstrap-node-form-overrides.css
  modules/custom/az_core/css/claro-node-form-overrides.css
  modules/custom/az_paragraphs/az_paragraphs.libraries.yml
Labels: bug, visual change, 2.8.x only, 2.8 beta

#2833 Closes #2829 All external links opening in new tab instead of only intended external links
  config/install/extlink.settings.yml
Labels: bug, 2.8.x only, 2.8 beta

#2839 Closes #2838 Fix failing create-release workflow.
  .github/workflows/create-release.yml
Labels: bug, ci

#2837 Closes #2836: Fix PR branch naming convention in prepare-for-minor-release workflow.
  .github/workflows/prepare-for-minor-release.yml
Labels: bug, ci

#2853 Fixes #2851 Cannot Save Curation Options
  modules/custom/az_curated_views/src/Plugin/views/field/AZCuratedViewsField.php
Labels: bug, high priority, needs-CWS-testing, 2.8.x only, 2.8 beta

#2850 Closes #2849 CKEditor preview styling overridden by AZ Barrio styling in 2.8 beta2
  modules/custom/az_core/css/claro-node-form-overrides.css
  modules/custom/az_paragraphs/az_paragraphs.libraries.yml
Labels: bug, 2.8.x only, 2.8 beta

#2844 Closes #2843: Address blazy module status report error in 2.8.x.
  modules/custom/az_carousel/config/quickstart/blazy.settings.yml
Labels: bug, dependencies, high priority, Drupal, needs-CWS-testing, 2.8.x only, 2.8 beta

#2841 #2827: Use stable embed release and final entity embed patch for CKEditor5 support.
  composer.json
  config/install/editor.editor.basic_html.yml
  modules/custom/az_media/config/install/filter.format.az_standard.yml
  modules/custom/az_paragraphs/config/optional/editor.editor.az_standard.yml
  modules/custom/az_paragraphs/config/optional/embed.button.az_embed_content.yml
  modules/custom/az_paragraphs/config/optional/embed.button.az_embed_content_block.yml
Labels: bug, dependencies, high priority, needs-CWS-testing, editor experience, 2.8.x only, 2.8 beta

#2846 Closes #2845: Ensure legacy Quickstart block_content view is replaced by core view.
  az_quickstart.post_update.php
  modules/custom/az_flexible_block/az_flexible_block.links.action.yml
  modules/custom/az_flexible_block/src/Plugin/Menu/LocalAction/AzFlexibleBlockAddLocalAction.php
Labels: bug, high priority, needs-CWS-testing, 2.8.x only, 2.8 beta

#2866 Closes #2864 Update security.yml github action to not run on pushing of tags
  .github/workflows/security.yml
Labels: bug, ci

#2863 Closes #2786: Update phonebook/directory links in global footer.
  modules/custom/az_global_footer/az_global_footer.install
  modules/custom/az_global_footer/data/az_global_footer.json
Labels: backport, patch release

#2873 Closes #2872 CKEditor 5 strips classes from div elements
  modules/custom/az_paragraphs/config/optional/editor.editor.az_standard.yml
Labels: bug, editor experience, 2.8.x only, 2.8 beta

#2879 Closes #2878 Bootstrap Barrio Subtheme not D10 Compatible.
  composer.json
Labels: bug, backport, dependencies, Drupal, patch release

#2871 Closes #2869 Linkit CKEditor5 fix for adding urls.
  composer.json
Labels: bug, dependencies, high priority, Drupal, editor experience, 2.8 beta

#2885 Closes #2884: Address ProboCI drush issues
  .probo.yaml
Labels: bug, backport, ci, patch release
