Repository az-digital/az_quickstart, pull requests merged in 2023-11, with the labels that each got.

#2867 Closes #1613: Add space to footer menu items
  themes/custom/az_barrio/az_barrio.theme
  themes/custom/az_barrio/css/style.css
Labels: enhancement, visual change, 2.8.x only

#2882 Closes #2732 Alternating Split Screen paragraphs don't line up in the center
  modules/custom/az_paragraphs/az_paragraphs_splitscreen/css/az_splitscreen.css
Labels: bug, backport, patch release, visual change

#2891 Closes #2890: Update paragraphs_admin to 8.x-1.5 for SA-CONTRIB-2023-049.
  composer.json
Labels: bug, backport, dependencies, Drupal, patch release

#2897 Closes #2896 - Make white text visible while editing
  modules/custom/az_event/config/install/field.field.node.az_event.field_az_body.yml
  modules/custom/az_news/config/install/field.field.node.az_news.field_az_body.yml
  modules/custom/az_paragraphs/az_paragraphs_splitscreen/config/install/field.field.paragraph.az_splitscreen.field_az_text_area.yml
  modules/custom/az_paragraphs/az_paragraphs_text/config/install/field.field.paragraph.az_text.field_az_text_area.yml
  modules/custom/az_paragraphs/az_paragraphs_text_background/config/install/field.field.paragraph.az_text_background.field_az_text_area.yml
  modules/custom/az_paragraphs/az_paragraphs_text_media/config/install/field.field.paragraph.az_text_media.field_az_text_area.yml
  modules/custom/az_person/config/install/field.field.node.az_person.field_az_body.yml
  themes/custom/az_barrio/css/ckeditor5.css
Labels: bug, patch release, accessibility, usability, editor experience, 2.8.x only

#2880 Closes #2671: Enable copy options based on content type
  modules/custom/az_marketing_cloud/config/install/views.view.az_marketing_cloud.yml
Labels: enhancement, backport, patch release, editor experience, trellis

#2919 Closes #2918: Add AZ Bootstrap library dependency to node form overrides library.
  modules/custom/az_core/az_core.libraries.yml
Labels: bug, high priority, patch release, editor experience, 2.8.x only

#2917 Closes #2916 Exclude BigPipe module from Quickstart installs on Pantheon
  az_quickstart.info.yml
  az_quickstart.install
Labels: enhancement, patch release

#2908 Closes #2907 Make Manual Migration Lookup DB configurable.
  modules/custom/az_core/src/Plugin/migrate/process/ManualMigrationLookup.php
Labels: enhancement, migration, patch release

#2906 Closes #2905 Clean up PHPCS warnings
  modules/custom/az_core/src/Plugin/ConfigProvider/QuickstartConfigProvider.php
  modules/custom/az_core/src/Plugin/Field/FieldWidget/AZAttributeWidget.php
  modules/custom/az_digital_asset_library/az_digital_asset_library.module
  modules/custom/az_marketing_cloud/src/Plugin/views/field/AzDropbutton.php
  modules/custom/az_paragraphs/az_paragraphs_text_media/az_paragraphs_text_media.install
Labels: low priority, 2.9.x only

#2900 Closes #2102 Error upon save when linking to a document in a Card Link URL field
  modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php
  modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php
Labels: bug, backport, patch release, editor experience

#2901 Fixes #2888 Marketing Cloud Event Specificity
  modules/custom/az_marketing_cloud/az_marketing_cloud.module
  modules/custom/az_marketing_cloud/config/install/core.entity_view_display.node.az_event.az_marketing_cloud_event_layout.yml
  modules/custom/az_marketing_cloud/config/install/views.view.az_marketing_cloud.yml
Labels: bug, Integrations, editor experience, 2.8.x only, trellis

#2782 Closes #2702: Add unpublished content layout to Marketing Cloud
  modules/custom/az_marketing_cloud/az_marketing_cloud.module
  modules/custom/az_marketing_cloud/config/install/views.view.az_marketing_cloud.yml
  modules/custom/az_marketing_cloud/images/30-70-layout-unpublished.png
  modules/custom/az_marketing_cloud/images/50-50-layout-unpublished.png
  modules/custom/az_marketing_cloud/images/hero-layout-unpublished.png
  modules/custom/az_marketing_cloud/templates/node--view--az-marketing-cloud--hero-layout.html.twig
Labels: enhancement, trellis

#2940 Closes #2736: Remove whitespace on cards with no body or link.
  modules/custom/az_card/templates/az-card.html.twig
Labels: bug, patch release, visual change

#2949 Closes #2946 Video Thumbnail in Page/Event/News Editor Too Small
  modules/custom/az_media/az_media.module
Labels: bug, patch release, editor experience, 2.8.x only

#2945 Closes #2944 Update style.css text field widths
  themes/custom/az_barrio/css/style.css
Labels: bug, patch release, visual change

#2956 Closes #2169 Close icon broken in media library edit module's modal
  modules/custom/az_core/az_core.libraries.yml
Labels: bug, dependencies, patch release, editor experience, 2.8.x only

#2932 Close #2928 Always show summary fields when adding or editing content.
  modules/custom/az_event/config/install/core.entity_form_display.node.az_event.default.yml
  modules/custom/az_flexible_page/config/install/core.entity_form_display.node.az_flexible_page.default.yml
  modules/custom/az_news/config/install/core.entity_form_display.node.az_news.default.yml
  modules/custom/az_person/config/install/core.entity_form_display.node.az_person.default.yml
  modules/custom/az_seo/config/quickstart/core.entity_form_display.node.az_event.default.yml
  modules/custom/az_seo/config/quickstart/core.entity_form_display.node.az_flexible_page.default.yml
  modules/custom/az_seo/config/quickstart/core.entity_form_display.node.az_news.default.yml
  modules/custom/az_seo/config/quickstart/core.entity_form_display.node.az_person.default.yml
Labels: enhancement, usability, editor experience, needs discussion, proposal, 2.9.x only

#2934 Close #2933 Update external link field help text to mention University calendar, and to be more concise.
  modules/custom/az_event/config/install/field.field.node.az_event.field_az_link.yml
Labels: patch release, editor experience

#2937 Close #2930 Add suggested character limit of 160 to all az_summary fields.
  modules/custom/az_event/config/install/field.field.node.az_event.field_az_summary.yml
  modules/custom/az_flexible_page/config/install/field.field.node.az_flexible_page.field_az_summary.yml
  modules/custom/az_news/config/install/field.field.node.az_news.field_az_summary.yml
Labels: documentation, enhancement, editor experience, 2.9.x only

#2788 Update PHPUnit config file using lando phpunit --migrate-configuration
  phpunit.xml.dist
Labels: enhancement, ci, 2.9.x only
