Repository az-digital/az_quickstart, pull requests merged in 2024-06, with the labels that each got.

#3180 Closes #3096 Simple file system configuration change to sanitize uploaded filenames.
  config/install/file.settings.yml
Labels: enhancement, needs-CWS-testing, 2.11.x only

#3466 Removing ghost block fix for menu_block 1.11.0 update.
  themes/custom/az_barrio/templates/layout/page.html.twig
Labels: bug, enhancement, dependencies

#3464 Closes #3404: Add release notes section to PR template
  .github/pull_request_template.md
Labels: documentation

#3442 Close #2717 Update UAlert link in Global Footer
  modules/custom/az_global_footer/az_global_footer.install
  modules/custom/az_global_footer/data/az_global_footer.json
Labels: enhancement, backport, patch release

#3467 Upgrade Blazy/Slick to 3.x
  composer.json
  modules/custom/az_carousel/config/quickstart/blazy.settings.yml
  modules/custom/az_carousel/config/quickstart/slick.settings.yml
Labels: enhancement, dependencies, Drupal, 2.11.x only

#3483 Closes #3482: Update link group paragraph type to use linkit widget.
  modules/custom/az_paragraphs/az_paragraphs_link_group/az_paragraphs_link_group.info.yml
  modules/custom/az_paragraphs/az_paragraphs_link_group/az_paragraphs_link_group.install
  modules/custom/az_paragraphs/az_paragraphs_link_group/config/install/core.entity_form_display.paragraph.az_link_group.default.yml
Labels: bug, enhancement, patch release

#3494 Closes #3493 PHP warnings logged upon inserting a new Bootstrap grid
  composer.json
Labels: bug, patch release

#3481 Remove `az_google_tag`'s dependency on `ctools` and remove `ctools` from `az_quickstart`.
  az_quickstart.install
  composer.json
  modules/custom/az_google_tag/az_google_tag.info.yml
Labels: dependencies, 2.11.x only

#3502 Close #3501 remove logging code from az_course importer.
  modules/custom/az_course/az_course.module
Labels: bug, patch release

#3495 Fixes #3470 Additional Course Fields
  modules/custom/az_course/config/install/core.entity_form_display.node.az_course.default.yml
  modules/custom/az_course/config/install/core.entity_view_display.node.az_course.az_card.yml
  modules/custom/az_course/config/install/core.entity_view_display.node.az_course.default.yml
  modules/custom/az_course/config/install/core.entity_view_display.node.az_course.teaser.yml
  modules/custom/az_course/config/install/field.field.node.az_course.field_az_course_units.yml
  modules/custom/az_course/config/install/field.storage.node.field_az_course_units.yml
  modules/custom/az_course/config/install/views.view.az_courses.yml
  modules/custom/az_course/migrations/az_courses.yml
Labels: enhancement, no backport, Integrations, 2.11.x only

#3463 Closes #3396: Makes clickable cards more accessible
  modules/custom/az_card/az_card.module
  modules/custom/az_card/css/az-card-title-hover.css
  modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php
  modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php
  modules/custom/az_card/templates/az-card.html.twig
Labels: bug, enhancement, visual change, needs-CWS-testing

#3510 Closes #3335: Remove modules deprecated in 2.9.x.
  az_quickstart.install
  composer.json
Labels: dependencies, 2.11.x only, release notes

#3468 Fixes #3305 Provide Attribute Filtering for News Export
  modules/custom/az_news/az_news_export/az_news_export.views.inc
  modules/custom/az_news/az_news_export/config/install/views.view.az_news_export.yml
  modules/custom/az_news/az_news_export/src/Plugin/views/filter/AZAttributeTid.php
Labels: enhancement, Integrations, needs-CWS-testing, news, trellis, 2.11.x only

#3418 #2635, #3290: Add WebP conversion step to all included image styles.
  composer.json
  config/optional/image.style.max_1300x1300.yml
  config/optional/image.style.max_2600x2600.yml
  config/optional/image.style.max_325x325.yml
  config/optional/image.style.max_650x650.yml
  modules/custom/az_core/config/install/image.style.az_enterprise_thumbnail.yml
  modules/custom/az_core/config/install/image.style.az_enterprise_thumbnail_small.yml
  modules/custom/az_core/config/install/image.style.az_tiny_thumbnail.yml
  modules/custom/az_media/config/install/image.style.az_card_image.yml
  modules/custom/az_media/config/install/image.style.az_carousel_item.yml
  modules/custom/az_media/config/install/image.style.az_full_width_bg_extra_small.yml
  modules/custom/az_media/config/install/image.style.az_full_width_bg_large.yml
  modules/custom/az_media/config/install/image.style.az_full_width_bg_medium.yml
  modules/custom/az_media/config/install/image.style.az_full_width_bg_small.yml
  modules/custom/az_media/config/install/image.style.az_large.yml
  modules/custom/az_media/config/install/image.style.az_medium.yml
  modules/custom/az_media/config/install/image.style.az_modal_image.yml
  modules/custom/az_media/config/install/image.style.az_natural.yml
  modules/custom/az_media/config/install/image.style.az_small.yml
  modules/custom/az_media/config/install/image.style.az_square.yml
  modules/custom/az_media/config/install/image.style.az_very_small.yml
Labels: enhancement, 2.11.x only, release notes

#3419 #3290: Convert plugin annotations to attributes for plugins updated in 10.3.0.
  modules/custom/az_accordion/src/Plugin/Field/FieldFormatter/AZAccordionDefaultFormatter.php
  modules/custom/az_accordion/src/Plugin/Field/FieldType/AZAccordionItem.php
  modules/custom/az_accordion/src/Plugin/Field/FieldWidget/AZAccordionWidget.php
  modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php
  modules/custom/az_card/src/Plugin/Field/FieldType/AZCardItem.php
  modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php
  modules/custom/az_core/src/Plugin/Field/FieldFormatter/AZEnterpriseTextExportFormatter.php
  modules/custom/az_core/src/Plugin/Field/FieldWidget/AZAttributeWidget.php
  modules/custom/az_core/src/Plugin/migrate/process/ArrayIntersect.php
  modules/custom/az_core/src/Plugin/migrate/process/ManualMigrationLookup.php
  modules/custom/az_core/src/Plugin/migrate/process/PrepareArrayForSubProcess.php
  modules/custom/az_course/src/Plugin/migrate/process/CourseSquash.php
  modules/custom/az_course/src/Plugin/migrate/process/InstructorLink.php
  modules/custom/az_course/src/Plugin/migrate/process/PeopleSoftYear.php
  modules/custom/az_curated_views/src/Plugin/views/field/AZCuratedViewsField.php
  modules/custom/az_event/az_event_trellis/src/Plugin/migrate/source/AZTrellisEventSource.php
  modules/custom/az_event/az_event_trellis/src/Plugin/views/field/AZEventTrellisViewsField.php
  modules/custom/az_event/az_event_trellis/src/Plugin/views/filter/AZEventTrellisViewsApprovalFilter.php
  modules/custom/az_event/az_event_trellis/src/Plugin/views/filter/AZEventTrellisViewsAttributeFilter.php
  modules/custom/az_event/az_event_trellis/src/Plugin/views/filter/AZEventTrellisViewsDateFilter.php
  modules/custom/az_event/src/Plugin/migrate/process/SmartDateCreateRecurrenceOnField.php
  modules/custom/az_event/src/Plugin/views/filter/AZCalendarFilter.php
  modules/custom/az_finder/src/Plugin/views/exposed_form/QuickstartExposedFilters.php
  modules/custom/az_marketing_cloud/src/Plugin/views/field/AzDropbutton.php
  modules/custom/az_migration/src/Plugin/migrate/process/DateTimeToSmartDate.php
  modules/custom/az_migration/src/Plugin/migrate/process/DefaultLangcode.php
  modules/custom/az_migration/src/Plugin/migrate/process/EntityEmbedProcess.php
  modules/custom/az_migration/src/Plugin/migrate/process/MediaBundleRecognizer.php
  modules/custom/az_migration/src/Plugin/migrate/process/MigratedPathLookup.php
  modules/custom/az_migration/src/Plugin/migrate/process/ParagraphMappingFlexiblePage.php
  modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsCalloutFieldMerge.php
  modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsChunksViewDisplayMapping.php
  modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsColumnImageFieldMerge.php
  modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsExtraInfoFieldMerge.php
  modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsFWMediaRowFieldMerge.php
  modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsFileDownloadFieldMerge.php
  modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsJumbotronFieldMerge.php
  modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsUpdateMediaCaption.php
  modules/custom/az_migration/src/Plugin/migrate/process/TextFormatRecognizer.php
  modules/custom/az_migration/src/Plugin/migrate/process/ViewsReferenceMapping.php
  modules/custom/az_news/az_news_export/src/Plugin/views/row/AZNewsDataFieldRow.php
  modules/custom/az_paragraphs/src/Plugin/Field/FieldFormatter/AZBackgroundMediaFormatter.php
  modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehaviorSettings.php
  modules/custom/az_publication/src/Plugin/Filter/AZDOIFilter.php
  modules/custom/az_publication/src/Plugin/views/argument/AZCitationStyleArgument.php
Labels: enhancement, Drupal, 2.11.x only

#2781 Fixes #2778 Cron Migration settings for Enterprise Attributes
  modules/custom/az_core/az_enterprise_attributes_import/az_enterprise_attributes_import.info.yml
  modules/custom/az_core/az_enterprise_attributes_import/az_enterprise_attributes_import.install
  modules/custom/az_core/az_enterprise_attributes_import/az_enterprise_attributes_import.module
  modules/custom/az_core/az_enterprise_attributes_import/az_enterprise_attributes_import.services.yml
  modules/custom/az_core/az_enterprise_attributes_import/config/install/migrate_plus.migration.az_enterprise_attributes_import.yml
  modules/custom/az_core/az_enterprise_attributes_import/config/install/migrate_plus.migration_group.az_enterprise_attributes_import.yml
  modules/custom/az_core/az_enterprise_attributes_import/config/install/migrate_queue_importer.cron_migration.az_enterprise_attributes_import.yml
  modules/custom/az_core/az_enterprise_attributes_import/src/EventSubscriber/AZEnterpriseAttributesMigrationSync.php
  modules/custom/az_news/az_news_export/src/Plugin/views/row/AZNewsDataFieldRow.php
Labels: enhancement, no backport, patch release, Integrations, needs-CWS-testing, trellis, 2.11.x only
