Repository az-digital/az_quickstart, pull requests merged in 2024-01, with the labels that each got.

#3040 #2084: Add DB update to uninstall now unsupported media_library_theme_reset module.
  az_quickstart.install
Labels: dependencies, patch release

#3064 Closes #3063 Fix permissions for reverting block content
  config/install/user.role.az_content_editor.yml
Labels: bug, 2.9.x only

#3066 Closes #3065: Remove text decoration from links in az_publication.module
  modules/custom/az_publication/az_publication.module
Labels: enhancement, backport, patch release, visual change, user experience

#3061 Closes #2757: Fix typo in README.md
  README.md
Labels: bug, documentation

#3056 Close #2800 Update Global Footer with new X/Twitter Icon.
  modules/custom/az_global_footer/az_global_footer.install
  modules/custom/az_global_footer/data/az_global_footer.json
Labels: enhancement, patch release, visual change

#3083 Closes #3082 Vertical tabs in Media Library modal are missing styling
  composer.json
Labels: bug, 2.9.x only

#3072 Closes #3060 - Fix CKEditor editor experience to match previous version
  config/install/editor.editor.basic_html.yml
  modules/custom/az_paragraphs/config/optional/editor.editor.az_standard.yml
  themes/custom/az_barrio/css/ckeditor5.css
Labels: bug, enhancement, patch release, editor experience

#3078 Closes #3077: Address PHP 8.1+ deprecation warnings caused by card links with empty URLs.
  modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php
Labels: bug, patch release, php

#3031 Fixes #3030 Link Publication Titles to Node.
  modules/custom/az_publication/az_publication.module
Labels: enhancement, user experience, 2.9.x only

#3085 Closes #3084 Event edit page displays User deprecated function error
  composer.json
Labels: bug, 2.9.x only

#3080 Closes #3079 Standardize Previous and Next links in full pagers of views
  modules/custom/az_news/config/install/views.view.az_news.yml
Labels: visual change, 2.10.x only

#3098 #3099 Update Drupal core to 10.1.8 for SA-CORE-2024-001 (2.8.x)
  composer.json
Labels: dependencies, high priority, Drupal, 2.8.x only

#3100 #3099 Update Drupal core to 10.2.2 for SA-CORE-2024-001
  composer.json
Labels: dependencies, high priority, Drupal, 2.9.x only

#2759 Closes #2758: Add patch to address Easy Breadcrumb deprecation warnings.
  composer.json
Labels: bug, dependencies, Drupal, patch release, php

#3107 Closes #3102 Some CKEditor editable tags are removed and can't be restored
  modules/custom/az_paragraphs/config/optional/editor.editor.az_standard.yml
Labels: bug, high priority, 2.9.x only

#3105 Close #3104 fix typo in az_news_feeds schema.
  modules/custom/az_news/az_news_feeds/config/schema/az_news_feeds.schema.yml
Labels: bug, patch release

#3114 Closes #3113 Standard text format cannot be edited in the UI without removing allowed tags
  composer.json
Labels: bug, blocker, 2.9.x only

#3058 Fixes #3012 Fixes #3119 Digital Object Identifiers to hyperlinks
  modules/custom/az_publication/az_publication.module
  modules/custom/az_publication/config/install/filter.format.az_citation.yml
  modules/custom/az_publication/src/Plugin/Filter/AZDOIFilter.php
Labels: enhancement, high priority, patch release, visual change, usability, user experience, needs discussion, 2.9.x only

#2861 Closes #2855: Full-width background padding
  modules/custom/az_demo/az_demo.module
  modules/custom/az_demo/data/az_demo_menu_links.json
  modules/custom/az_demo/data/az_demo_page_node.json
  modules/custom/az_paragraphs/az_paragraphs_splitscreen/css/az_splitscreen.css
  modules/custom/az_paragraphs/az_paragraphs_text_background/templates/paragraph--az-text-background--default.html.twig
  modules/custom/az_paragraphs/css/az_paragraphs_full_width.css
Labels: bug, visual change, 2.10.x only

#2594 Closes #2550 Add support for future dates by setting publication status to "forthcoming"
  modules/custom/az_publication/az_publication.module
  modules/custom/az_publication/config/install/az_publication.az_citation_style.az_bluebook.yml
Labels: enhancement, patch release, 2.9.x only

#3057 Closes #1015 Update styles for full pager to work better on mobile
  themes/custom/az_barrio/css/style.css
  themes/custom/az_barrio/templates/navigation/pager.html.twig
Labels: usability, user experience, 2.10.x only

#3124 Closes #1275: Enable row display plugin for node content embed button.
  modules/custom/az_paragraphs/config/optional/embed.button.az_embed_content.yml
Labels: enhancement, 2.10.x only
