Repository az-digital/az_quickstart, pull requests merged in 2024-04, with the labels that each got.

#3303 Closes #3241: Add DB update for fixing langcode on migrated menu links and add DefaultLangcode migrate plugin.
  az_quickstart.install
  modules/custom/az_migration/README.md
  modules/custom/az_migration/migrations/az_menu_links.yml
  modules/custom/az_migration/migrations/az_node_carousel.yml
  modules/custom/az_migration/migrations/az_node_event.yml
  modules/custom/az_migration/migrations/az_node_flexible_page.yml
  modules/custom/az_migration/migrations/az_node_news.yml
  modules/custom/az_migration/migrations/az_node_person.yml
  modules/custom/az_migration/migrations/az_node_uaqs_basic_page_to_az_page.yml
  modules/custom/az_migration/src/Plugin/migrate/process/DefaultLangcode.php
Labels: bug, migration, patch release

#3284 Closes #3233 Auto-Import for Trellis Events
  modules/custom/az_event/az_event_trellis/az_event_trellis.links.action.yml
  modules/custom/az_event/az_event_trellis/az_event_trellis.links.task.yml
  modules/custom/az_event/az_event_trellis/az_event_trellis.module
  modules/custom/az_event/az_event_trellis/az_event_trellis.routing.yml
  modules/custom/az_event/az_event_trellis/config/schema/az_event_trellis.schema.yml
  modules/custom/az_event/az_event_trellis/src/AZRecurringImportRuleInterface.php
  modules/custom/az_event/az_event_trellis/src/AZRecurringImportRuleListBuilder.php
  modules/custom/az_event/az_event_trellis/src/Controller/AZRecurringImportModalController.php
  modules/custom/az_event/az_event_trellis/src/Entity/AZRecurringImportRule.php
  modules/custom/az_event/az_event_trellis/src/Form/AZRecurringImportRuleForm.php
  modules/custom/az_event/az_event_trellis/src/Plugin/migrate/source/AZTrellisEventSource.php
  modules/custom/az_event/az_event_trellis/src/Plugin/views/filter/AZEventTrellisViewsAttributeFilter.php
  modules/custom/az_event/az_event_trellis/src/TrellisHelper.php
Labels: high priority, Integrations, editor experience, trellis, 2.10.x only

#2998 Closes #2997: Add better exposed filter plugin that transforms a taxonomy vocabulary into a nested list of filters for a view.
  modules/custom/az_demo/config/install/views.view.az_finder.yml
  modules/custom/az_finder/az_finder.libraries.yml
  modules/custom/az_finder/az_finder.module
  modules/custom/az_finder/az_finder.services.yml
  modules/custom/az_finder/css/taxonomy-index-tid-widget.css
  modules/custom/az_finder/js/taxonomy-index-tid-widget.es6.js
  modules/custom/az_finder/js/taxonomy-index-tid-widget.js
  modules/custom/az_finder/src/AZFinderIcons.php
  modules/custom/az_finder/src/Plugin/better_exposed_filters/filter/AZFinderTaxonomyIndexTidWidget.php
  modules/custom/az_finder/templates/az-finder-nested-elements.html.twig
  modules/custom/az_finder/templates/az-finder-widget.html.twig
  modules/custom/az_finder/tests/AZFinderIconsTest.php
Labels: enhancement, high priority, visual change, 2.10.x only

#3255 Closes #2357 Add better metatag defaults for Quickstart
  modules/custom/az_core/az_core.module
  modules/custom/az_seo/config/quickstart/metatag.metatag_defaults.node.yml
  modules/custom/az_seo/config/quickstart/metatag.metatag_defaults.node__az_event.yml
  modules/custom/az_seo/config/quickstart/metatag.metatag_defaults.node__az_news.yml
  modules/custom/az_seo/config/quickstart/metatag.metatag_defaults.node__az_person.yml
Labels: enhancement, QS1 feature parity, 2.10.x only

#3306 Closes #3304: Add Quickstart Exposed Filter options to existing views
  modules/custom/az_finder/config/quickstart/views.view.az_events.yml
  modules/custom/az_finder/config/quickstart/views.view.az_news.yml
  modules/custom/az_finder/config/quickstart/views.view.az_page_by_category.yml
  modules/custom/az_finder/config/quickstart/views.view.az_person.yml
Labels: enhancement, high priority, editor experience, 2.10.x only

#3267 #3266: Add additional modules for configuration staging workflow(s).
  composer.json
  config/optional/config_ignore.settings.yml
Labels: enhancement, dependencies, 2.10.x only, developer experience

#3316 Closes #3315: Fix security GH actions workflow.
  .github/workflows/security.yml
Labels: bug, ci, patch release

#3328 Prepare repository for new minor release branch 2.10.x
  composer.json
Labels: 2.11.x only

#3331 Close #3330 Ensure Recurring Import Rule entity type is installed during update.
  modules/custom/az_event/az_event_trellis/az_event_trellis.install
Labels: bug, blocker, 2.10.x only

#3345 Closes #3344 Some meta tags are missing in 2.10.x
  modules/custom/az_seo/config/install/metatag.metatag_defaults.node__az_event.yml
  modules/custom/az_seo/config/install/metatag.metatag_defaults.node__az_news.yml
  modules/custom/az_seo/config/install/metatag.metatag_defaults.node__az_person.yml
  modules/custom/az_seo/config/quickstart/metatag.metatag_defaults.front.yml
Labels: bug, 2.10.x only

#3336 Closes #3334 Remove modules deprecated as of 2.8.x.
  az_quickstart.install
  composer.json
  modules/custom/az_digital_asset_library/az_digital_asset_library.install
  modules/custom/az_paragraphs/config/optional/embed.button.az_embed_content.yml
  modules/custom/az_paragraphs/config/optional/embed.button.az_embed_content_block.yml
Labels: dependencies, 2.10.x only

#3348 Fixes #3347, Fixes #3338 Allow QuickstartConfigProvider to ignore some Diff types.
  modules/custom/az_core/src/AZConfigOverride.php
  modules/custom/az_core/src/Plugin/ConfigProvider/QuickstartConfigProvider.php
Labels: bug, blocker, 2.10.x only

#2041 Closes #2037 - Make card titles configurable
  modules/custom/az_card/az_card.module
  modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php
  modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php
  modules/custom/az_card/templates/az-card.html.twig
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZCardsParagraphBehavior.php
Labels: enhancement, editor experience, needs discussion, 2.10.x only

#3295 Closes #3218 Reduce carousel item width to 1110px
  modules/custom/az_media/config/install/image.style.az_carousel_item.yml
Labels: bug, patch release, visual change

#3297 Closes #3214 Update carousel image help text
  modules/custom/az_carousel/config/install/field.field.node.az_carousel_item.field_az_media_image.yml
Labels: bug, documentation, patch release, needs-CWS-testing, editor experience

#3353 Closes #3352: Update CONTRIBUTING.md file with information about issues and PRs.
  CONTRIBUTING.md
  README.md
Labels: documentation, enhancement, developer experience

#3376 Close #3375 Install AZ Finder module if AZ Demo module is already installed.
  modules/custom/az_demo/az_demo.install
Labels: bug

#3366 Closes #3365: Set Easy Breadcrumb preferred menu setting to main menu by default.
  config/install/easy_breadcrumb.settings.yml
Labels: enhancement, usability, editor experience

#3363 Closes #3307: Add reset order button to draggable views.
  composer.json
  modules/custom/az_carousel/config/install/views.view.az_carousel.yml
  modules/custom/az_person/config/install/views.view.az_reorder.yml
Labels: enhancement, patch release
