Repository az-digital/az_quickstart, pull requests merged in 2024-09, with the labels that each got.

#3687 Closes #3686 Empty view blocks causing sidebar region to render.
  themes/custom/az_barrio/templates/layout/page.html.twig
Labels: bug, patch release, 2.11.x only

#3680 Fixes #3678 Add Generator Metatag
  modules/custom/az_core/az_core.module
  modules/custom/az_core/az_core.services.yml
  modules/custom/az_core/src/EventSubscriber/AZGeneratorSubscriber.php
Labels: enhancement, no backport, 2.12.x only

#3684 Close #3683 use migmag_lookup instead of migrate_lookup
  modules/custom/az_migration/README.md
  modules/custom/az_migration/az_migration.info.yml
  modules/custom/az_migration/az_migration.install
  modules/custom/az_migration/migrations/az_block_content_flexible_block.yml
  modules/custom/az_migration/migrations/az_cas_user.yml
  modules/custom/az_migration/migrations/az_event_categories.yml
  modules/custom/az_migration/migrations/az_exclude_node_title.yml
  modules/custom/az_migration/migrations/az_files.yml
  modules/custom/az_migration/migrations/az_flexible_page_categories.yml
  modules/custom/az_migration/migrations/az_media.yml
  modules/custom/az_migration/migrations/az_news_tags.yml
  modules/custom/az_migration/migrations/az_node_carousel.yml
  modules/custom/az_migration/migrations/az_node_event.yml
  modules/custom/az_migration/migrations/az_node_flexible_page.yml
  modules/custom/az_migration/migrations/az_node_news.yml
  modules/custom/az_migration/migrations/az_node_person.yml
  modules/custom/az_migration/migrations/az_node_uaqs_basic_page_to_az_page.yml
  modules/custom/az_migration/migrations/az_paragraph_card_deck.yml
  modules/custom/az_migration/migrations/az_paragraph_carousel.yml
  modules/custom/az_migration/migrations/az_paragraph_column_image.yml
  modules/custom/az_migration/migrations/az_paragraph_content_marquee.yml
  modules/custom/az_migration/migrations/az_paragraph_file_download.yml
  modules/custom/az_migration/migrations/az_paragraph_full_width_media_row.yml
  modules/custom/az_migration/migrations/az_paragraph_gallery.yml
  modules/custom/az_migration/migrations/az_person_categories.yml
  modules/custom/az_migration/migrations/az_person_categories_secondary.yml
  modules/custom/az_migration/migrations/az_redirects.yml
  modules/custom/az_migration/migrations/az_user.yml
  modules/custom/az_migration/src/Plugin/migrate/process/MigratedPathLookup.php
  modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsColumnImageFieldMerge.php
  modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsFileDownloadFieldMerge.php
Labels: enhancement, migration, patch release

#3701 Closes #3700: Update drupal/core-recommended to 10.3.4.
  composer.json
Labels: bug, dependencies, Drupal

#3729 Closes #3723 Card title on image is red when the card is not clickable
  modules/custom/az_card/css/az-card-title-hover.css
  modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php
  modules/custom/az_card/templates/az-card.html.twig
Labels: bug, patch release

#3732 Close #3730 mark minified JS as minified.
  modules/custom/az_event/az_event_trellis/az_event_trellis.libraries.yml
  modules/custom/az_publication/az_publication.libraries.yml
  themes/custom/az_barrio/az_barrio.libraries.yml
Labels: bug, patch release, 2.11.x only

#3727 For #3705 Menu blocks intermittently not visible to anonymous users after updating to Quickstart 2.11
  composer.json
Labels: bug, high priority, 2.11.x only

#3728 Closes #3725: Hard code higher WebP conversion quality setting until configurable for GD in core.
  composer.json
Labels: bug, patch release, 2.11.x only

#3719 Closes #3718 Improve styling of AZ Finder exposed form, especially for multiple vocabulary filters
  modules/custom/az_finder/css/taxonomy-index-tid-widget.css
  modules/custom/az_finder/src/Plugin/better_exposed_filters/filter/AZFinderTaxonomyIndexTidWidget.php
Labels: enhancement, backport, patch release, visual change

#3715 Closes #3714 Extra main landmark role in page template
  themes/custom/az_barrio/templates/layout/page.html.twig
Labels: bug, patch release, accessibility, release notes

#3570 Fixes #3074, Fixes #3568 Course Importer Missing Content, Course Instructor Person Links
  composer.json
  modules/custom/az_course/migrations/az_courses.yml
  modules/custom/az_course/src/Plugin/migrate/process/InstructorLink.php
Labels: enhancement, no backport, patch release, Integrations, 2.11.x only

#3738 Fixes #3737 SlevomatCodingStandards
  modules/custom/az_core/az_core.module
  modules/custom/az_core/src/AZConfigOverride.php
  modules/custom/az_core/src/Drush/Commands/AZCoreConfigCommands.php
  modules/custom/az_core/src/Plugin/ConfigProvider/QuickstartConfigProvider.php
  modules/custom/az_core/tests/src/Functional/QuickstartFunctionalTestBase.php
  modules/custom/az_course/src/Form/CourseImportForm.php
  modules/custom/az_demo/az_demo.module
  modules/custom/az_event/az_event_trellis/az_event_trellis.module
  modules/custom/az_event/az_event_trellis/src/Entity/AZRecurringImportRule.php
  modules/custom/az_event/az_event_trellis/src/EventSubscriber/AZEventTrellisDataSubscriber.php
  modules/custom/az_event/az_event_trellis/src/Form/AZRecurringImportRuleForm.php
  modules/custom/az_event/az_event_trellis/src/Plugin/migrate/source/AZTrellisEventSource.php
  modules/custom/az_event/az_event_trellis/src/Plugin/views/field/AZEventTrellisViewsField.php
  modules/custom/az_event/az_event_trellis/src/TrellisHelper.php
  modules/custom/az_finder/src/Form/AZFinderSettingsForm.php
  modules/custom/az_finder/src/Plugin/better_exposed_filters/filter/AZFinderTaxonomyIndexTidWidget.php
  modules/custom/az_finder/src/Plugin/views/exposed_form/QuickstartExposedFilters.php
  modules/custom/az_http/src/AZHttpRetryMiddleware.php
  modules/custom/az_http/src/Strategy/AZPoliteCacheStrategy.php
  modules/custom/az_migration/src/Plugin/migrate/process/MigratedPathLookup.php
  modules/custom/az_news/az_news_export/src/Plugin/views/row/AZNewsDataFieldRow.php
  modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehaviorSettings.php
  modules/custom/az_paragraphs/tests/src/Unit/AZVideoEmbedHelperTest.php
  modules/custom/az_publication/az_publication.module
  modules/custom/az_publication/src/AZAuthorStorage.php
  modules/custom/az_publication/src/AZAuthorStorageInterface.php
  modules/custom/az_publication/src/Controller/AZAuthorController.php
  modules/custom/az_publication/src/Form/AZAuthorRevisionRevertForm.php
  modules/custom/az_publication/src/Form/AZAuthorRevisionRevertTranslationForm.php
Labels: task, developer experience

#3677 Fixes #3676 Course Display Changes
  modules/custom/az_course/az_course.module
  modules/custom/az_course/config/install/core.entity_view_display.node.az_course.az_card.yml
  modules/custom/az_course/config/install/core.entity_view_display.node.az_course.default.yml
  modules/custom/az_course/templates/field--node--field-az-course-instructor--az-course.html.twig
Labels: visual change, 2.12.x only
