Repository az-digital/az_quickstart, pull requests merged in 2024-11, with the labels that each got.

#3853 Fixes #3852 Citation Style Group Rendering
  composer.json
Labels: patch release, publications

#3815 Close #3813 set default format to plain_text in flexible page summary field migration.
  modules/custom/az_migration/migrations/az_node_flexible_page.yml
Labels: bug, migration, patch release, release notes

#3847 Closes #3228: Change featured image to thumbnail image in Marketing Cloud layouts
  modules/custom/az_marketing_cloud/az_marketing_cloud.module
  modules/custom/az_marketing_cloud/config/install/core.entity_view_display.node.az_news.az_marketing_cloud_30_70_layout.yml
  modules/custom/az_marketing_cloud/config/install/core.entity_view_display.node.az_news.az_marketing_cloud_50_50_layout.yml
  modules/custom/az_marketing_cloud/config/install/core.entity_view_display.node.az_news.az_marketing_cloud_50_50_layout_image_right.yml
  modules/custom/az_marketing_cloud/config/install/core.entity_view_display.node.az_news.az_marketing_cloud_70_30_layout_image_right.yml
  modules/custom/az_marketing_cloud/config/install/core.entity_view_display.node.az_news.az_marketing_cloud_hero_layout.yml
Labels: patch release, Integrations, release notes, 2.12.x only

#1387 Closes #1273 Closes #3848: Allow multiple select menus on the same page
  modules/custom/az_select_menu/js/az-select-menu.es6.js
  modules/custom/az_select_menu/js/az-select-menu.js
  modules/custom/az_select_menu/src/Plugin/Block/AzSelectMenu.php
  modules/custom/az_select_menu/templates/az-select-menu.html.twig
Labels: bug, enhancement, patch release, accessibility, 2.12.x only

#3875 Fixes #3874 Modules using Configuration Overrides should declare az_core dependency
  modules/custom/az_digital_asset_library/az_digital_asset_library.info.yml
  modules/custom/az_finder/az_finder.info.yml
  modules/custom/az_google_tag/az_google_tag.info.yml
  modules/custom/az_seo/az_seo.info.yml
Labels: bug, patch release, needs-CWS-testing

#3864 Fixes #3823 Card Widget Deprecation Notices
  modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php
Labels: bug, patch release, editor experience

#3872 Closes #3870 Revert #3219: Add anchor link plugin for CKEditor5
  composer.json
  modules/custom/az_paragraphs/az_paragraphs.info.yml
  modules/custom/az_paragraphs/az_paragraphs.install
  modules/custom/az_paragraphs/az_paragraphs.module
  modules/custom/az_paragraphs/config/optional/editor.editor.az_standard.yml
Labels: bug, 2.12.x only

#3867 Close #3861 Change scope of spaceless filter from all elements to AZ Person headings
  modules/custom/az_person/az_person.module
  modules/custom/az_person/templates/field-group-html-element--node--az-person--h1.html.twig
  modules/custom/az_person/templates/field-group-html-element--node--az-person--h2.html.twig
  modules/custom/az_person/templates/field-group-html-element--node--az-person--h3.html.twig
Labels: bug, needs discussion

#3895 #3893: Update drupal/core-recommended from 10.2.10 to 10.2.11 (addresses multiple security vulnerabilities).
  .probo.yaml
  composer.json
Labels: dependencies, high priority, Drupal, patch release, 2.10.x only, release notes

#3894 #3893: Update drupal/core-recommended from 10.3.6 to 10.3.9 (addresses multiple security advisories).
  .probo.yaml
  composer.json
Labels: dependencies, high priority, Drupal, patch release, release notes

#3851 Closes #3850: Update Quickstart content type views to have sticky at top of lists respected
  modules/custom/az_event/config/install/views.view.az_events.yml
  modules/custom/az_finder/config/quickstart/views.view.az_events.yml
  modules/custom/az_finder/config/quickstart/views.view.az_news.yml
  modules/custom/az_finder/config/quickstart/views.view.az_page_by_category.yml
  modules/custom/az_finder/config/quickstart/views.view.az_person.yml
  modules/custom/az_flexible_page/config/install/views.view.az_page_by_category.yml
  modules/custom/az_news/config/install/views.view.az_news.yml
  modules/custom/az_person/config/install/views.view.az_person.yml
  modules/custom/az_person/config/install/views.view.az_reorder.yml
Labels: enhancement, visual change, release notes, 2.13.x only

#3400 Closes #3391: Hyperlink Land Acknowledgement text in the Global Footer
  themes/custom/az_barrio/az_barrio.theme
Labels: enhancement, patch release

#3909 Close #3903 Add schema_metatag module as dependency of az_seo
  composer.json
  modules/custom/az_seo/az_seo.info.yml
  modules/custom/az_seo/az_seo.install
Labels: high priority, patch release
