Repository az-digital/az_quickstart, pull requests merged in 2024-05, with the labels that each got.

#3392 Closes #3174. Made text area not required on az_text_background.
  modules/custom/az_paragraphs/az_paragraphs_text_background/config/install/field.field.paragraph.az_text_background.field_az_text_area.yml
Labels: enhancement, good first issue, editor experience, 2.11.x only

#3388 Close #3385 Remove redundant permissions in "Content Administrator" role.
  config/install/user.role.az_content_admin.yml
Labels: enhancement, low priority, 2.11.x only

#3393 Closes #3339 New breakpoint to hide arrows on small displays
  modules/custom/az_carousel/config/install/slick.optionset.center_mode.yml
Labels: enhancement, low priority, patch release, visual change

#3378 Close #3377 require "Access Draggableviews" permission to access carousel items draggable view.
  modules/custom/az_carousel/config/install/views.view.az_carousel.yml
Labels: bug, backport, patch release

#3275 Closes #2735 Additional content type displays for AZ Side-by-Side Views
  modules/custom/az_flexible_page/config/install/core.entity_view_display.node.az_flexible_page.az_row_with_background.yml
  modules/custom/az_paragraphs/az_paragraphs_views_side_by_side/config/install/views.view.az_side_by_side_views.yml
  modules/custom/az_person/config/install/core.entity_view_display.node.az_person.az_row_with_background.yml
Labels: enhancement, patch release

#3409 Closes #3405: Add config_readonly patch for ConfigEntityListBuilder forms.
  composer.json
Labels: bug, dependencies, patch release, 2.10.x only

#3337 Close #3329 Update prepare repository for minor release action so that it updates the main branch version alias as a pull request.
  .github/workflows/prepare-for-minor-release.yml
Labels: ci, 2.11.x only

#3425 Closes #3424 Update for changes in the YouTube API to fix videos not playing automatically
  modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_youtube.es6.js
  modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_youtube.js
Labels: bug, backport, high priority, patch release

#3152 Closes #3151 Update NodeJS in ProboCI config to version 20.13.0.
  .eslintrc.json
  .lando.yml
  .probo.yaml
  modules/custom/az_select_menu/js/az-select-menu.js
  package.json
  themes/custom/az_barrio/js/az-ajax.js
Labels: enhancement, ci, dependencies, 2.11.x only
