Repository az-digital/az_quickstart, pull requests merged in 2024-02, with the labels that each got.

#3140 Closes #2301 Add Very Small media display
  modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_very_small.yml
  modules/custom/az_media/config/install/core.entity_view_mode.media.az_very_small.yml
  modules/custom/az_media/config/install/filter.format.az_standard.yml
  modules/custom/az_media/config/install/image.style.az_very_small.yml
Labels: enhancement, low priority, editor experience, 2.10.x only

#3121 Closes #3035: Add 'Configure' Links to Quickstart Modules
  modules/custom/az_cas/az_cas.info.yml
  modules/custom/az_core/az_core.info.yml
  modules/custom/az_core/az_enterprise_attributes_import/az_enterprise_attributes_import.info.yml
  modules/custom/az_publication/az_publication.info.yml
Labels: enhancement, user experience, 2.10.x only

#3146 Close #2054 Note that any Drush version lower than`12.4.3` will cause a conflict, and add `az-entity-list:list` drush command.
  composer.json
  modules/custom/az_core/drush.services.yml
  modules/custom/az_core/src/Commands/README.md
  modules/custom/az_core/src/Drush/Commands/AZCoreConfigCommands.php
  modules/custom/az_core/src/Drush/Commands/AZEntityListCommands.php
  modules/custom/az_core/src/Drush/Commands/README.md
Labels: enhancement, QS1 feature parity

#2966 Fixes #2964, Fixes #2957 Add Filters on Published/Approved Events
  modules/custom/az_event/az_event_trellis/az_event_trellis.views.inc
  modules/custom/az_event/az_event_trellis/config/install/views.view.az_event_trellis_import.yml
  modules/custom/az_event/az_event_trellis/src/EventSubscriber/AZEventTrellisDataSubscriber.php
  modules/custom/az_event/az_event_trellis/src/Plugin/views/filter/AZEventTrellisViewsApprovalFilter.php
Labels: enhancement, backport, patch release, needs discussion, trellis

#3133 Fixes #3071 Add additional Publication Identifiers
  modules/custom/az_publication/az_publication.module
  modules/custom/az_publication/az_publication_bibtex/migrations/az_publication_bibtex_import.yml
  modules/custom/az_publication/config/install/core.entity_form_display.node.az_publication.default.yml
  modules/custom/az_publication/config/install/core.entity_view_display.node.az_publication.az_card.yml
  modules/custom/az_publication/config/install/core.entity_view_display.node.az_publication.az_publication_reference.yml
  modules/custom/az_publication/config/install/core.entity_view_display.node.az_publication.default.yml
  modules/custom/az_publication/config/install/core.entity_view_display.node.az_publication.teaser.yml
  modules/custom/az_publication/config/install/core.entity_view_mode.node.az_publication_reference.yml
  modules/custom/az_publication/config/install/field.field.node.az_publication.field_az_publication_isbn.yml
  modules/custom/az_publication/config/install/field.field.node.az_publication.field_az_publication_issn.yml
  modules/custom/az_publication/config/install/field.field.node.az_publication.field_az_publication_pmcid.yml
  modules/custom/az_publication/config/install/field.storage.node.field_az_publication_isbn.yml
  modules/custom/az_publication/config/install/field.storage.node.field_az_publication_issn.yml
  modules/custom/az_publication/config/install/field.storage.node.field_az_publication_pmcid.yml
Labels: enhancement, patch release, editor experience, 2.9.x only

#3166 Closes #3120: Adding viewsreference patch to fix cache issues for views without empty handling.
  composer.json
Labels: bug, backport, dependencies, high priority, Drupal, patch release

#3154 Closes #3153 Duplicate H1 on person pages tripping up some crawlers
  modules/custom/az_person/config/install/core.entity_view_display.node.az_person.default.yml
Labels: bug, backport, patch release, accessibility

#3167 Closes #3162: Remove hard-coded slick_ui dependency from az_carousel.
  modules/custom/az_carousel/az_carousel.info.yml
Labels: bug, enhancement, dependencies, patch release

#3170 Closes #1428 Carousel off center at display size above 1750 px wide
  modules/custom/az_carousel/config/install/slick.optionset.center_mode.yml
  modules/custom/az_carousel/css/az_carousel.css
Labels: bug, backport, patch release, visual change

#3184 Partially fixes #3125 Linkit creating node based link paths (2.9.x only)
  composer.json
Labels: bug, high priority, patch release, 2.9.x only

#3111 Closes #3110: Add viewsreference module patch to fix field config schema issues
  composer.json
  modules/custom/az_paragraphs/az_paragraphs_view/config/install/field.field.paragraph.az_view_reference.field_az_view_reference.yml
  modules/custom/az_paragraphs/az_paragraphs_views_side_by_side/config/install/field.field.paragraph.az_views_side_by_side.field_az_second_view.yml
  modules/custom/az_paragraphs/az_paragraphs_views_side_by_side/config/install/field.field.paragraph.az_views_side_by_side.field_az_view_reference.yml
Labels: bug, dependencies, high priority, Drupal, patch release

#3193 Closes #3191 Remove patch for drupal.org/i/3163925
  composer.json
Labels: bug, backport, dependencies, Drupal, patch release

#3187 Closes #3185 Workbench Access menu schemes may cause menu items to change when pages are saved
  composer.json
Labels: bug, patch release, editor experience

#2925 Closes #2904 - Add link group paragraph type
  modules/custom/az_paragraphs/az_paragraphs_link_group/az_paragraphs_link_group.info.yml
  modules/custom/az_paragraphs/az_paragraphs_link_group/az_paragraphs_link_group.module
  modules/custom/az_paragraphs/az_paragraphs_link_group/config/install/core.entity_form_display.paragraph.az_link_group.default.yml
  modules/custom/az_paragraphs/az_paragraphs_link_group/config/install/core.entity_view_display.paragraph.az_link_group.default.yml
  modules/custom/az_paragraphs/az_paragraphs_link_group/config/install/field.field.paragraph.az_link_group.field_az_link_item.yml
  modules/custom/az_paragraphs/az_paragraphs_link_group/config/install/field.field.paragraph.az_link_group.field_az_title.yml
  modules/custom/az_paragraphs/az_paragraphs_link_group/config/install/field.storage.paragraph.field_az_link_item.yml
  modules/custom/az_paragraphs/az_paragraphs_link_group/config/install/paragraphs.paragraphs_type.az_link_group.yml
  modules/custom/az_paragraphs/az_paragraphs_link_group/templates/paragraph--az-link-group--default.html.twig
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZLinkGroupParagraphBehavior.php
Labels: enhancement, editor experience, 2.10.x only

#3195 Closes #3190: Add core patch for BigPipe Javascript error(s) on node add/edit pages.
  composer.json
Labels: bug, dependencies, Drupal, patch release

#1465 Close #3186 Use Composer to track az-icons package, and add ability for site owner to choose how az-icon library is loaded.
  .github/workflows/az-icons-release.yml
  composer.json
  themes/custom/az_barrio/az_barrio.libraries.yml
  themes/custom/az_barrio/az_barrio.theme
  themes/custom/az_barrio/config/install/az_barrio.settings.yml
  themes/custom/az_barrio/config/schema/az_barrio.schema.yml
  themes/custom/az_barrio/includes/common.inc
  themes/custom/az_barrio/libraries/az-icons/az-icons-styles.css
  themes/custom/az_barrio/libraries/az-icons/fonts/az-icons.eot
  themes/custom/az_barrio/libraries/az-icons/fonts/az-icons.svg
  themes/custom/az_barrio/libraries/az-icons/fonts/az-icons.ttf
  themes/custom/az_barrio/libraries/az-icons/fonts/az-icons.woff
  themes/custom/az_barrio/libraries/az-icons/png/arizona.png
  themes/custom/az_barrio/libraries/az-icons/png/award.png
  themes/custom/az_barrio/libraries/az-icons/png/cost.png
  themes/custom/az_barrio/libraries/az-icons/png/facebook.png
  themes/custom/az_barrio/libraries/az-icons/png/financial-aid.png
  themes/custom/az_barrio/libraries/az-icons/png/grad-cap.png
  themes/custom/az_barrio/libraries/az-icons/png/instagram.png
  themes/custom/az_barrio/libraries/az-icons/png/linkedin.png
  themes/custom/az_barrio/libraries/az-icons/png/majors-and-degrees.png
  themes/custom/az_barrio/libraries/az-icons/png/map-marker.png
  themes/custom/az_barrio/libraries/az-icons/png/pinterest.png
  themes/custom/az_barrio/libraries/az-icons/png/scholarship.png
  themes/custom/az_barrio/libraries/az-icons/png/sign-post.png
  themes/custom/az_barrio/libraries/az-icons/png/spotify.png
  themes/custom/az_barrio/libraries/az-icons/png/spring-fling.png
  themes/custom/az_barrio/libraries/az-icons/png/tiktok.png
  themes/custom/az_barrio/libraries/az-icons/png/twitter.png
  themes/custom/az_barrio/libraries/az-icons/png/vimeo.png
  themes/custom/az_barrio/libraries/az-icons/png/wildcat.png
  themes/custom/az_barrio/libraries/az-icons/png/youtube.png
  themes/custom/az_barrio/libraries/az-icons/svg/arizona.svg
  themes/custom/az_barrio/libraries/az-icons/svg/award.svg
  themes/custom/az_barrio/libraries/az-icons/svg/cost.svg
  themes/custom/az_barrio/libraries/az-icons/svg/facebook.svg
  themes/custom/az_barrio/libraries/az-icons/svg/financial-aid.svg
  themes/custom/az_barrio/libraries/az-icons/svg/grad-cap.svg
  themes/custom/az_barrio/libraries/az-icons/svg/instagram.svg
  themes/custom/az_barrio/libraries/az-icons/svg/linkedin.svg
  themes/custom/az_barrio/libraries/az-icons/svg/majors-and-degrees.svg
  themes/custom/az_barrio/libraries/az-icons/svg/map-marker.svg
  themes/custom/az_barrio/libraries/az-icons/svg/pinterest.svg
  themes/custom/az_barrio/libraries/az-icons/svg/schoalrship.svg
  themes/custom/az_barrio/libraries/az-icons/svg/sign-post.svg
  themes/custom/az_barrio/libraries/az-icons/svg/spotify.svg
  themes/custom/az_barrio/libraries/az-icons/svg/spring-fling.svg
  themes/custom/az_barrio/libraries/az-icons/svg/tiktok.svg
  themes/custom/az_barrio/libraries/az-icons/svg/twitter.svg
  themes/custom/az_barrio/libraries/az-icons/svg/vimeo.svg
  themes/custom/az_barrio/libraries/az-icons/svg/wildcat.svg
  themes/custom/az_barrio/libraries/az-icons/svg/youtube.svg
  themes/custom/az_barrio/theme-settings.php
Labels: enhancement, ci, 2.10.x only

#3090 Closes #3019: Update AZ Core Routes.php class to use AutowireTrait.
  modules/custom/az_core/az_core.services.yml
  modules/custom/az_core/src/Routing/Routes.php
Labels: enhancement, Drupal, 2.10.x only

#3091 Closes #3016: Autowire controller services.
  modules/custom/az_publication/az_publication_import/src/Controller/AZPublicationImportController.php
  modules/custom/az_publication/src/Controller/AZAuthorController.php
Labels: enhancement, Drupal, 2.10.x only

#3092 Closes #3018: Enable auto-configuration for event subscribers.
  modules/custom/az_cas/az_cas.services.yml
  modules/custom/az_event/az_event_trellis/az_event_trellis.services.yml
  modules/custom/az_metrics/az_metrics.services.yml
  modules/custom/az_news/az_news_feeds/az_news_feeds.services.yml
  modules/custom/az_publication/az_publication_import/az_publication_import.services.yml
Labels: enhancement, Drupal, 2.10.x only

#3205 Closes #3204: Change News content max-width
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.default.yml
Labels: visual change, 2.10.x only

#2482 Closes #2385 Add indent and outdent to az_standard text editor
  composer.json
  modules/custom/az_paragraphs/az_paragraphs.info.yml
  modules/custom/az_paragraphs/az_paragraphs.install
  modules/custom/az_paragraphs/config/optional/editor.editor.az_standard.yml
Labels: documentation, enhancement, QS1 feature parity, editor experience, needs discussion, 2.10.x only

#3202 Closes #3201 Add a top margin to the pager on certain view displays
  modules/custom/az_core/config/install/views.view.az_taxonomy.yml
  modules/custom/az_event/config/install/views.view.az_events.yml
  modules/custom/az_flexible_page/config/install/views.view.az_page_by_category.yml
  modules/custom/az_news/config/install/views.view.az_news.yml
  themes/custom/az_barrio/css/style.css
Labels: visual change, 2.10.x only
