Repository az-digital/az_quickstart, pull requests merged in 2024-03, with the labels that each got.

#2537 Closes #2536, Closes #2876: Add missing Intelligence Bank setting and set media embed triggered modal width to 75% of browser window.
  modules/custom/az_digital_asset_library/az_digital_asset_library.module
  modules/custom/az_digital_asset_library/config/quickstart/ib_dam.settings.yml
Labels: bug, patch release

#3235 Fixes #3234 AZBackgroundMediaFormatter breaks field displays on non-paragraph entities
  modules/custom/az_paragraphs/src/Plugin/Field/FieldFormatter/AZBackgroundMediaFormatter.php
Labels: bug, backport, patch release

#3224 Closes #3223: Update test account passwords for ProboCI, lando, and ddev.
  .ddev/commands/web/install
  .lando.yml
  .probo.yaml
  CONTRIBUTING.md
Labels: bug, ci, high priority

#3226 Backport Update for Google Tag version 2.0.4 to Quickstart 2.8.x branch.
  composer.json
  modules/custom/az_google_tag/config/install/google_tag.container.az_comprehensive.yml
Labels: dependencies, high priority, Drupal, 2.8.x only

#3245 #3242, #3244: Ensure any existing version info removed from .info.yml file before adding new version.
  .github/workflows/create-release.yml
Labels: bug, backport, ci, patch release

#3249 Closes #3247 - Make Webform labels visually distinguishable from description text
  themes/custom/az_barrio/css/style.css
Labels: bug, visual change, usability, user experience, 2.10.x only

#3258 Closes #3257 Updated az_cas README with current WebAuth info
  modules/custom/az_cas/README.md
Labels: documentation, patch release, developer experience

#3250 Closes #3141: Customize Add CAS User(s) menu local action and optionally remove standard Add user action.
  modules/custom/az_cas/az_cas.module
  modules/custom/az_cas/config/install/az_cas.settings.yml
  modules/custom/az_cas/config/schema/az_cas.schema.yml
  modules/custom/az_cas/src/Form/AzCasSettingsForm.php
Labels: enhancement, user experience, 2.10.x only

#3254 Fixes #3253 Add Image Credit to Photo Galleries.
  modules/custom/az_paragraphs/az_paragraphs_photo_gallery/templates/paragraph--az-photo-gallery.html.twig
Labels: enhancement, no backport, visual change, user experience, proposal, 2.10.x only

#3238 Closes #1327: Added a new block display to Events view for past occurrences.
  modules/custom/az_event/config/install/views.view.az_events.yml
Labels: enhancement, 2.10.x only

#3251 Closes #3248: Adds status report check for Google Tag consent mode settings.
  modules/custom/az_google_tag/az_google_tag.install
  modules/custom/az_google_tag/az_google_tag.module
Labels: enhancement, backport, high priority, patch release

#3260 Close #3210, Close #3037 Address failing PHPCS security and coding standards warnings.
  modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php
  modules/custom/az_core/src/Plugin/ConfigProvider/QuickstartConfigProvider.php
  modules/custom/az_event/az_event.module
  modules/custom/az_mail/az_mail.module
  modules/custom/az_migration/src/Plugin/migrate/source/AZFileHandle.php
  modules/custom/az_paragraphs/az_paragraphs_link_group/az_paragraphs_link_group.module
  modules/custom/az_paragraphs/src/Plugin/Field/FieldFormatter/AZBackgroundMediaFormatter.php
  modules/custom/az_publication/az_publication_bibtex/src/Form/AZPublicationBibtexForm.php
  modules/custom/az_publication/az_publication_bibtex/src/Processor/AZLatexProcessor.php
  modules/custom/az_publication/src/Plugin/Filter/AZDOIFilter.php
  phpcs.xml.dist
Labels: enhancement, ci, 2.10.x only, developer experience

#3273 Close #3272 fix typo in az_core help.
  modules/custom/az_core/az_core.module
Labels: bug, backport, patch release

#3283 Close #3282 Turn Off Detailed Cron Logging By Default.
  config/install/system.cron.yml
Labels: enhancement, 2.10.x only, developer experience

#3269 Closes #3268 Add Photo Gallery Demo Content
  modules/custom/az_demo/data/az_demo_image_file.json
  modules/custom/az_demo/data/az_demo_page_node.json
  modules/custom/az_demo/data/az_demo_paragraph_gallery.json
  modules/custom/az_demo/migrations/az_demo_image_file.yml
  modules/custom/az_demo/migrations/az_demo_page_node.yml
  modules/custom/az_demo/migrations/az_demo_paragraph_gallery.yml
Labels: enhancement, ci, 2.10.x only

#3264 Closes #3263 Update ESLint docs in CONTRIBUTING.md with additional developer instructions.
  CONTRIBUTING.md
Labels: documentation, enhancement, 2.10.x only, developer experience

#3271 Closes #3270 Update CONTRIBUTING.md developer docs to reflect changes for Drupal 10.1
  CONTRIBUTING.md
Labels: documentation, enhancement, 2.10.x only, developer experience

#3279 Closes #2997 Add Demo Content as a Starting Point for Better Exposed Filter Finder Functionality
  modules/custom/az_demo/az_demo.module
  modules/custom/az_demo/config/install/views.view.az_finder.yml
  modules/custom/az_demo/config/optional/block.block.az_barrio_exposedformaz_findercontent.yml
  modules/custom/az_demo/config/optional/block.block.az_barrio_exposedformaz_finderevent.yml
  modules/custom/az_demo/config/optional/block.block.az_barrio_exposedformaz_findernews.yml
  modules/custom/az_demo/config/optional/block.block.az_barrio_exposedformaz_finderpage.yml
  modules/custom/az_demo/config/optional/block.block.az_barrio_exposedformaz_finderperson.yml
  modules/custom/az_demo/data/az_demo_menu_links.json
  modules/custom/az_demo/data/az_demo_page_categories.json
  modules/custom/az_demo/data/az_demo_page_node.json
  modules/custom/az_demo/data/az_demo_person_categories.json
  modules/custom/az_demo/data/az_demo_person_categories_secondary.json
  modules/custom/az_demo/data/az_demo_view_paragraph.json
Labels: enhancement, blocker, 2.10.x only

#3148 Closes #3142 - Adding SECURITY.md from template repository
  .github/SECURITY.md
Labels: documentation, enhancement, 2.10.x only

#3294 Close #3293 Allow reinstallation of az_demo module.
  modules/custom/az_demo/config/install/views.view.az_finder.yml
  modules/custom/az_demo/config/optional/block.block.az_barrio_exposedformaz_findercontent.yml
  modules/custom/az_demo/config/optional/block.block.az_barrio_exposedformaz_finderevent.yml
  modules/custom/az_demo/config/optional/block.block.az_barrio_exposedformaz_findernews.yml
  modules/custom/az_demo/config/optional/block.block.az_barrio_exposedformaz_finderpage.yml
  modules/custom/az_demo/config/optional/block.block.az_barrio_exposedformaz_finderperson.yml
Labels: bug, 2.10.x only

#3203 Fixes #3200 Implement HTTP Cache for Migrate Requests
  composer.json
  modules/custom/az_http/az_http.info.yml
  modules/custom/az_http/az_http.links.task.yml
  modules/custom/az_http/az_http.module
  modules/custom/az_http/az_http.routing.yml
  modules/custom/az_http/az_http.services.yml
  modules/custom/az_http/config/install/az_http.settings.yml
  modules/custom/az_http/config/schema/az_http.schema.yml
  modules/custom/az_http/src/AZHttpGuzzleCacheMiddleware.php
  modules/custom/az_http/src/AZHttpGuzzleCacheStorage.php
  modules/custom/az_http/src/AZHttpRetryMiddleware.php
  modules/custom/az_http/src/Form/AZHttpSettingsForm.php
  modules/custom/az_http/src/Plugin/migrate_plus/data_fetcher/AzHttp.php
  modules/custom/az_http/src/Strategy/AZPoliteCacheStrategy.php
Labels: enhancement, high priority, no backport, usability, editor experience, 2.10.x only

#3289 Close #3286 Adding a better exposed filter plugin for views.
  modules/custom/az_demo/az_demo.info.yml
  modules/custom/az_demo/config/install/views.view.az_finder.yml
  modules/custom/az_finder/az_finder.info.yml
  modules/custom/az_finder/az_finder.libraries.yml
  modules/custom/az_finder/az_finder.module
  modules/custom/az_finder/config/schema/views.exposed_form.az_better_exposed_filters.yml
  modules/custom/az_finder/js/active-filter-count.es6.js
  modules/custom/az_finder/js/active-filter-count.js
  modules/custom/az_finder/js/active-filter-reset.es6.js
  modules/custom/az_finder/js/active-filter-reset.js
  modules/custom/az_finder/src/Plugin/views/exposed_form/QuickstartExposedFilters.php
Labels: enhancement, high priority, news, 2.10.x only

#2540 Fixes #1537 Distribution Config Export Commands
  modules/custom/az_core/az_core.distribution_export.yml
  modules/custom/az_core/drush.services.yml
  modules/custom/az_core/src/Drush/Commands/AZCoreConfigCommands.php
  modules/custom/az_core/src/Plugin/ConfigProvider/QuickstartConfigProvider.php
Labels: enhancement, spike, usability, needs discussion, 2.10.x only

#2532 Closes #2528 Add bootstrap class `col-form-label` to `<legend>` element within `<fieldset>`s.
  themes/custom/az_barrio/templates/forms/fieldset.html.twig
Labels: documentation, visual change, 2.10.x only

#3298 Close #3296: Re-export az_finder view to remove extraneous BEF settings
  modules/custom/az_demo/config/install/views.view.az_finder.yml
Labels: bug, 2.10.x only
