Repository az-digital/az_quickstart, pull requests merged in 2024-07, with the labels that each got.

#3515 #2778: Fix 10.3.x specific PHPCS issue in AZEnterpriseAttributesMigrationSync
  modules/custom/az_core/az_enterprise_attributes_import/src/EventSubscriber/AZEnterpriseAttributesMigrationSync.php
Labels: bug, 2.11.x only

#3514 Closes #2835: Switch back to d.o. version of smart_title.
  composer.json
Labels: dependencies, Drupal, patch release

#3519 Closes #3453 | Remove duplicate required asterisk on Webforms
  themes/custom/az_barrio/templates/forms/fieldset.html.twig
Labels: bug, backport, patch release, visual change

#3545 Fixes #3544 AZBackgroundMediaFormatter Breaks with Missing Files
  modules/custom/az_paragraphs/src/Plugin/Field/FieldFormatter/AZBackgroundMediaFormatter.php
Labels: bug, backport, patch release

#3547 Closes #3546 PHPUnit tests cannot be run locally using lando
  .lando.yml
Labels: bug, ci

#3554 Refactor Finder Settings Form.
  modules/custom/az_finder/src/Form/AZFinderSettingsForm.php
Labels: bug, enhancement

#3558 Fixes #3556, Fixes #3557 Regressions in AZEventTrellisViewsField, AZTrellisEventSource
  modules/custom/az_event/az_event_trellis/src/Plugin/migrate/source/AZTrellisEventSource.php
  modules/custom/az_event/az_event_trellis/src/Plugin/views/field/AZEventTrellisViewsField.php
Labels: bug, high priority, no backport, 2.11.x only

#3420 Close #3262 Add ability for content admins to set finder overrides.
  config/install/user.role.az_content_admin.yml
  modules/custom/az_demo/config/install/views.view.az_finder.yml
  modules/custom/az_finder/az_finder.info.yml
  modules/custom/az_finder/az_finder.links.task.yml
  modules/custom/az_finder/az_finder.permissions.yml
  modules/custom/az_finder/az_finder.routing.yml
  modules/custom/az_finder/az_finder.services.yml
  modules/custom/az_finder/config/install/az_finder.settings.yml
  modules/custom/az_finder/config/quickstart/views.view.az_page_by_category.yml
  modules/custom/az_finder/config/schema/az_finder.schema.yml
  modules/custom/az_finder/config/schema/views.exposed_form.az_better_exposed_filters.yml
  modules/custom/az_finder/css/taxonomy-index-tid-widget.css
  modules/custom/az_finder/src/Form/AZFinderSettingsForm.php
  modules/custom/az_finder/src/Plugin/better_exposed_filters/filter/AZFinderTaxonomyIndexTidWidget.php
  modules/custom/az_finder/src/Service/AZFinderIcons.php
  modules/custom/az_finder/src/Service/AZFinderOverrides.php
  modules/custom/az_finder/src/Service/AZFinderViewOptions.php
  modules/custom/az_finder/src/Service/AZFinderVocabulary.php
  modules/custom/az_finder/templates/az-finder-nested-elements.html.twig
  modules/custom/az_finder/templates/az-finder-widget.html.twig
  modules/custom/az_finder/tests/AZFinderIconsTest.php
Labels: enhancement, needs-CWS-testing, 2.11.x only

#3562 Closes #3561: Add NetID field to AZ Person.
  modules/custom/az_person/config/install/core.entity_form_display.node.az_person.default.yml
  modules/custom/az_person/config/install/core.entity_view_display.node.az_person.az_card.yml
  modules/custom/az_person/config/install/core.entity_view_display.node.az_person.az_row.yml
  modules/custom/az_person/config/install/core.entity_view_display.node.az_person.az_row_with_background.yml
  modules/custom/az_person/config/install/core.entity_view_display.node.az_person.default.yml
  modules/custom/az_person/config/install/core.entity_view_display.node.az_person.teaser.yml
  modules/custom/az_person/config/install/field.field.node.az_person.field_az_netid.yml
  modules/custom/az_person/config/install/field.storage.node.field_az_netid.yml
  modules/custom/az_seo/config/quickstart/core.entity_form_display.node.az_person.default.yml
Labels: enhancement, Integrations, proposal, 2.11.x only

#3499 Closes #3498 Make config dependencies, module dependencies in az_seo.
  modules/custom/az_seo/az_seo.info.yml
  modules/custom/az_seo/az_seo.install
Labels: bug, patch release

#3446 Closes #3445 Make config dependencies, module dependencies in az_paragraphs:az_paragraphs_view
  modules/custom/az_paragraphs/az_paragraphs_views_side_by_side/az_paragraphs_views_side_by_side.info.yml
  modules/custom/az_paragraphs/az_paragraphs_views_side_by_side/az_paragraphs_views_side_by_side.install
Labels: bug, patch release

#3583 Closes #3581: Apply updated coding standards to 2.10.x branch.
  modules/custom/az_core/src/Drush/Commands/AZEntityListCommands.php
  modules/custom/az_core/tests/src/Functional/MonitoringPageTest.php
  modules/custom/az_demo/tests/src/Functional/AZDemoContentTest.php
  modules/custom/az_event/az_event_trellis/src/Plugin/migrate/source/AZTrellisEventSource.php
  modules/custom/az_finder/src/AZFinderIcons.php
  modules/custom/az_finder/src/Plugin/better_exposed_filters/filter/AZFinderTaxonomyIndexTidWidget.php
  modules/custom/az_finder/src/Plugin/views/exposed_form/QuickstartExposedFilters.php
  modules/custom/az_http/src/Plugin/migrate_plus/data_fetcher/AzHttp.php
  modules/custom/az_news/az_news_feeds/src/EventSubscriber/AzNewsFeedsMigrateSubscriber.php
  modules/custom/az_news/az_news_feeds/src/Form/AzNewsFeedsAdminForm.php
  modules/custom/az_paragraphs/src/Plugin/Field/FieldFormatter/AZBackgroundMediaFormatter.php
Labels: bug, ci, patch release, 2.10.x only

#3584 #3581: Apply updated coding standards to 2.9.x branch.
  modules/custom/az_core/tests/src/Functional/MonitoringPageTest.php
  modules/custom/az_demo/tests/src/Functional/AZDemoContentTest.php
  modules/custom/az_event/az_event_trellis/src/Plugin/migrate/source/AZTrellisEventSource.php
  modules/custom/az_news/az_news_feeds/src/EventSubscriber/AzNewsFeedsMigrateSubscriber.php
  modules/custom/az_news/az_news_feeds/src/Form/AzNewsFeedsAdminForm.php
  modules/custom/az_paragraphs/src/Plugin/Field/FieldFormatter/AZBackgroundMediaFormatter.php
Labels: bug, backport, ci, 2.9.x only
