Repository az-digital/az_quickstart, pull requests merged in 2024-10, with the labels that each got.

#3749 Closes #1212: Add views_bulk_operations as optional module.
  composer.json
Labels: enhancement, patch release, release notes

#3745 Closes #3744 Prevent views using Quickstart Exposed Filters from scrolling when checkboxes are checked
  modules/custom/az_finder/az_finder.services.yml
  modules/custom/az_finder/src/EventSubscriber/AZFinderAjaxResponseSubscriber.php
Labels: bug, enhancement, patch release

#3748 Closes #3747 Restore the display of 12:00 am and 12:00 pm as "midnight" and "noon" for events
  modules/custom/az_demo/data/az_demo_event_node.json
  modules/custom/az_demo/data/az_demo_event_rrule.json
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_card.yml
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_card_alternate.yml
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_row.yml
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.default.yml
Labels: bug, patch release

#3752 Closes #3751: Update drupal/core-recommended to 10.3.6 (addresses CVE-2024-45440).
  composer.json
Labels: dependencies, Drupal, patch release, 2.11.x only, release notes

#3759 Closes #3758: Ensure all external and minified library assets are properly configured.
  modules/custom/az_event/az_event_trellis/az_event_trellis.libraries.yml
  modules/custom/az_finder/az_finder.libraries.yml
  modules/custom/az_publication/az_publication.libraries.yml
  themes/custom/az_barrio/az_barrio.libraries.yml
Labels: bug, 2.11.x only

#3724 #3717, az-digital/az-quickstart-pantheon#282: Add ImageMagick module.
  composer.json
Labels: enhancement, dependencies, patch release, release notes

#3767 Close #3765 Change top-level Quickstart toolbar link to an internal page instead of an external page.
  modules/custom/az_core/az_core.module
Labels: bug, patch release, usability, editor experience, user experience

#3782 Closes #3780: Add missing SMTP module config to address test failures in 2.10.x
  modules/custom/az_mail/config/quickstart/smtp.settings.yml
Labels: bug, patch release, 2.10.x only

#3779 #3737: Backport coding standards fixes from #3738 to 2.10.x.
  modules/custom/az_core/az_core.module
  modules/custom/az_core/src/AZConfigOverride.php
  modules/custom/az_core/src/Drush/Commands/AZCoreConfigCommands.php
  modules/custom/az_core/src/Plugin/ConfigProvider/QuickstartConfigProvider.php
  modules/custom/az_core/tests/src/Functional/QuickstartFunctionalTestBase.php
  modules/custom/az_course/src/Form/CourseImportForm.php
  modules/custom/az_demo/az_demo.module
  modules/custom/az_event/az_event_trellis/az_event_trellis.module
  modules/custom/az_event/az_event_trellis/src/Entity/AZRecurringImportRule.php
  modules/custom/az_event/az_event_trellis/src/EventSubscriber/AZEventTrellisDataSubscriber.php
  modules/custom/az_event/az_event_trellis/src/Form/AZRecurringImportRuleForm.php
  modules/custom/az_event/az_event_trellis/src/Plugin/migrate/source/AZTrellisEventSource.php
  modules/custom/az_event/az_event_trellis/src/Plugin/views/field/AZEventTrellisViewsField.php
  modules/custom/az_event/az_event_trellis/src/TrellisHelper.php
  modules/custom/az_finder/src/Plugin/better_exposed_filters/filter/AZFinderTaxonomyIndexTidWidget.php
  modules/custom/az_finder/src/Plugin/views/exposed_form/QuickstartExposedFilters.php
  modules/custom/az_http/src/AZHttpRetryMiddleware.php
  modules/custom/az_http/src/Strategy/AZPoliteCacheStrategy.php
  modules/custom/az_migration/src/Plugin/migrate/process/MigratedPathLookup.php
  modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehaviorSettings.php
  modules/custom/az_paragraphs/tests/src/Unit/AZVideoEmbedHelperTest.php
  modules/custom/az_publication/az_publication.module
  modules/custom/az_publication/src/AZAuthorStorage.php
  modules/custom/az_publication/src/AZAuthorStorageInterface.php
  modules/custom/az_publication/src/Controller/AZAuthorController.php
  modules/custom/az_publication/src/Form/AZAuthorRevisionRevertForm.php
  modules/custom/az_publication/src/Form/AZAuthorRevisionRevertTranslationForm.php
Labels: bug, patch release, 2.10.x only

#3778 Closes #3777: Update drupal/core-recommended to 10.2.10 for SA-CORE-2024-002 and CVE-2024-45440
  composer.json
Labels: bug, dependencies, Drupal, patch release, 2.10.x only

#3788 Closes #3787: Update release notes section in pull_request_template.md
  .github/pull_request_template.md
Labels: documentation, backport, patch release

#3552 Closes #3551 Update references to UArizona
  README.md
  modules/custom/az_demo/data/az_demo_news_node.json
  modules/custom/az_demo/data/az_demo_splitscreen_paragraph.json
  modules/custom/az_demo/data/az_demo_text_media_paragraph.json
  modules/custom/az_demo/data/az_demo_text_paragraph.json
  modules/custom/az_global_footer/README.md
  modules/custom/az_global_footer/az_global_footer.info.yml
  modules/custom/az_global_footer/az_global_footer.module
  modules/custom/az_google_tag/az_google_tag.install
  modules/custom/az_news/az_news_feeds/az_news_feeds.info.yml
  modules/custom/az_news/az_news_feeds/az_news_feeds.links.task.yml
  modules/custom/az_news/az_news_feeds/az_news_feeds.routing.yml
  modules/custom/az_news/az_news_feeds/config/install/migrate_plus.migration.az_news_feed_stories.yml
  modules/custom/az_news/az_news_feeds/config/install/migrate_plus.migration.az_news_feed_stories_files.yml
  modules/custom/az_news/az_news_feeds/config/install/migrate_plus.migration.az_news_feed_stories_media.yml
  modules/custom/az_news/az_news_feeds/config/install/migrate_plus.migration_group.az_news_feeds.yml
  modules/custom/az_news/az_news_feeds/config/schema/az_news_feeds.schema.yml
  modules/custom/az_news/az_news_feeds/src/EventSubscriber/AzNewsFeedsMigrateSubscriber.php
  modules/custom/az_news/az_news_feeds/src/Form/AzNewsFeedsAdminForm.php
  modules/custom/az_news/config/install/field.field.node.az_news.field_az_link.yml
Labels: task, patch release, visual change, 2.11.x only, brand change

#3774 Closes #3773 Styling issues with Box style Text on Media paragraphs
  modules/custom/az_paragraphs/az_paragraphs_text_media/config/install/core.entity_view_display.paragraph.az_text_media.default.yml
  modules/custom/az_paragraphs/css/az_paragraphs_full_width.css
Labels: bug, backport, patch release, visual change, needs-CWS-testing

#3785 Closes #3784 Incorrect access permission for Reorder Carousel Items view display
  modules/custom/az_carousel/config/install/views.view.az_carousel.yml
Labels: bug, backport, patch release

#3585 Closes #3086 Adding demo content for publications
  modules/custom/az_demo/az_demo.info.yml
  modules/custom/az_demo/config/optional/block.block.az_barrio_views_block__az_publications_az_author_person.yml
  modules/custom/az_demo/data/az_demo_az_author_author.json
  modules/custom/az_demo/data/az_demo_menu_links.json
  modules/custom/az_demo/data/az_demo_node_publication.json
  modules/custom/az_demo/data/az_demo_page_node.json
  modules/custom/az_demo/data/az_demo_person_node.json
  modules/custom/az_demo/data/az_demo_taxonomy_term_publication_categories.json
  modules/custom/az_demo/data/az_demo_view_paragraph.json
  modules/custom/az_demo/migrations/az_demo_az_author_author.yml
  modules/custom/az_demo/migrations/az_demo_node_publication.yml
  modules/custom/az_demo/migrations/az_demo_person_node.yml
  modules/custom/az_demo/migrations/az_demo_taxonomy_term_publication_categories.yml
Labels: enhancement, publications, 2.12.x only

#3805 Close #3804 fix summary import in az_demo.
  modules/custom/az_demo/data/az_demo_event_node.json
  modules/custom/az_demo/data/az_demo_news_node.json
  modules/custom/az_demo/data/az_demo_page_node.json
  modules/custom/az_demo/migrations/az_demo_event_node.yml
  modules/custom/az_demo/migrations/az_demo_news_node.yml
  modules/custom/az_demo/migrations/az_demo_page_node.yml
Labels: patch release, QS1 feature parity, developer experience

#3808 Closes #3807: Deprecate aria_controls variable in az_accordion theme implementation and template.
  modules/custom/az_accordion/az_accordion.module
  modules/custom/az_accordion/src/Plugin/Field/FieldFormatter/AZAccordionDefaultFormatter.php
  modules/custom/az_accordion/templates/az-accordion.html.twig
Labels: task, release notes, 2.12.x only

#3219 Closes #3217: Add anchor link plugin for CKEditor5.
  composer.json
  modules/custom/az_paragraphs/az_paragraphs.info.yml
  modules/custom/az_paragraphs/az_paragraphs.install
  modules/custom/az_paragraphs/az_paragraphs.module
  modules/custom/az_paragraphs/config/optional/editor.editor.az_standard.yml
Labels: enhancement, QS1 feature parity, visual change, needs-CWS-testing, editor experience, release notes, 2.12.x only

#3696 Closes #3569, #3689 Disable automatic paragraph filter for the Standard text format
  modules/custom/az_demo/data/az_demo_event_node.json
  modules/custom/az_demo/data/az_demo_news_node.json
  modules/custom/az_media/config/install/filter.format.az_standard.yml
Labels: bug, visual change, needs-CWS-testing, needs discussion, release notes, 2.12.x only

#3814 Closes #3793: Improve accessibility of card link titles
  modules/custom/az_card/css/az-card-title-hover.css
  modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php
  modules/custom/az_demo/data/az_demo_card_paragraph.json
Labels: bug, enhancement, accessibility, needs-CWS-testing, 2.12.x only

#2347 Closes #2345: Add automated test to verify cache invalidation is working.
  modules/custom/az_core/tests/src/Functional/CacheInvalidationTest.php
Labels: enhancement, ci, 2.12.x only

#3764 Fixes #3553, Fixes #3790 AZ Person manageable using CAS account login, Dedicated Permission for Publication Curation
  config/install/user.role.administrator.yml
  config/install/user.role.az_content_admin.yml
  config/install/user.role.az_content_editor.yml
  config/install/user.role.az_html_admin.yml
  config/install/user.role.az_profile_editor.yml
  config/install/user.role.az_user_admin.yml
  modules/custom/az_core/az_core.module
  modules/custom/az_core/az_core.permissions.yml
  modules/custom/az_core/az_core.services.yml
  modules/custom/az_core/src/AZUserToolbarLinkBuilder.php
  modules/custom/az_curated_views/az_curated_views.permissions.yml
  modules/custom/az_curated_views/src/Plugin/views/field/AZCuratedViewsField.php
  modules/custom/az_publication/config/install/views.view.az_publications_curate.yml
Labels: enhancement, needs-CWS-testing, editor experience, needs discussion, release notes, 2.12.x only

#3818 Closes #3817 Full-width paragraphs may have wrong width when not in the Content region
  modules/custom/az_paragraphs/css/az_paragraphs_az_text_background.css
  modules/custom/az_paragraphs/css/az_paragraphs_az_text_media.css
  modules/custom/az_paragraphs/css/az_paragraphs_full_width.css
Labels: bug, backport, high priority, patch release

#3786 Closes #2929: Strip links from summary field(s).
  modules/custom/az_core/src/Plugin/Field/FieldFormatter/AZSummaryFormatter.php
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_card.yml
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_card_alternate.yml
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_row.yml
  modules/custom/az_flexible_page/config/install/core.entity_view_display.node.az_flexible_page.az_card.yml
  modules/custom/az_flexible_page/config/install/core.entity_view_display.node.az_flexible_page.az_row.yml
  modules/custom/az_flexible_page/config/install/core.entity_view_display.node.az_flexible_page.az_row_with_background.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_card.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_feature.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_media_list.yml
Labels: bug, release notes, 2.12.x only

#3837 Prepare 2.11.x branch for new minor release branch 2.12.x
  composer.json
Labels: 2.11.x only

#3839 Close #3838 Update prepare-for-minor-release.yml with new release branches
  .github/workflows/prepare-for-minor-release.yml
Labels: ci

#3840 Close #1479 exclude Drupal 6 migrations from appearing when running drush migrate:status
  modules/custom/az_migration/az_migration.module
Labels: migration, patch release, developer experience
