Repository az-digital/az_quickstart, pull requests merged in 2024-12, with the labels that each got.

#3918 Closes #3917: Update no results views on events
  modules/custom/az_event/config/install/views.view.az_events.yml
  modules/custom/az_finder/config/quickstart/views.view.az_events.yml
Labels: bug, visual change, needs-CWS-testing, release notes, 2.12.x only

#3921 Closes #3653: Add Recent News Marquee demo content
  modules/custom/az_demo/data/az_demo_image_file.json
  modules/custom/az_demo/data/az_demo_page_node.json
  modules/custom/az_demo/data/az_demo_view_paragraph.json
Labels: enhancement, ci, 2.13.x only

#3919 Closes #3855: Update config schema files that have uuid fields that are string to use the uuid type
  modules/custom/az_event/az_event_trellis/config/schema/az_event_trellis.schema.yml
  modules/custom/az_publication/config/schema/az_citation_style.schema.yml
  modules/custom/az_publication/config/schema/az_publication_type.schema.yml
Labels: enhancement

#3928 Closes #3277: Update "Update Review Site" workflow to add a more descriptive commit message when rebuilding demo.quickstart.arizona.edu
  .github/workflows/review-site.yml
Labels: ci, github_actions

#3910 Closes #3130: Add descriptions for 6 AZ modules
  modules/custom/az_block_types/az_block_types_quick_links/az_block_types_quick_links.info.yml
  modules/custom/az_flexible_block/az_flexible_block.info.yml
  modules/custom/az_flexible_page/az_flexible_page.info.yml
  modules/custom/az_google_tag/az_google_tag.info.yml
  modules/custom/az_select_menu/az_select_menu.info.yml
  modules/custom/az_seo/az_seo.info.yml
Labels: documentation, enhancement, developer experience

#3937 Closes #3438: Image captions visible in AZ News - Recent News Marquee paragraph
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_marquee.yml
Labels: enhancement, visual change, release notes, 2.13.x only

#3947 Fixes #3946 Whitescreen if az_person not installed.
  modules/custom/az_core/az_core.services.yml
  modules/custom/az_core/src/AZUserToolbarLinkBuilder.php
Labels: bug, high priority, patch release, release notes, 2.12.x only

#3950 Closes #3949 AZ Publication database update fails if no publication nodes exist
  modules/custom/az_publication/az_publication.install
Labels: bug, high priority, 2.12.x only

#3868 Fixes #3866 Update AZEnterpriseAttributesMigrationSync, Migrate Tools
  composer.json
  modules/custom/az_core/az_enterprise_attributes_import/az_enterprise_attributes_import.services.yml
  modules/custom/az_core/az_enterprise_attributes_import/src/EventSubscriber/AZEnterpriseAttributesMigrationSync.php
  modules/custom/az_core/az_enterprise_attributes_import/tests/src/Functional/EnterpriseAttributesImportTest.php
Labels: bug, enhancement, patch release

#3943 Closes #3942: Update drupal/core-recommended to 10.3.10.
  composer.json
Labels: backport, dependencies, Drupal, patch release

#3953 Close #3952 Add patch to allow overriding viewsreference offset using zero value.
  composer.json
Labels: backport, dependencies, Drupal, patch release
