Repository az-digital/az_quickstart, pull requests merged in 2024-08, with the labels that each got.

#3587 Close #3586 Set lifecycle key in info files if not stable.
  modules/custom/az_core/az_enterprise_attributes_import/az_enterprise_attributes_import.info.yml
  modules/custom/az_course/az_course.info.yml
  modules/custom/az_curated_views/az_curated_views.info.yml
  modules/custom/az_demo/az_demo.info.yml
  modules/custom/az_digital_asset_library/az_digital_asset_library.info.yml
  modules/custom/az_event/az_event_trellis/az_event_trellis.info.yml
  modules/custom/az_finder/az_finder.info.yml
  modules/custom/az_http/az_http.info.yml
  modules/custom/az_marketing_cloud/az_marketing_cloud.info.yml
  modules/custom/az_migration/az_migration.info.yml
  modules/custom/az_news/az_news_export/az_news_export.info.yml
  modules/custom/az_news/az_news_feeds/az_news_feeds.info.yml
  modules/custom/az_paragraphs/az_paragraphs_link_group/az_paragraphs_link_group.info.yml
  modules/custom/az_paragraphs/az_paragraphs_views_side_by_side/az_paragraphs_views_side_by_side.info.yml
  modules/custom/az_publication/az_publication.info.yml
  modules/custom/az_publication/az_publication_bibtex/az_publication_bibtex.info.yml
  modules/custom/az_publication/az_publication_doi/az_publication_doi.info.yml
  modules/custom/az_publication/az_publication_import/az_publication_import.info.yml
Labels: good first issue, task, patch release, usability, developer experience

#3589 Close #3588 Allow newly enabled module config to be overridden.
  modules/custom/az_core/src/Plugin/ConfigProvider/QuickstartConfigProvider.php
  modules/custom/az_core/tests/src/Functional/ConfigOverrideTest.php
Labels: bug, backport, patch release

#3592 Fixes #3591 Add NetID Unique Constraint
  modules/custom/az_person/az_person.module
Labels: bug, editor experience, 2.11.x only

#3577 Closes #3567 Styling adjustments for the AZ Finder exposed form (AZDIGITAL-158)
  modules/custom/az_finder/css/taxonomy-index-tid-widget.css
  modules/custom/az_finder/src/Plugin/better_exposed_filters/filter/AZFinderTaxonomyIndexTidWidget.php
Labels: enhancement, patch release, visual change

#3477 Closes #3473: Adding policy recommendations for Experimental Modules
  RELEASES.md
Labels: documentation, patch release

#3600 Fix #3599 Can no longer save text format and editor configuration form, and upgrade bootstrap_utilities from 2.0.0 to 3.0.0
  composer.json
Labels: bug, patch release, 2.11.x only

#3603 Close #3602 transpile JS with build tools `lando yarn run build`
  modules/custom/az_card/js/az-card-no-follow.js
  modules/custom/az_finder/js/active-filter-count.js
  modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_youtube.js
  modules/custom/az_select_menu/js/az-select-menu.js
Labels: task, patch release, 2.11.x only

#3598 Closes #3597: Add lifecycle_link to experimental modules documentation in experimental modules.
  RELEASES.md
  modules/custom/az_core/az_enterprise_attributes_import/az_enterprise_attributes_import.info.yml
  modules/custom/az_course/az_course.info.yml
  modules/custom/az_curated_views/az_curated_views.info.yml
  modules/custom/az_demo/az_demo.info.yml
  modules/custom/az_digital_asset_library/az_digital_asset_library.info.yml
  modules/custom/az_event/az_event_trellis/az_event_trellis.info.yml
  modules/custom/az_finder/az_finder.info.yml
  modules/custom/az_http/az_http.info.yml
  modules/custom/az_marketing_cloud/az_marketing_cloud.info.yml
  modules/custom/az_migration/az_migration.info.yml
  modules/custom/az_news/az_news_export/az_news_export.info.yml
  modules/custom/az_news/az_news_feeds/az_news_feeds.info.yml
  modules/custom/az_paragraphs/az_paragraphs_link_group/az_paragraphs_link_group.info.yml
  modules/custom/az_paragraphs/az_paragraphs_views_side_by_side/az_paragraphs_views_side_by_side.info.yml
  modules/custom/az_publication/az_publication.info.yml
  modules/custom/az_publication/az_publication_bibtex/az_publication_bibtex.info.yml
  modules/custom/az_publication/az_publication_doi/az_publication_doi.info.yml
  modules/custom/az_publication/az_publication_import/az_publication_import.info.yml
Labels: documentation, enhancement, patch release

#3640 Fixes #3639 Order Authors by Name
  modules/custom/az_publication/src/AZAuthorListBuilder.php
Labels: bug, editor experience

#3638 Fixes #3619 Add Documentation for az-core-distribution-config
  CONTRIBUTING.md
Labels: documentation, enhancement, developer experience

#3643 Closes #3642 Upgrade Drupal core to 10.3.2
  composer.json
Labels: dependencies, Drupal, patch release, 2.11.x only

#3648 #3647: Disable az_seo_update_1021001 and az_paragraphs_views_side_by_side_update_1021001.
  modules/custom/az_paragraphs/az_paragraphs_views_side_by_side/az_paragraphs_views_side_by_side.info.yml
  modules/custom/az_paragraphs/az_paragraphs_views_side_by_side/az_paragraphs_views_side_by_side.install
  modules/custom/az_seo/az_seo.info.yml
  modules/custom/az_seo/az_seo.install
Labels: bug, patch release, release notes

#3631 Closes #3576 Add new demo AZ News node with embedded media and extra paragraphs
  modules/custom/az_demo/data/az_demo_card_paragraph.json
  modules/custom/az_demo/data/az_demo_image_file.json
  modules/custom/az_demo/data/az_demo_news_node.json
  modules/custom/az_demo/images/BIO5-Keating-1224x682.jpg
  modules/custom/az_demo/images/Health-Sciences-Education-Building-2464x1640.jpg
  modules/custom/az_demo/migrations/az_demo_news_node.yml
Labels: enhancement, ci, 2.12.x only

#3659 Close #3658 Add all paragraph migrations as optional dependencies of the news node migration.
  modules/custom/az_migration/migrations/az_node_news.yml
Labels: enhancement, migration, patch release

#3668 Closes #3666 Update Photo Gallery to prevent potential XSS vulnerability
  modules/custom/az_paragraphs/az_paragraphs_photo_gallery/templates/paragraph--az-photo-gallery.html.twig
Labels: bug, backport, dependencies, high priority, patch release

#3672 Closes #3671 Add minified option on az_bootstrap_js_info
  themes/custom/az_barrio/az_barrio.theme
Labels: bug, backport, patch release
