Repository az-digital/az_quickstart, pull requests merged in 2025-04, with the labels that each got.

#4165 Closes #4166: Update Config Synchronizer + dependencies.
  composer.json
Labels: dependencies, Drupal, 2.13.x only

#4053 #4040 Map Enterprise Attributes during Trellis Events import
  modules/custom/az_core/az_enterprise_attributes_import/config/install/migrate_plus.migration.az_enterprise_attributes_import.yml
  modules/custom/az_core/az_enterprise_attributes_import/config/install/migrate_plus.migration_group.az_enterprise_attributes_import.yml
  modules/custom/az_event/az_event_trellis/config/install/migrate_plus.migration.az_trellis_events.yml
  modules/custom/az_event/az_event_trellis/src/TrellisHelper.php
Labels: documentation, enhancement, high priority, Integrations, needs-CWS-testing, trellis, release notes, needs-documentation

#4075 Fixes #3712 Add Author Role to Publications
  composer.json
  modules/custom/az_demo/data/az_demo_node_publication.json
  modules/custom/az_demo/migrations/az_demo_node_publication.yml
  modules/custom/az_publication/az_publication.install
  modules/custom/az_publication/az_publication.module
  modules/custom/az_publication/az_publication.views.inc
  modules/custom/az_publication/az_publication_bibtex/migrations/az_publication_bibtex_import.yml
  modules/custom/az_publication/config/install/core.entity_form_display.node.az_publication.default.yml
  modules/custom/az_publication/config/install/core.entity_view_display.node.az_publication.az_card.yml
  modules/custom/az_publication/config/install/core.entity_view_display.node.az_publication.az_publication_reference.yml
  modules/custom/az_publication/config/install/core.entity_view_display.node.az_publication.default.yml
  modules/custom/az_publication/config/install/core.entity_view_display.node.az_publication.teaser.yml
  modules/custom/az_publication/config/install/field.field.node.az_publication.field_az_authors.yml
  modules/custom/az_publication/config/install/field.field.node.az_publication.field_az_contributors.yml
  modules/custom/az_publication/config/install/field.storage.node.field_az_contributors.yml
  modules/custom/az_publication/config/install/views.view.az_publications.yml
  modules/custom/az_publication/config/install/views.view.az_publications_curate.yml
  modules/custom/az_publication/src/Plugin/Field/FieldFormatter/AZEntityRoleReferenceLabelFormatter.php
  modules/custom/az_publication/src/Plugin/Field/FieldType/AZEntityRoleReferenceItem.php
  modules/custom/az_publication/src/Plugin/Field/FieldWidget/AZEntityRoleInlineFormComplex.php
  modules/custom/az_publication/templates/az-inline-entity-role-form-entity-table.html.twig
Labels: enhancement, high priority, needs-CWS-testing, publications, release notes, 2.13.x only, needs-documentation

#3901 Closes #3644: Add schema_metatag global defaults using the az_seo module
  composer.json
  modules/custom/az_seo/az_seo.info.yml
  modules/custom/az_seo/az_seo.install
  modules/custom/az_seo/config/quickstart/metatag.metatag_defaults.front.yml
  modules/custom/az_seo/config/quickstart/metatag.metatag_defaults.global.yml
  modules/custom/az_seo/config/quickstart/metatag.metatag_defaults.node.yml
Labels: enhancement, high priority, needs-CWS-testing, release notes, 2.13.x only, needs-documentation

#4051 Close #4039 Add Enterprise Attributes to az_events
  modules/custom/az_core/az_enterprise_attributes_import/config/install/migrate_plus.migration.az_enterprise_attributes_import.yml
  modules/custom/az_core/az_enterprise_attributes_import/config/install/migrate_plus.migration_group.az_enterprise_attributes_import.yml
  modules/custom/az_core/src/Plugin/Field/FieldWidget/AZAttributeWidget.php
  modules/custom/az_event/az_event_trellis/az_event_trellis.module
  modules/custom/az_event/az_event_trellis/config/install/migrate_plus.migration.az_trellis_events.yml
  modules/custom/az_event/az_event_trellis/src/TrellisHelper.php
  modules/custom/az_event/config/install/core.entity_form_display.node.az_event.default.yml
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_card.yml
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_card_alternate.yml
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_row.yml
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_row_with_background.yml
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.default.yml
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.teaser.yml
  modules/custom/az_event/config/install/field.field.node.az_event.field_az_enterprise_attributes.yml
  modules/custom/az_seo/config/quickstart/core.entity_form_display.node.az_event.default.yml
Labels: enhancement, high priority, Integrations, needs-CWS-testing, editor experience, needs-documentation

#3923 Fixes #3922 Add Event to Calendar support
  composer.json
  modules/custom/az_event/az_event.info.yml
  modules/custom/az_event/az_event.install
  modules/custom/az_event/az_event.module
  modules/custom/az_event/templates/az-event-calendar-add-button.html.twig
Labels: enhancement, visual change, needs-CWS-testing, usability, user experience, proposal, release notes, 2.13.x only, needs-documentation

#4159 Fixes #4158 Profiles-imported Person photos should not be editable.
  modules/custom/az_person/az_person.module
Labels: bug, Integrations, needs-CWS-testing, needs discussion, 2.13.x only, needs-documentation

#4164 Closes #4163: Updates AZ Page Card and Row Displays
  modules/custom/az_flexible_page/config/install/core.entity_view_display.node.az_flexible_page.az_card.yml
  modules/custom/az_flexible_page/config/install/core.entity_view_display.node.az_flexible_page.az_row.yml
Labels: backport, patch release, accessibility, release notes

#4153 Closes #2028, #4141: Repeating Events date list pushes Event Description (far) down the page
  modules/custom/az_event/az_event.info.yml
  modules/custom/az_event/az_event.module
  modules/custom/az_event/templates/az-event-calendar-add-button.html.twig
Labels: visual change, needs-CWS-testing, 2.13.x only, needs-documentation

#4172 Fixes #4169 Resolve Drush 13 phpstan errors
  phpstan.neon
Labels: bug, ci, developer experience, 2.13.x only

#4196 Closes #4190: Add a recurrence description to pages for recurring events
  modules/custom/az_event/az_event.module
  modules/custom/az_event/templates/az-event-calendar-add-button.html.twig
  modules/custom/az_event/templates/az-event-view-occurrences-button.html.twig
  modules/custom/az_event/templates/field--node--az-event.html.twig
Labels: enhancement, 2.13.x only

#4212 Fixes #4211 Trellis Events views integration not translatable.
  modules/custom/az_event/az_event_trellis/az_event_trellis.views.inc
Labels: bug, backport, patch release, Integrations, trellis, publications

#4209 Closes #1546 Fix az-aspect-ratio setting with content-width Text on Media paragraphs.
  modules/custom/az_paragraphs/css/az_paragraphs_full_width.css
  modules/custom/az_paragraphs/src/Plugin/Field/FieldFormatter/AZBackgroundMediaFormatter.php
Labels: bug, patch release

#4231 Close #4230 Add patch for field_group module
  composer.json
Labels: blocker, patch release, 2.13.x only

#4227 Close #3795 Remove modules deprecated in `2.11.x`: `ctools`, `jquery_ui_slider`, `jquery_ui_touch_punch`
  az_quickstart.install
  composer.json
Labels: task, dependencies, release notes, 2.13.x only

#4205 Fixes #4203, Fixes #4216 Update Add to Calendar Modal Links
  modules/custom/az_event/az_event.module
  modules/custom/az_event/templates/az-event-calendar-add-button.html.twig
Labels: enhancement, user experience, 2.13.x only

#4215 Closes #186: Use GitHub Actions for more PR checks.
  .github/workflows/ci.yml
  .github/workflows/security.yml
  .probo.yaml
Labels: enhancement, backport, ci, patch release, developer experience

#4217 Close #1639 remove dependency on media_migration contrib module.
  az_quickstart.install
  composer.json
  modules/custom/az_migration/az_migration.info.yml
  modules/custom/az_migration/migrations/az_media.yml
  modules/custom/az_migration/src/Plugin/migrate/source/AzFileEntity.php
Labels: dependencies, patch release, release notes

#4245 Close #1639 remove dependency on media_migration contrib module. (#4217)
  composer.json
  modules/custom/az_migration/az_migration.info.yml
  modules/custom/az_migration/migrations/az_media.yml
  modules/custom/az_migration/src/Plugin/migrate/source/AzFileEntity.php
Labels: dependencies, 2.13.x only

#4247 #1639: Add missing drupal/migmag module.
  composer.json
Labels: dependencies, migration, patch release

#4254 Closes #4253: Invalid ARIA attribute on Person tab
  modules/custom/az_person/templates/horizontal-tabs--node--az-person--group-tabs.html.twig
Labels: bug, 2.13.x only

#4252 Closes #4251: Use GitHub Actions matrix for PHPUnit + optimize existing tests for concurrency.
  .github/workflows/ci.yml
  modules/custom/az_cas/tests/src/Functional/AzCasDisableLoginFormTest.php
  modules/custom/az_cas/tests/src/Functional/AzCasDisablePasswordResetTest.php
  modules/custom/az_demo/tests/src/Functional/AZDemoContentTest.php
  themes/custom/az_barrio/tests/src/Functional/AzBarrioAdminTest.php
  themes/custom/az_barrio/tests/src/Functional/AzBarrioTest.php
Labels: enhancement, backport, ci, patch release, developer experience

#4268 Closes #4266: Revert removal of jquery_ui_slider and jquery_ui_touch_punch
  az_quickstart.install
  composer.json
Labels: task, dependencies, 2.13.x only

#4271 Closes #4270: Update drupal/block_class from 4.0.0 to 4.0.1 (addresses SA-CONTRIB-2025-043)
  composer.json
Labels: dependencies, high priority, Drupal, patch release, release notes

#4258 Closes #2403: Save UUIDs when importing Quickstart config overrides to prevent deprecation warnings.
  modules/custom/az_core/az_core.post_update.php
  modules/custom/az_core/az_core.services.yml
  modules/custom/az_core/src/AZConfigOverride.php
Labels: bug, 2.13.x only

#4264 Fixes #4262 Profiles Import revision log message does not reflect current time and user
  modules/custom/az_person/az_person_profiles_import/az_person_profiles_import.module
Labels: bug, patch release, Integrations

#4255 Fixes #4122 Exclude noncanonical publications from xmlsitemap
  modules/custom/az_publication/az_publication.module
Labels: bug, publications, 2.13.x only

#4286 Fixes #4284 Check for absent config entities in az_core_post_update_add_missing_config_uuids
  modules/custom/az_core/az_core.post_update.php
Labels: bug, high priority, 2.13.x only

#4265 Fixes #4263 Course Import Instructions
  modules/custom/az_course/az_course.routing.yml
  modules/custom/az_course/src/Form/CourseImportForm.php
Labels: documentation, patch release, Integrations, usability, editor experience

#4282 Closes #4281: Add missing 'assign az_auto_expiring_user role' permission to az_user_admin role.
  config/install/user.role.az_user_admin.yml
Labels: bug, 2.13.x only
