Repository az-digital/az_quickstart, pull requests merged in 2025-06, with the labels that each got.

#4226 Close #4225 Upgrade Javascript components with Arizona Bootstrap 5 compatibility.
  modules/custom/az_accordion/templates/az-accordion.html.twig
  modules/custom/az_event/templates/az-event-calendar-add-button.html.twig
  modules/custom/az_event/templates/az-event-view-occurrences-button.html.twig
  modules/custom/az_finder/config/quickstart/views.view.az_person.yml
  modules/custom/az_finder/src/Plugin/better_exposed_filters/filter/AZFinderTaxonomyIndexTidWidget.php
  modules/custom/az_paragraphs/az_paragraphs_link_group/templates/paragraph--az-link-group--default.html.twig
  modules/custom/az_paragraphs/az_paragraphs_photo_gallery/templates/paragraph--az-photo-gallery.html.twig
  modules/custom/az_person/config/install/views.view.az_person.yml
  modules/custom/az_person/templates/horizontal-tabs--node--az-person--group-tabs.html.twig
  modules/custom/az_select_menu/src/Plugin/Block/AzSelectMenu.php
  themes/custom/az_barrio/config/install/az_barrio.settings.yml
  themes/custom/az_barrio/css/az-barrio-off-canvas-nav.css
  themes/custom/az_barrio/templates/blocks/block--system-menu-block.html.twig
  themes/custom/az_barrio/templates/layout/page.html.twig
  themes/custom/az_barrio/templates/navigation/menu--main.html.twig
Labels: 2.14.x only, Arizona-Bootstrap-5

#4358 Fixes #4192 Remove Chosen from disabled form fields
  modules/custom/az_core/css/az-core-chosen.css
Labels: usability, editor experience, proposal, release notes, 2.14.x only

#4322 Closes #4321: Replace dependabot reviewers config option with updated CODEOWNERS config.
  .github/CODEOWNERS
  .github/dependabot.yml
Labels: task, ci, dependencies

#4419 Closes #4418 Set photo gallery default to grid
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZPhotoGalleryParagraphBehavior.php
Labels: enhancement, proposal, 2.14.x only

#4306 Close #4305 Upgrade Bootstrap Barrio, Views Bootstrap for Arizona Bootstrap 5
  .lando.yml
  composer.json
  themes/custom/az_barrio/az_barrio.theme
  themes/custom/az_barrio/config/install/az_barrio.settings.yml
Labels: dependencies, Drupal, 3.0.x only, Arizona-Bootstrap-5
