Repository az-digital/az_quickstart, pull requests merged in 2025-02, with the labels that each got.

#4032 Closes #4031 Replace symfony security checker with composer audit in GH actions security workflow
  .github/workflows/security.yml
Labels: enhancement, ci

#3916 Closes #3857: Update config schema files that have id fields that are strings to use the machine_name type
  modules/custom/az_event/az_event_trellis/config/schema/az_event_trellis.schema.yml
  modules/custom/az_finder/config/schema/az_finder.schema.yml
  modules/custom/az_publication/config/schema/az_citation_style.schema.yml
  modules/custom/az_publication/config/schema/az_publication_type.schema.yml
Labels: enhancement, 2.13.x only

#4008 Close #3990 Add result summary to finder in az_demo.
  modules/custom/az_demo/config/install/views.view.az_finder.yml
Labels: visual change, 2.13.x only

#4036 Close #4035 Enable smart title for all publication display modes.
  modules/custom/az_demo/data/az_demo_node_publication.json
  modules/custom/az_demo/tests/src/Functional/AZDemoContentTest.php
  modules/custom/az_publication/config/install/core.entity_view_display.node.az_publication.az_publication_reference.yml
  modules/custom/az_publication/config/install/core.entity_view_display.node.az_publication.default.yml
Labels: bug, patch release, publications

#4018 Close #4017 Imagemagick fails to convert animated gifs into animated webps Close #1606 enable animated gifs.
  composer.json
Labels: bug, patch release, editor experience, release notes

#4030 Fixes #3938 Update Trellis events only if content changes
  modules/custom/az_event/az_event_trellis/config/install/migrate_queue_importer.cron_migration.az_event_trellis.yml
  modules/custom/az_event/az_event_trellis/src/Plugin/migrate/source/AZTrellisEventSource.php
  modules/custom/az_event/az_event_trellis/src/Plugin/views/field/AZEventTrellisViewsField.php
Labels: bug, backport, patch release, Integrations, editor experience

#4025 Closes #4024: Extra white space on title-on-image cards having an empty body and a hidden link
  modules/custom/az_card/templates/az-card.html.twig
  modules/custom/az_demo/data/az_demo_card_paragraph.json
Labels: bug, patch release, visual change, 2.12.x only

#3970 Close #3967: Add Masquerade Log module
  composer.json
Labels: enhancement, dependencies, patch release, editor experience, proposal, release notes

#3665 Closes #3550: Add experimental az_user_expire module.
  composer.json
  config/install/user.role.anonymous.yml
  config/install/user.role.authenticated.yml
  config/install/user.role.az_content_admin.yml
  config/install/user.role.az_content_editor.yml
  config/install/user.role.az_html_admin.yml
  config/install/user.role.az_profile_editor.yml
  config/install/user.role.az_user_admin.yml
  modules/custom/az_user_expire/az_user_expire.info.yml
  modules/custom/az_user_expire/config/install/user.role.az_auto_expiring_user.yml
  modules/custom/az_user_expire/config/quickstart/user_expire.settings.yml
Labels: enhancement, proposal, 2.13.x only

#4043 Closes #4042: Update Drupal core from 10.4.1 to 10.4.2
  composer.json
Labels: dependencies, Drupal, 2.13.x only

#4046 #4044: Update Drupal core from 10.3.11 to 10.3.12 (2.12.x)
  composer.json
Labels: dependencies, Drupal, patch release, 2.12.x only

#4045 #4044: Update Drupal core from 10.3.11 to 10.3.12 (2.11.x)
  composer.json
Labels: dependencies, Drupal, patch release, 2.11.x only

#4056 Closes #4049: Add a general view display to AZ Publications view without exposed filters
  modules/custom/az_publication/config/install/views.view.az_publications.yml
Labels: enhancement, patch release, publications

#4072 Close #4071 Skip hyphen when importing enterprise attributes.
  modules/custom/az_core/az_enterprise_attributes_import/config/install/migrate_plus.migration.az_enterprise_attributes_import.yml
Labels: bug, Integrations, trellis

#4066 Close #4065 Remove "Diversity" link from global footer and update land acknowledgement.
  modules/custom/az_global_footer/az_global_footer.install
  modules/custom/az_global_footer/data/az_global_footer.json
  themes/custom/az_barrio/az_barrio.theme
Labels: task, backport, patch release, brand change

#4055 Closes #3394 Enable Masquerade & Masquerade Log modules by default.
  az_quickstart.info.yml
  az_quickstart.install
Labels: enhancement, dependencies, developer experience, release notes, 2.13.x only

#4057 Closes #3789 Add recommendation that developers using macOS CLI should install gpatch.
  CONTRIBUTING.md
Labels: documentation, developer experience

#4060 Closes #3997 Adjust default Chosen width
  modules/custom/az_core/az_core.libraries.yml
  modules/custom/az_core/az_core.module
  modules/custom/az_core/config/quickstart/chosen.settings.yml
  modules/custom/az_core/css/az-core-chosen.css
Labels: bug, editor experience

#4069 Closes #4067: Remove taxonomy vocabulary validation from AZ Publications view displays
  modules/custom/az_publication/config/install/views.view.az_publications.yml
Labels: enhancement, release notes, 2.13.x only

#4081 Closes #4080: Add patch for preventing persistent metatag module TypeError.
  composer.json
Labels: bug, backport, dependencies, high priority, Drupal, patch release

#4077 Close #4038: Update 'Health & Medical' footer link
  modules/custom/az_global_footer/az_global_footer.install
  modules/custom/az_global_footer/data/az_global_footer.json
Labels: patch release

#4073 Closes #1753 Update AZCardWidget card preview classes
  modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php
Labels: bug, editor experience

#4061 Close #3309 Polish the finder counter number to look more like an intentional UI
  modules/custom/az_finder/js/active-filter-count.es6.js
  modules/custom/az_finder/js/active-filter-count.js
  modules/custom/az_finder/src/Plugin/views/exposed_form/QuickstartExposedFilters.php
Labels: enhancement, patch release, visual change, accessibility

#3914 Close #3913 Add new content field to AZ Publication.
  modules/custom/az_demo/data/az_demo_image_file.json
  modules/custom/az_demo/data/az_demo_media_document.json
  modules/custom/az_demo/data/az_demo_node_publication.json
  modules/custom/az_demo/data/az_demo_text_paragraph.json
  modules/custom/az_demo/images/1386px-Leonardo_da_Vinci_-_presumed_self-portrait_-_WGA12798.jpg
  modules/custom/az_demo/media/document/Small-PDF.pdf
  modules/custom/az_demo/media/document/Wilbur_Wildcat_Book_Review_The_Life_of_Leonardo_da_Vinci.pdf
  modules/custom/az_demo/media/document/Wilma_Wildcat_phd_Book_Review_The_Life_of_Leonardo_da_Vinci.pdf
  modules/custom/az_demo/migrations/az_demo_media_document.yml
  modules/custom/az_demo/migrations/az_demo_node_publication.yml
  modules/custom/az_demo/tests/src/Functional/AZDemoContentTest.php
  modules/custom/az_publication/az_publication.info.yml
  modules/custom/az_publication/az_publication.module
  modules/custom/az_publication/config/install/core.entity_form_display.node.az_publication.default.yml
  modules/custom/az_publication/config/install/core.entity_view_display.node.az_publication.az_card.yml
  modules/custom/az_publication/config/install/core.entity_view_display.node.az_publication.az_publication_reference.yml
  modules/custom/az_publication/config/install/core.entity_view_display.node.az_publication.default.yml
  modules/custom/az_publication/config/install/core.entity_view_display.node.az_publication.teaser.yml
  modules/custom/az_publication/config/install/field.field.node.az_publication.field_az_main_content.yml
Labels: enhancement, publications, 2.13.x only

#4088 #4085: Update drupal/core-recommended to 10.3.13 for SA-CORE-2025-001, SA-CORE-2025-002, SA-CORE-2025-003 (2.11.x)
  composer.json
Labels: dependencies, high priority, Drupal, patch release, 2.11.x only

#4087 #4085: Update drupal/core-recommended to 10.3.13 for SA-CORE-2025-001, SA-CORE-2025-002, SA-CORE-2025-003 (2.12.x)
  composer.json
Labels: dependencies, high priority, Drupal, patch release, 2.12.x only

#4091 Closes #3812: Remove deprecated aria_controls variable from az_accordion theme implementation.
  modules/custom/az_accordion/az_accordion.module
  modules/custom/az_accordion/src/Plugin/Field/FieldFormatter/AZAccordionDefaultFormatter.php
Labels: task, 2.13.x only

#4048 Closes #2631 Use selenium-chrome for ddev and minor ddev config updates
  .ddev/commands/web/drush
  .ddev/commands/web/eslint
  .ddev/commands/web/install
  .ddev/commands/web/phpcbf
  .ddev/commands/web/phpcs
  .ddev/commands/web/phpstan
  .ddev/commands/web/phpstan-contrib
  .ddev/commands/web/phpunit
  .ddev/commands/web/phpunit-fastest
  .ddev/commands/web/theme-debug
  .ddev/commands/web/yarn
  .ddev/config.quickstart.yaml
  .ddev/docker-compose.override.yaml
  .ddev/docker-compose.quickstart.yaml
  CONTRIBUTING.md
  phpcs.xml.dist
  phpstan-contrib.neon
  phpstan.neon
Labels: bug, enhancement, ci, dependencies, developer experience

#4100 Fixes #4097, Fixes #4098, Fixes #4099 Handle HTML and tag case in AZBibtex
  modules/custom/az_publication/az_publication_bibtex/src/Plugin/migrate_plus/data_parser/AZBibtex.php
  modules/custom/az_publication/az_publication_bibtex/src/Processor/AZStripHtmlProcessor.php
Labels: bug, backport, patch release, publications

#3760 Closes #3756: Add default “no results” text on all the News views
  modules/custom/az_finder/config/quickstart/views.view.az_news.yml
  modules/custom/az_news/config/install/views.view.az_news.yml
Labels: enhancement, 2.13.x only
