Repository az-digital/az_quickstart, pull requests merged in 2025-08, with the labels that each got.

#4576 Fixes #4518 Disable /dev/shm usage for chromedriver in CI
  .github/workflows/ci.yml
Labels: bug, backport, ci, high priority, patch release, developer experience

#4503 Closes #4400 Closes #4531 Update events for Bootstrap 5 compatibility.
  modules/custom/az_event/az_event.module
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_card.yml
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_card_alternate.yml
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_row.yml
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_row_with_background.yml
  modules/custom/az_event/config/install/core.entity_view_display.taxonomy_term.az_event_categories.az_badge.yml
  modules/custom/az_event/css/az_calendar_filter.css
  modules/custom/az_event/js/az_calendar_filter.es6.js
  modules/custom/az_event/js/az_calendar_filter.js
  modules/custom/az_event/templates/az-event-calendar-add-button.html.twig
  modules/custom/az_event/templates/az-event-view-occurrences-button.html.twig
  themes/custom/az_barrio/css/style.css
Labels: Arizona-Bootstrap-5, 3.x only

#4584 Update drupal/media_library_form_element requirement from 2.1.1 to 2.1.2 (2.x back-port of #4482)
  composer.json
Labels: backport, dependencies, Drupal, patch release, php, 2.x only

#4582 Fixes #4558 Add description subfield to document media (2.x backport of #4560)
  modules/custom/az_demo/data/az_demo_media_document.json
  modules/custom/az_demo/data/az_demo_text_paragraph.json
  modules/custom/az_demo/media/document/PDF-with-Description.pdf
  modules/custom/az_demo/migrations/az_demo_media_document.yml
  modules/custom/az_media/config/install/field.field.media.az_document.field_media_az_document.yml
Labels: 2.x only, minor release

#4583 Fixes #4518 Disable /dev/shm usage for chromedriver in CI (2.x backport of #4576)
  .github/workflows/ci.yml
Labels: ci, patch release, 2.x only

#4578 Closes #4426: Upgrade Drupal core to 10.5 (2.x back-port of #4427)
  .github/workflows/ci.yml
  .prettierrc.json
  composer.json
  package.json
Labels: 2.14.x only, 2.x only, minor release

#4594 Closes #4592: Update prepare-for-minor-release workflow to support dynamic source branch. (2.x back-port of #4593)
  .github/workflows/prepare-for-minor-release.yml
Labels: backport, 2.x only

#4595 Closes #4571: VoiceOver Double Speak issue for accessibility tools. (2.x back-port of #4580)
  themes/custom/az_barrio/templates/layout/page.html.twig
Labels: backport, patch release, 2.x only

#4474 Closes #1885 Adds photo gallery carousel indicators (2.x version)
  modules/custom/az_paragraphs/az_paragraphs_photo_gallery/templates/paragraph--az-photo-gallery.html.twig
  modules/custom/az_paragraphs/css/az_paragraphs_az_photo_gallery.css
Labels: enhancement, 2.x only, minor release

#4536 Closes #4535, #1885 Adds photo gallery indicators (Bootstrap 5 version)
  modules/custom/az_paragraphs/az_paragraphs_photo_gallery/templates/paragraph--az-photo-gallery.html.twig
  modules/custom/az_paragraphs/css/az_paragraphs_az_photo_gallery.css
Labels: Arizona-Bootstrap-5, 3.x only

#4598 Closes #4597: Fix validation logic in prepare-for-minor-release workflow.
  .github/workflows/prepare-for-minor-release.yml
Labels: bug, backport, ci

#4599 Closes #4597: Fix validation logic in prepare-for-minor-release workflow. (2.x back-port of #4598)
  .github/workflows/prepare-for-minor-release.yml
Labels: 2.x only

#4600 #4597: Fix more errors in prepare-for-minor-release workflow.
  .github/workflows/prepare-for-minor-release.yml
Labels: bug, ci, 3.x only

#4602 #4597: Another fix for prepare-for-minor-release workflow (2.x)
  .github/workflows/prepare-for-minor-release.yml
Labels: bug, ci, 2.x only

#4603 #4597: Another fix for prepare-for-minor-release workflow
  .github/workflows/prepare-for-minor-release.yml
Labels: bug, ci

#4608 #4597: Update main branch version of prepare-for-minor-release workflow.
  .github/workflows/prepare-for-minor-release.yml
Labels: bug, ci, 3.x only

#4559 Closes #4138: Update AZ Person horizontal tabs template for Arizona Bootstrap 5
  modules/custom/az_person/config/install/core.entity_view_display.node.az_person.default.yml
  modules/custom/az_person/css/az_person.css
  modules/custom/az_person/templates/horizontal-tabs--node--az-person--group-tabs.html.twig
Labels: Arizona-Bootstrap-5, 3.x only

#4466 Closes #4397: Update page to work with Bootstrap 5
  modules/custom/az_flexible_page/config/install/core.entity_view_display.node.az_flexible_page.az_card.yml
  modules/custom/az_flexible_page/config/install/core.entity_view_display.node.az_flexible_page.az_row.yml
  modules/custom/az_flexible_page/config/install/core.entity_view_display.node.az_flexible_page.az_row_with_background.yml
  modules/custom/az_flexible_page/css/az_flexible_page.theme.css
Labels: Arizona-Bootstrap-5, 3.x only

#4551 Closes #4398: Update AZ News to work with Bootstrap 5
  modules/custom/az_finder/config/quickstart/views.view.az_news.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_card.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_feature.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_marquee.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_media_list.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_medium_media_list.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_minimal_media_list.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_row.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_row_with_background.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_small_row.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.default.yml
  modules/custom/az_news/config/install/core.entity_view_display.taxonomy_term.az_news_tags.az_badge.yml
Labels: Arizona-Bootstrap-5, 3.x only

#4373 Fixes #4372, Fixes #3428 Add EDS Module, Secrets Management
  .gitignore
  .lando.yml
  composer.json
  modules/custom/az_eds/az_eds.info.yml
  modules/custom/az_eds/config/install/key.config_override.az_eds_address.yml
  modules/custom/az_eds/config/install/key.config_override.az_eds_dn.yml
  modules/custom/az_eds/config/install/key.config_override.az_eds_password.yml
  modules/custom/az_eds/config/install/key.key.az_eds_address.yml
  modules/custom/az_eds/config/install/key.key.az_eds_dn.yml
  modules/custom/az_eds/config/install/key.key.az_eds_password.yml
  modules/custom/az_eds/config/install/ldap_servers.server.az_eds.yml
  modules/custom/az_secrets/az_secrets.info.yml
  modules/custom/az_secrets/az_secrets.module
  modules/custom/az_secrets/src/Plugin/KeyProvider/AZSecrets.php
Labels: enhancement, Integrations, proposal, 3.x only, minor release

#4624 Fixes #4621 Event views without delta generate warnings
  modules/custom/az_event/az_event.module
Labels: bug, patch release, backport-2.x

#4628 #4537: Remove delete-branch option from pr-backport workflow.
  .github/workflows/pr-backport.yml
Labels: bug, ci, developer experience

#4631 #4537: Use GH CLI for PR creation in pr-backport workflow.
  .github/workflows/pr-backport.yml
Labels: bug, ci, developer experience

#4629 Update drupal/linkit requirement from 7.0.7 to 7.0.8 (2.x back-port of #4614)
  composer.json
Labels: backport, dependencies, patch release, 2.x-only

#4634 Fixes #4621 Event views without delta generate warnings (2.x backport of #4624)
  modules/custom/az_event/az_event.module
Labels: backport, patch release, 2.x-only

#4324 Closes #4323: Update text background color classes for Arizona Bootstrap 5
  modules/custom/az_alphabetical_listing/templates/views-view--az-alphabetical-listing.html.twig
  modules/custom/az_card/templates/az-card.html.twig
  modules/custom/az_demo/data/az_demo_splitscreen_paragraph.json
  modules/custom/az_demo/data/az_demo_text_background_paragraph.json
  modules/custom/az_flexible_page/config/install/core.entity_view_display.node.az_flexible_page.az_card.yml
  modules/custom/az_flexible_page/config/install/core.entity_view_display.node.az_flexible_page.az_row.yml
  modules/custom/az_flexible_page/config/install/core.entity_view_display.node.az_flexible_page.az_row_with_background.yml
  modules/custom/az_migration/migrations/az_paragraph_card_deck.yml
  modules/custom/az_migration/migrations/az_paragraph_content_marquee.yml
  modules/custom/az_migration/migrations/az_paragraph_full_width_bg_wrapper.yml
  modules/custom/az_migration/migrations/az_paragraph_full_width_media_row.yml
  modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsCalloutFieldMerge.php
  modules/custom/az_paragraphs/az_paragraphs_photo_gallery/templates/paragraph--az-photo-gallery.html.twig
  modules/custom/az_paragraphs/az_paragraphs_splitscreen/az_paragraphs_splitscreen.install
  modules/custom/az_paragraphs/az_paragraphs_text_background/az_paragraphs_text_background.install
  modules/custom/az_paragraphs/az_paragraphs_text_media/az_paragraphs_text_media.install
  modules/custom/az_paragraphs/az_paragraphs_views_side_by_side/config/install/core.entity_form_display.paragraph.az_views_side_by_side.default.yml
  modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehaviorSettings.php
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZSplitScreenParagraphBehavior.php
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithBackgroundParagraphBehavior.php
  themes/custom/az_barrio/css/style.css
  themes/custom/az_barrio/templates/blocks/block--az-barrio-offcanvas-searchform.html.twig
  themes/custom/az_barrio/templates/layout/page.html.twig
  themes/custom/az_barrio/templates/navigation/menu--sidebar.html.twig
Labels: high priority, Arizona-Bootstrap-5, 3.x only

#4619 Closes #4618: Enable automated update PRs for Arizona Bootstrap 5.x releases.
  .github/workflows/arizona-bootstrap-release.yml
Labels: ci, high priority, Arizona-Bootstrap-5

#4638 Closes #4425 Update issue templates with a public content warning
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/spike.md
  .github/ISSUE_TEMPLATE/task.md
  .github/ISSUE_TEMPLATE/user_story.md
Labels: documentation, enhancement, developer experience

#4296 Closes #4295 Update RELEASES.md with LTS and major policies.
  RELEASES.md
Labels: documentation, release notes

#4654 Close #4653 Replace visually-hidden focusable class with visually-hidden-focusable
  modules/custom/az_finder/az_finder.module
  themes/custom/az_barrio/templates/layout/html.html.twig
Labels: accessibility, Arizona-Bootstrap-5, 3.x only

#4672 Closes #4591 - Update cases of card-clickable to stretched link
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_card.yml
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_card_alternate.yml
  modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_row_with_background.yml
  modules/custom/az_flexible_page/config/install/core.entity_view_display.node.az_flexible_page.az_card.yml
  modules/custom/az_flexible_page/config/install/core.entity_view_display.node.az_flexible_page.az_row.yml
  modules/custom/az_flexible_page/config/install/core.entity_view_display.node.az_flexible_page.az_row_with_background.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_card.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_feature.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_marquee.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_media_list.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_medium_media_list.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_minimal_media_list.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_row.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_row_with_background.yml
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_small_row.yml
  modules/custom/az_person/config/install/core.entity_view_display.node.az_person.az_row_with_background.yml
  modules/custom/az_person/css/az_person.css
  modules/custom/az_publication/config/install/core.entity_view_display.node.az_publication.az_card.yml
Labels: high priority, Arizona-Bootstrap-5, 3.x only

#4678 Fixes #4675 Update EDS imports to migrate_tools 6.1.x API
  modules/custom/az_person/az_person_eds_import/src/Form/AZPersonEDSImportForm.php
Labels: bug, high priority, Integrations, 3.x only

#4665 Closes #4663 Update theme settings to account for Bootstrap 5.
  themes/custom/az_barrio/az_barrio.post_update.php
  themes/custom/az_barrio/includes/common.inc
  themes/custom/az_barrio/theme-settings.php
Labels: high priority, Arizona-Bootstrap-5, 3.x only

#4683 Close #4682 Update ckeditor5-stylesheets to Arizona Bootstrap 5 and remove ckeditor_stylesheets from az_barrio.info.yml
  themes/custom/az_barrio/az_barrio.info.yml
Labels: good first issue, visual change, editor experience, Arizona-Bootstrap-5, 3.x only

#4686 Close #4684 add placeholder override to arizona-bootstrap-node-form-overrides.css
  modules/custom/az_core/css/arizona-bootstrap-node-form-overrides.css
Labels: editor experience, Arizona-Bootstrap-5, 3.x only

#4411 Fixes #4410 Update seboettg/citeproc-php requirement from 2.6.2 to 2.7.0.
  composer.json
  modules/custom/az_demo/tests/src/Functional/AZDemoContentTest.php
Labels: enhancement, dependencies, publications, 3.x only, minor release

#4698 Close #4697 Update taxonomy badge displays to use Arizona Bootstrap 5 classes
  modules/custom/az_flexible_page/config/install/core.entity_view_display.taxonomy_term.az_page_categories.az_badge.yml
  modules/custom/az_person/config/install/core.entity_view_display.taxonomy_term.az_person_categories.az_badge.yml
  modules/custom/az_person/config/install/core.entity_view_display.taxonomy_term.az_person_categories_secondary.az_badge.yml
Labels: bug, patch release, Arizona-Bootstrap-5, 3.x only

#4699 #3471, #4167: Add D11 compatibility for az_person_eds_import.
  modules/custom/az_person/az_person_eds_import/az_person_eds_import.info.yml
Labels: bug, 3.x only

#4716 Fixes #4713 az_news_export REST endpoint fails with NotNormalizableValueException
  modules/custom/az_news/az_news_export/src/Normalizer/AZNewsDataEmptyNormalizer.php
Labels: bug, high priority, news, trellis, 3.x only

#4729 Closes #4727: Chevron in Photo Gallery previous button is misaligned
  modules/custom/az_paragraphs/az_paragraphs_photo_gallery/templates/photo-gallery-carousel.html.twig
Labels: bug, 3.x only

#4726 Closes #4725 Add regression patch for embed media dialog boxes.
  composer.json
Labels: bug, Drupal, editor experience, 3.x only

#4722 Closes #4711 - Restore Claro Title and Message Styles that were overriden by AZBS 5
  modules/custom/az_core/css/arizona-bootstrap-node-form-overrides.css
Labels: bug, editor experience, Arizona-Bootstrap-5, 3.x only

#4721 Close #4718 Fix Alerts in az_barrio for Arizona Bootstrap 5.
  composer.json
  themes/custom/az_barrio/az_barrio.info.yml
  themes/custom/az_barrio/az_barrio.libraries.yml
  themes/custom/az_barrio/config/install/az_barrio.settings.yml
  themes/custom/az_barrio/js/toasts.es6.js
  themes/custom/az_barrio/js/toasts.js
Labels: visual change, usability, editor experience, Arizona-Bootstrap-5

#4734 Update prepare-for-minor-release workflow to support creating initial minor release branch for a major release (e.g. 3.0.x).
  .github/workflows/prepare-for-minor-release.yml
Labels: bug, ci, high priority

#4736 More fixes/cleanup for prepre-for-minor-release workflow.
  .github/workflows/prepare-for-minor-release.yml
Labels: bug, ci, high priority

#4747 Close #4746 Changing all instances of btn-block to w-100
  modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php
  modules/custom/az_demo/data/az_demo_card_paragraph.json
  modules/custom/az_migration/migrations/az_paragraph_card_deck.yml
  modules/custom/az_migration/migrations/az_paragraph_single_card.yml
  modules/custom/az_paragraphs/az_paragraphs_cards/az_paragraphs_cards.install
Labels: bug, high priority, Arizona-Bootstrap-5, 3.x only

#4749 Closes #4748: Add mappings for UA Bootstrap classes deprecated in AZ Bootstrap 2 to AZBootstrapMarkupConverter.
  modules/custom/az_core/src/Utility/AZBootstrapMarkupConverter.php
Labels: bug, high priority, Arizona-Bootstrap-5, 3.x only
