Repository az-digital/az_quickstart, pull requests merged in 2025-07, with the labels that each got.

#4457 Closes #4456: Add bootstrap_barrio patch to fix tabledrag.js issue causing test failures.
  composer.json
Labels: bug, ci, dependencies, Drupal, 3.0.x only, Arizona-Bootstrap-5

#4454 Closes #4453 Disable email hostname on CAS bulk add user form.
  modules/custom/az_cas/az_cas.module
Labels: enhancement, usability, editor experience, user experience, proposal

#4365 Closes #4364 Update the splitscreen update functions for changed release version.
  modules/custom/az_paragraphs/az_paragraphs_splitscreen/az_paragraphs_splitscreen.install
Labels: 2.14.x only

#4502 #4446: Fix broken .lando.yml file (follow-up to #4448) (2.x version).
  .lando.yml
Labels: bug, ci, high priority, developer experience, 2.x only

#4500 Fine tune dependabot rules (#4446 follow-up).
  .github/dependabot.yml
Labels: enhancement, backport, ci, dependencies

#4510 Closes #4428 Remove presentation role from pagination
  themes/custom/az_barrio/templates/navigation/pager.html.twig
Labels: bug, backport, patch release, accessibility

#4437 Closes #4393 Update text on media for Bootstrap 5 compatibility
  modules/custom/az_demo/data/az_demo_text_media_paragraph.json
  modules/custom/az_paragraphs/az_paragraphs_text_media/az_paragraphs_text_media.install
  modules/custom/az_paragraphs/az_paragraphs_text_media/templates/media--az-remote-video--az-background.html.twig
  modules/custom/az_paragraphs/css/az_paragraphs_az_text_media.css
  modules/custom/az_paragraphs/src/Plugin/Field/FieldFormatter/AZBackgroundMediaFormatter.php
  modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehaviorSettings.php
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithMediaParagraphBehavior.php
  themes/custom/az_barrio/css/style.css
Labels: Arizona-Bootstrap-5, 3.x only

#4447 Closes #3657 Allow alt text on images to be indicative of decorative images
  composer.json
  modules/custom/az_media/az_media.info.yml
  modules/custom/az_media/az_media.install
  modules/custom/az_media/config/install/core.entity_form_display.media.az_image.default.yml
  modules/custom/az_media/config/install/core.entity_form_display.media.az_image.media_library.yml
  modules/custom/az_media/config/install/core.entity_form_display.media.az_remote_video.default.yml
  modules/custom/az_media/config/install/field.field.media.az_image.field_media_az_image.yml
  modules/custom/az_media/config/install/field.field.media.az_remote_video.field_media_az_image.yml
Labels: enhancement, backport, patch release, accessibility, editor experience

#4552 #3657: Fix invalid config resulting from faulty merge of #4538 into 2.13.x
  modules/custom/az_media/config/install/core.entity_form_display.media.az_image.default.yml
  modules/custom/az_media/config/install/core.entity_form_display.media.az_image.media_library.yml
Labels: bug, high priority, patch release, 2.13.x only
