Repository az-digital/az_quickstart, pull requests merged in 2025-01, with the labels that each got.

#3955 Close #3954 Update patch for viewsreference label field formatter.
  composer.json
Labels: dependencies, patch release

#3960 Closes #3697 Layout of the menu link edit form does not match the node edit form
  modules/custom/az_core/az_core.module
Labels: bug, patch release

#3957 Close 1831 Update AZ News default display to fix contacts heading tags
  modules/custom/az_news/templates/field--node--az-news.html.twig
Labels: enhancement, low priority, patch release, accessibility

#3975 Fixes #3974 Broken Coding Standards Sniffs
  modules/custom/az_core/src/Drush/Commands/AZEntityListCommands.php
  modules/custom/az_publication/az_publication.module
Labels: bug, high priority, developer experience

#3879 Closes #3869: Enhance resolution of images for Marketing Cloud emails
  modules/custom/az_marketing_cloud/config/install/image.style.az_marketing_cloud_30_70_layout.yml
  modules/custom/az_marketing_cloud/config/install/image.style.az_marketing_cloud_50_50_layout.yml
  modules/custom/az_marketing_cloud/config/install/image.style.az_marketing_cloud_hero_layout.yml
Labels: backport, patch release, editor experience

#3966 Closes #3003: Add menu parent to chosen settings
  modules/custom/az_core/config/quickstart/chosen.settings.yml
Labels: enhancement, visual change, editor experience, 2.13.x only

#3364 Fixes #3362 Profiles Integration
  modules/custom/az_person/az_person.module
  modules/custom/az_person/az_person_profiles_import/az_person_profiles_import.info.yml
  modules/custom/az_person/az_person_profiles_import/az_person_profiles_import.links.task.yml
  modules/custom/az_person/az_person_profiles_import/az_person_profiles_import.module
  modules/custom/az_person/az_person_profiles_import/az_person_profiles_import.routing.yml
  modules/custom/az_person/az_person_profiles_import/az_person_profiles_import.services.yml
  modules/custom/az_person/az_person_profiles_import/config/install/az_person_profiles_import.settings.yml
  modules/custom/az_person/az_person_profiles_import/config/schema/az_person_profiles_import.schema.yml
  modules/custom/az_person/az_person_profiles_import/migrations/az_person_profiles_import.yml
  modules/custom/az_person/az_person_profiles_import/src/EventSubscriber/AZPersonProfilesImportEventSubscriber.php
  modules/custom/az_person/az_person_profiles_import/src/Form/AZPersonProfilesImportForm.php
  modules/custom/az_person/az_person_profiles_import/src/Form/AZPersonProfilesImportSettingsForm.php
  modules/custom/az_person/az_person_profiles_import/src/Plugin/migrate/process/AZPersonDegrees.php
  modules/custom/az_person/az_person_profiles_import/src/Plugin/migrate_plus/data_fetcher/AZProfilesAPIFetcher.php
  modules/custom/az_person/az_person_profiles_import/src/Plugin/migrate_plus/data_parser/AZPersonProfilesImportJson.php
Labels: enhancement, Integrations, editor experience, 2.12.x only

#3977 Closes #3976: Update drupal/core-recommended to 10.3.11
  composer.json
Labels: backport, dependencies, Drupal, patch release

#3933 Closes #3821: Make the # link stay at the current page
  modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php
Labels: bug, patch release

#3995 Closes #3994 Zero margin styles in CKEditor have no effect
  modules/custom/az_paragraphs/config/optional/editor.editor.az_standard.yml
Labels: bug, enhancement, patch release, editor experience

#3987 Closes #1897: Add accordion demo content
  modules/custom/az_demo/data/az_demo_page_node.json
  modules/custom/az_demo/data/az_demo_paragraph_accordion.json
  modules/custom/az_demo/migrations/az_demo_page_node.yml
  modules/custom/az_demo/migrations/az_demo_paragraph_accordion.yml
Labels: enhancement, low priority, visual change, release notes

#3935 Closes #3934: Upgrade Drupal core to 10.4.x
  composer.json
  config/install/user.role.az_content_admin.yml
  config/install/user.role.az_profile_editor.yml
  config/optional/image.style.max_1300x1300.yml
  config/optional/image.style.max_2600x2600.yml
  config/optional/image.style.max_325x325.yml
  config/optional/image.style.max_650x650.yml
  modules/custom/az_demo/config/optional/block.block.az_barrio_views_block__az_publications_az_author_person.yml
Labels: dependencies, Drupal, 2.13.x only

#4004 Fixes #4003 Allow Converted UAQS Basic Pages in Menu link migration.
  modules/custom/az_migration/migrations/az_menu_links.yml
Labels: bug, backport, migration, patch release

#3859 Closes #3820 Full-width paragraphs have a different width in the Content region compared to other regions
  modules/custom/az_paragraphs/css/az_paragraphs_full_width.css
  modules/custom/az_paragraphs/js/az_paragraphs_full_width.es6.js
  modules/custom/az_paragraphs/js/az_paragraphs_full_width.js
  themes/custom/az_barrio/css/style.css
Labels: bug, visual change, 2.13.x only

#4009 Closes #3992: Remove FieldType Categories
  modules/custom/az_accordion/src/Plugin/Field/FieldType/AZAccordionItem.php
  modules/custom/az_card/src/Plugin/Field/FieldType/AZCardItem.php
Labels: bug, patch release, developer experience

#4012 Closes #4011: Upgrade google_tag for SA-CONTRIB-2025-011, SA-CONTRIB-2025-012
  composer.json
Labels: bug, backport, dependencies, high priority, Drupal, patch release, release notes

#2961 Close #2959 refactor AZParagraphsItem migrate source plugin.
  modules/custom/az_migration/src/Plugin/migrate/source/AZParagraphsItem.php
Labels: enhancement, migration, patch release
