Repository az-digital/az_quickstart, pull requests merged in 2025-05, with the labels that each got.

#4308 Closes #4307: Update global footer to use lowercase U in "The university"
  themes/custom/az_barrio/az_barrio.theme
Labels: patch release, release notes

#4331 Closes #4330: Fix red bar height when institutional wordmark is disabled.
  themes/custom/az_barrio/az_barrio.libraries.yml
Labels: bug, backport, patch release, visual change

#4320 Fixes #4319 Trellis Event API requests use wrong timezone
  modules/custom/az_event/az_event_trellis/src/Plugin/views/filter/AZEventTrellisViewsDateFilter.php
Labels: bug, backport, patch release, Integrations, usability, editor experience, trellis

#4335 Close #1251 separate CSS from JS in Arizona Bootstrap and deprecate az_barrio/arizona-bootstrap library.
  modules/custom/az_accordion/az_accordion.libraries.yml
  modules/custom/az_alphabetical_listing/az_alphabetical_listing.libraries.yml
  modules/custom/az_core/az_core.install
  modules/custom/az_core/az_core.libraries.yml
  modules/custom/az_paragraphs/az_paragraphs.libraries.yml
  modules/custom/az_paragraphs/az_paragraphs_splitscreen/az_paragraphs_splitscreen.libraries.yml
  modules/custom/az_select_menu/az_select_menu.libraries.yml
  themes/custom/az_barrio/az_barrio.libraries.yml
  themes/custom/az_barrio/az_barrio.post_update.php
  themes/custom/az_barrio/az_barrio.theme
  themes/custom/az_barrio/config/install/az_barrio.settings.yml
  themes/custom/az_barrio/config/schema/az_barrio.schema.yml
  themes/custom/az_barrio/theme-settings.php
Labels: dependencies, patch release, release notes, Arizona-Bootstrap-5

#4333 Fixes #4327 Add to Calendar link fails for Event nodes with long descriptions
  modules/custom/az_event/az_event.module
Labels: bug, patch release, Integrations, user experience, release notes

#4329 Closes #4328: Update Drupal core from 10.4.6 to 10.4.7
  composer.json
Labels: dependencies, Drupal, 2.13.x only

#4292 Closes #4276: Fix missing user role bulk actions
  composer.json
  config/install/system.action.user_add_role_action.administrator.yml
  config/install/system.action.user_add_role_action.az_content_admin.yml
  config/install/system.action.user_add_role_action.az_content_editor.yml
  config/install/system.action.user_add_role_action.az_html_admin.yml
  config/install/system.action.user_add_role_action.az_profile_editor.yml
  config/install/system.action.user_add_role_action.az_user_admin.yml
  config/install/system.action.user_remove_role_action.administrator.yml
  config/install/system.action.user_remove_role_action.az_content_admin.yml
  config/install/system.action.user_remove_role_action.az_content_editor.yml
  config/install/system.action.user_remove_role_action.az_html_admin.yml
  config/install/system.action.user_remove_role_action.az_profile_editor.yml
  config/install/system.action.user_remove_role_action.az_user_admin.yml
  modules/custom/az_user_expire/config/install/system.action.user_add_role_action.az_auto_expiring_user.yml
  modules/custom/az_user_expire/config/install/system.action.user_remove_role_action.az_auto_expiring_user.yml
Labels: bug, Drupal, patch release, editor experience, 2.13.x only

#4317 Closes #4278: events show wrong date in view listings other than calendar
  modules/custom/az_demo/config/install/views.view.az_finder.yml
  modules/custom/az_event/az_event.module
Labels: bug, backport, patch release

#4259 Closes #2708 Enable AZ Card media edit button in paragraphs.
  .gitignore
  modules/custom/az_card/src/Element/AZMediaLibrary.php
  modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php
Labels: enhancement, QS1 feature parity, editor experience, 2.14.x only

#4341 Fixes #4338 Prepopulate Alphabetical index letters on AZ Person
  modules/custom/az_person/az_person.module
Labels: enhancement, usability, editor experience, 2.14.x only

#4355 Closes #4354: Address PHPCS failure caused by updated Drupal coding standard.
  modules/custom/az_event/az_event.views.inc
Labels: bug, blocker, ci

#4351 Closes #3796 Remove modules deprecated as of 2.12.x
  az_quickstart.install
  composer.json
Labels: dependencies, 2.14.x only

#4359 Closes #4222 Use carousel image style for paragraph photo gallery slider
  modules/custom/az_paragraphs/az_paragraphs_photo_gallery/templates/paragraph--az-photo-gallery.html.twig
Labels: enhancement, visual change, release notes

#4294 Fixes #4291 AZ Event View Caching
  modules/custom/az_event/az_event.module
Labels: bug, usability, user experience
