Repository az-digital/az_quickstart, pull requests merged in 2025-03, with the labels that each got.

#3876 Closes #3762: Re-save and re-export all views config in order to capture & resolve the configuration drift issue
  modules/custom/az_alphabetical_listing/config/install/views.view.az_alphabetical_listing.yml
  modules/custom/az_publication/config/install/views.view.az_publications_curate.yml
Labels: task, 2.13.x only

#4092 Closes #2764 Add Quickstart Analytics permission and toolbar link check.
  config/install/user.role.az_content_admin.yml
  modules/custom/az_google_tag/az_google_tag.module
  modules/custom/az_google_tag/az_google_tag.permissions.yml
Labels: enhancement, editor experience, user experience

#4103 Closes #4094 Add Title Color setting to Card Decks
  modules/custom/az_migration/migrations/az_paragraph_card_deck.yml
  modules/custom/az_paragraphs/az_paragraphs_cards/az_paragraphs_cards.module
  modules/custom/az_paragraphs/az_paragraphs_cards/config/install/field.field.paragraph.az_cards.field_az_title.yml
  modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZCardsParagraphBehavior.php
Labels: enhancement, 2.13.x only

#4113 Closes #4112: Add past row display to AZ Events view
  modules/custom/az_event/config/install/views.view.az_events.yml
  modules/custom/az_finder/config/quickstart/views.view.az_events.yml
Labels: needs-CWS-testing, editor experience, release notes

#4115 Closes #4114 Add contextual link to finder exposed filters block for finder settings.
  modules/custom/az_finder/az_finder.links.contextual.yml
  modules/custom/az_finder/src/Plugin/better_exposed_filters/filter/AZFinderTaxonomyIndexTidWidget.php
Labels: enhancement, editor experience, 2.13.x only

#4101 Closes #2721 Add xmlsitemap content types
  modules/custom/az_seo/az_seo.install
  modules/custom/az_seo/az_seo.module
  modules/custom/az_seo/config/quickstart/xmlsitemap.settings.node.az_event.yml
  modules/custom/az_seo/config/quickstart/xmlsitemap.settings.node.az_news.yml
  modules/custom/az_seo/config/quickstart/xmlsitemap.settings.node.az_person.yml
  modules/custom/az_seo/config/quickstart/xmlsitemap.settings.node.az_publication.yml
Labels: documentation, enhancement, release notes, 2.13.x only

#4129 Closes #4128: Update Drupal core from 10.4.3 to 10.4.4
  composer.json
Labels: dependencies, Drupal, 2.13.x only

#4134 #4132: Update drupal/core-recommended to 10.3.14 for SA-CORE-2025-004 (2.12.x)
  composer.json
Labels: dependencies, high priority, Drupal, patch release, release notes, 2.12.x only

#4135 #4132: Update drupal/core-recommended to 10.3.14 for SA-CORE-2025-004 (2.11.x)
  composer.json
Labels: dependencies, high priority, Drupal, patch release, 2.11.x only, release notes

#4110 Fixes #4010 Remote Media Migration for API Images
  composer.json
  modules/custom/az_event/az_event_trellis/az_event_trellis.info.yml
  modules/custom/az_event/az_event_trellis/az_event_trellis.install
  modules/custom/az_event/az_event_trellis/config/install/migrate_plus.migration.az_trellis_events.yml
  modules/custom/az_event/az_event_trellis/migrations/az_trellis_events_files.yml
  modules/custom/az_event/az_event_trellis/migrations/az_trellis_events_media.yml
  modules/custom/az_event/az_event_trellis/src/Plugin/views/field/AZEventTrellisViewsField.php
  modules/custom/az_migration/az_migration_remote/az_migration_remote.info.yml
  modules/custom/az_migration/az_migration_remote/az_migration_remote.services.yml
  modules/custom/az_migration/az_migration_remote/src/MigrationRemoteTools.php
  modules/custom/az_migration/az_migration_remote/src/Plugin/migrate/process/MigrationRemoteFile.php
  modules/custom/az_person/az_person_profiles_import/az_person_profiles_import.info.yml
  modules/custom/az_person/az_person_profiles_import/az_person_profiles_import.install
  modules/custom/az_person/az_person_profiles_import/migrations/az_person_profiles_import.yml
  modules/custom/az_person/az_person_profiles_import/migrations/az_person_profiles_import_files.yml
  modules/custom/az_person/az_person_profiles_import/migrations/az_person_profiles_import_media.yml
  modules/custom/az_person/az_person_profiles_import/src/Form/AZPersonProfilesImportForm.php
Labels: enhancement, help wanted, Integrations, needs-CWS-testing, user experience, trellis, release notes, 2.13.x only

#4127 Fixes #4119 Update Profiles Integration Migration Fields
  modules/custom/az_person/az_person.module
  modules/custom/az_person/az_person_profiles_import/az_person_profiles_import.module
  modules/custom/az_person/az_person_profiles_import/migrations/az_person_profiles_import.yml
  modules/custom/az_person/az_person_profiles_import/src/Plugin/migrate/process/AZPersonNested.php
Labels: enhancement, high priority, Integrations, 2.13.x only

#4126 Closes #4118 Refactor Text on Media YouTube JavaScript library
  modules/custom/az_paragraphs/az_paragraphs_text_media/az_paragraphs_text_media.libraries.yml
  modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_youtube.es6.js
  modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_youtube.js
  modules/custom/az_paragraphs/src/Plugin/Field/FieldFormatter/AZBackgroundMediaFormatter.php
Labels: task, 2.13.x only

#4149 Closes #4148: Update Global Footer from Title IX/Non-Discrimination to Nondiscrimination
  modules/custom/az_global_footer/az_global_footer.install
  modules/custom/az_global_footer/data/az_global_footer.json
Labels: backport, high priority, patch release

#4143 Fixes #4142 Profiles Integration Use Preferred Names
  modules/custom/az_person/az_person_profiles_import/migrations/az_person_profiles_import.yml
  modules/custom/az_person/az_person_profiles_import/src/Plugin/migrate/process/AZPersonEmptyCoalesce.php
Labels: bug, backport, patch release, Integrations

#4147 Closes #3500: Modify Marquee display of News to use the Thumbnail Image instead of the Featured Image
  modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_marquee.yml
Labels: visual change, release notes, 2.13.x only

#4151 Fixes #4040 Map enterprise attributes (v3 API)
  modules/custom/az_event/az_event_trellis/config/install/migrate_plus.migration.az_trellis_events.yml
  modules/custom/az_event/az_event_trellis/src/TrellisHelper.php
Labels: high priority, 2.13.x only
